import assert from 'node:assert/strict';
import test from 'node:test';
import type { AccessTokenClaims, AccessTokenService } from '../../src/modules/auth/crypto.js';
import type { ModerationRouterDependencies } from '../../src/modules/moderation/router.js';
import { createInMemoryRequestIssueRepository, createRequestIssueService } from '../../src/modules/moderation/request-issues.js';
import { createApiServer, startApiServer, stopApiServer } from '../../src/server.js';

const propertyId = '2123456789abcdef01234567'; const reportId = '3123456789abcdef01234567'; const reporter = '0123456789abcdef01234567';
const tokens: AccessTokenService = { issue() { return 'x'; }, verify(token) { return { iss: 'sadat-real-estate-api', aud: 'sadat-real-estate', sub: reporter, sid: '4123456789abcdef01234567', role: token === 'admin' ? 'admin' : 'seeker', status: token === 'pending' ? 'pending_review' : 'verified', iat: 1, exp: 2, jti: 'j' } as AccessTokenClaims; } };
const service: ModerationRouterDependencies['service'] = { async create() { return { id: reportId, propertyId, reason: 'duplicate', status: 'open', version: 0, createdAt: '2026-08-14T08:00:00.000Z', updatedAt: '2026-08-14T08:00:00.000Z' }; }, async list() { return { items: [{ id: reportId, propertyId, reporterId: reporter, reason: 'duplicate', status: 'open', version: 0, createdAt: '2026-08-14T08:00:00.000Z', updatedAt: '2026-08-14T08:00:00.000Z' }], page: 1, limit: 20, total: 1 }; }, async resolve() { return { id: reportId, propertyId, reason: 'duplicate', status: 'resolved', resolutionReason: 'Resolved report', version: 1, createdAt: '2026-08-14T08:00:00.000Z', updatedAt: '2026-08-14T08:00:00.000Z' }; }, async listAccountReports() { return { items: [{ id: reportId, accountId: reporter, accountRoleType: 'seeker', reporterId: propertyId, reason: 'Reported account has inaccurate information', status: 'open', relatedReports: 2, version: 0, createdAt: '2026-08-14T08:00:00.000Z', updatedAt: '2026-08-14T08:00:00.000Z' }], page: 1, limit: 20, total: 1 }; }, async resolveAccountReport() { return { id: reportId, accountId: reporter, accountRoleType: 'seeker', reason: 'Reported account has inaccurate information', status: 'resolved', resolutionReason: 'Resolved account report', version: 1, createdAt: '2026-08-14T08:00:00.000Z', updatedAt: '2026-08-14T08:00:00.000Z' }; } };
const requestIssues = createRequestIssueService({ repository: createInMemoryRequestIssueRepository() });
async function run(fn: (url: string) => Promise<void>) { const server = createApiServer({ database: { isReady: async () => true }, moderation: { service, accessTokens: tokens, requestIssues } }); const address = await startApiServer(server, { host: '127.0.0.1', port: 0 }); try { await fn(`http://127.0.0.1:${address.port}`); } finally { await stopApiServer(server); } }
const request = (url: string, method: string, path: string, token: string, body?: unknown) => fetch(url + path, { method, headers: { Authorization: `Bearer ${token}`, ...(body ? { 'Content-Type': 'application/json' } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });

test('property, account, and request reports enforce authentication, admin roles, strict input, and resolution routes', async () => run(async url => { assert.equal((await request(url, 'POST', `/api/v1/provider/properties/${propertyId}/reports`, 'seeker', { reason: 'duplicate', details: 'Duplicate property report' })).status, 201); assert.equal((await request(url, 'POST', `/api/v1/provider/properties/${propertyId}/reports`, 'pending', { reason: 'duplicate' })).status, 401); assert.equal((await request(url, 'GET', '/api/v1/admin/property-reports', 'seeker')).status, 403); assert.equal((await request(url, 'GET', '/api/v1/admin/property-reports', 'admin')).status, 200); assert.equal((await request(url, 'POST', `/api/v1/admin/property-reports/${reportId}/resolve`, 'admin', { version: 0, action: 'resolve', reason: 'Resolve report safely' })).status, 200); assert.equal((await request(url, 'POST', `/api/v1/admin/property-reports/${reportId}/resolve`, 'admin', { version: 0, action: 'resolve' })).status, 400); assert.equal((await request(url, 'GET', '/api/v1/admin/account-reports?status=open&page=1&limit=20', 'seeker')).status, 403); assert.equal((await request(url, 'GET', '/api/v1/admin/account-reports?status=open&page=1&limit=20', 'admin')).status, 200); assert.equal((await request(url, 'POST', `/api/v1/admin/account-reports/${reportId}/resolve`, 'admin', { version: 0, action: 'resolve', reason: 'Resolve account report safely' })).status, 200); assert.equal((await request(url, 'POST', `/api/v1/admin/account-reports/${reportId}/resolve`, 'admin', { version: 0, action: 'resolve', unexpected: true })).status, 400); assert.equal((await request(url, 'GET', '/api/v1/admin/request-issues', 'seeker')).status, 403); assert.equal((await request(url, 'GET', '/api/v1/admin/request-issues', 'admin')).status, 200); assert.equal((await request(url, 'POST', `/api/v1/admin/request-issues/${reportId}/resolve`, 'admin', { expectedVersion: 0, action: 'resolve', reason: 'Resolve request issue safely' })).status, 404); }));
