import type { AccessTokenClaims } from '../auth/crypto.js';
import { favoriteListDataSchema, favoriteListQuerySchema, favoritePropertyParamsSchema, favoritePropertySchema, favoriteRemoveDataSchema, favoriteSaveDataSchema, type FavoriteListData, type FavoriteRemoveData, type FavoriteSaveData } from '@sadat-real-estate/contracts';

export interface FavoritePropertySource { id: string; slug: string; kind: string; name: unknown; transactionType: string; imageUrl?: string; locationName?: unknown; sourceName?: unknown; sourceImageUrl?: string; sourceType?: string; sourceVerified?: boolean; publicCode?: string; viewCount?: number; installmentAvailable?: boolean; featured?: boolean; deliveryStatus?: string; projectId?: string; description?: unknown; area?: unknown; layout?: unknown; price?: unknown; status: string; active: boolean }
export interface FavoriteRecord { seekerId: string; propertyId: string; savedAt: Date }
export interface FavoriteRepository { save(seekerId: string, propertyId: string, now: Date): Promise<{ kind: 'created' | 'existing' | 'unavailable'; favorite?: FavoriteRecord; property?: FavoritePropertySource }>; remove(seekerId: string, propertyId: string): Promise<boolean>; list(seekerId: string, page: number, limit: number): Promise<{ rows: { favorite: FavoriteRecord; property: FavoritePropertySource }[]; total: number }> }
export type FavoriteServiceErrorCode = 'FAVORITE_FORBIDDEN' | 'FAVORITE_PROPERTY_UNAVAILABLE';
export class FavoriteServiceError extends Error { constructor(readonly code: FavoriteServiceErrorCode) { super(code); this.name = 'FavoriteServiceError'; } }
function activeSeeker(claims: AccessTokenClaims): boolean { return claims.role === 'seeker' && claims.status === 'verified'; }
function item(favorite: FavoriteRecord, source: FavoritePropertySource) { const parsed = favoritePropertySchema.safeParse({ id: source.id, slug: source.slug, kind: source.kind, name: source.name, transactionType: source.transactionType, ...(source.imageUrl ? { imageUrl: source.imageUrl } : {}), ...(source.locationName !== undefined ? { locationName: source.locationName } : {}), ...(source.sourceName !== undefined ? { sourceName: source.sourceName } : {}), ...(source.sourceImageUrl ? { sourceImageUrl: source.sourceImageUrl } : {}), ...(source.sourceType ? { sourceType: source.sourceType } : {}), ...(source.sourceVerified !== undefined ? { sourceVerified: source.sourceVerified } : {}), ...(source.publicCode ? { publicCode: source.publicCode } : {}), ...(source.viewCount !== undefined ? { viewCount: source.viewCount } : {}), ...(source.installmentAvailable !== undefined ? { installmentAvailable: source.installmentAvailable } : {}), ...(source.featured !== undefined ? { featured: source.featured } : {}), ...(source.deliveryStatus ? { deliveryStatus: source.deliveryStatus } : {}), ...(source.projectId ? { projectId: source.projectId } : {}), ...(source.description !== undefined ? { description: source.description } : {}), ...(source.area !== undefined ? { area: source.area } : {}), ...(source.layout !== undefined ? { layout: source.layout } : {}), ...(source.price !== undefined ? { price: source.price } : {}), savedAt: favorite.savedAt.toISOString() }); return parsed.success ? parsed.data : null; }
export function createFavoriteService(dependencies: { repository: FavoriteRepository; isActiveSeeker: (userId: string) => Promise<boolean>; now?: () => Date }) {
  const now = dependencies.now ?? (() => new Date());
  async function authorize(claims: AccessTokenClaims): Promise<void> { if (!activeSeeker(claims) || !await dependencies.isActiveSeeker(claims.sub)) throw new FavoriteServiceError('FAVORITE_FORBIDDEN'); }
  return {
    async list(claims: AccessTokenClaims, unparsedQuery: unknown): Promise<FavoriteListData> { await authorize(claims); const query = favoriteListQuerySchema.parse(unparsedQuery); const result = await dependencies.repository.list(claims.sub, query.page, query.limit); const items = result.rows.flatMap(row => { if (row.property.status !== 'published' || !row.property.active) return []; const value = item(row.favorite, row.property); return value ? [value] : []; }); return favoriteListDataSchema.parse({ items, page: query.page, limit: query.limit, total: result.total }); },
    async save(claims: AccessTokenClaims, unparsedPropertyId: unknown): Promise<FavoriteSaveData> { await authorize(claims); const propertyId = favoritePropertyParamsSchema.parse({ propertyId: unparsedPropertyId }).propertyId; const result = await dependencies.repository.save(claims.sub, propertyId, now()); if (result.kind === 'unavailable' || !result.favorite || !result.property || result.property.status !== 'published' || !result.property.active) throw new FavoriteServiceError('FAVORITE_PROPERTY_UNAVAILABLE'); const value = item(result.favorite, result.property); if (!value) throw new FavoriteServiceError('FAVORITE_PROPERTY_UNAVAILABLE'); return favoriteSaveDataSchema.parse({ saved: true, alreadySaved: result.kind === 'existing', item: value }); },
    async remove(claims: AccessTokenClaims, unparsedPropertyId: unknown): Promise<FavoriteRemoveData> { await authorize(claims); const propertyId = favoritePropertyParamsSchema.parse({ propertyId: unparsedPropertyId }).propertyId; return favoriteRemoveDataSchema.parse({ removed: await dependencies.repository.remove(claims.sub, propertyId) }); }
  };
}
