import { Router, type Request, type Response } from 'express';
import { viewingCreateSchema, viewingIdParamsSchema, viewingListQuerySchema, viewingPatchSchema, viewingTransitionSchema } from '@sadat-real-estate/contracts';
import type { AccessTokenClaims, AccessTokenService } from '../auth/crypto.js';
import { ApiContractError, toApiErrorResponse } from '../contracts/error-boundary.js';
import { toSuccessResponse } from '../contracts/response.js';
import { getRequestContext } from '../observability/context.js';
import { ViewingServiceError } from './service.js';
import type { createViewingService } from './service.js';
export const VIEWING_ROUTE_DEFINITIONS = [
  { method: 'GET', path: '/api/v1/seeker/viewings', operationId: 'listSeekerViewings' }, { method: 'POST', path: '/api/v1/seeker/viewings', operationId: 'createSeekerViewing' }, { method: 'PATCH', path: '/api/v1/seeker/viewings/:viewingId', operationId: 'rescheduleSeekerViewing' }, { method: 'POST', path: '/api/v1/seeker/viewings/:viewingId/cancel', operationId: 'cancelSeekerViewing' },
  { method: 'GET', path: '/api/v1/provider/viewings', operationId: 'listProviderViewings' }, { method: 'POST', path: '/api/v1/provider/viewings/:viewingId/transitions', operationId: 'transitionProviderViewing' }, { method: 'GET', path: '/api/v1/admin/viewings', operationId: 'listAdminViewings' }
] as const;
export interface ViewingRouterDependencies { service: ReturnType<typeof createViewingService>; accessTokens: AccessTokenService; }
const requestId = (request: Request) => getRequestContext()?.requestId ?? request.get('x-request-id') ?? 'unknown-request';
function auth(accessTokens: AccessTokenService, role: AccessTokenClaims['role']) { return (request: Request, response: Response, next: () => void): void => { const token = request.get('authorization')?.replace(/^Bearer\s+/i, '').trim(); if (!token) { const body = toApiErrorResponse(new ApiContractError('AUTHENTICATION_REQUIRED', 'errors.authenticationRequired', 401), requestId(request)); response.status(401).json(body.body); return; } try { const claims = accessTokens.verify(token); if (claims.role !== role || claims.status !== 'verified') throw new Error('forbidden'); response.locals.viewingClaims = claims; next(); } catch { const body = toApiErrorResponse(new ApiContractError('FORBIDDEN', 'errors.forbidden', 403), requestId(request)); response.status(403).json(body.body); } }; }
function send(request: Request, response: Response, error: unknown): void { const map: Record<string, { status: number; key: string }> = { VIEWING_FORBIDDEN: { status: 403, key: 'errors.forbidden' }, VIEWING_NOT_FOUND: { status: 404, key: 'errors.viewings.notFound' }, VIEWING_VERSION_CONFLICT: { status: 409, key: 'errors.viewings.versionConflict' }, VIEWING_CONFLICT: { status: 409, key: 'errors.viewings.conflict' }, VIEWING_INVALID_STATE: { status: 409, key: 'errors.viewings.invalidState' } }; const current = error instanceof ViewingServiceError ? map[error.code] : undefined; const body = toApiErrorResponse(current && error instanceof ViewingServiceError ? new ApiContractError(error.code, current.key, current.status) : error, requestId(request)); response.status(body.statusCode).json(body.body); }
export function createViewingRouter(dependencies: ViewingRouterDependencies): Router { const router = Router(); router.use((_req, res, next) => { res.setHeader('Cache-Control', 'no-store'); next(); }); const claims = (res: Response) => res.locals.viewingClaims as AccessTokenClaims;
  router.get('/seeker/viewings', auth(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res), viewingListQuerySchema.parse(req.query)), requestId(req))); } catch (e) { send(req, res, e); } });
  router.post('/seeker/viewings', auth(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(201).json(toSuccessResponse(await dependencies.service.create(claims(res), viewingCreateSchema.parse(req.body ?? {})), requestId(req))); } catch (e) { send(req, res, e); } });
  router.patch('/seeker/viewings/:viewingId', auth(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.patch(claims(res), viewingIdParamsSchema.parse(req.params).viewingId, viewingPatchSchema.parse(req.body ?? {})), requestId(req))); } catch (e) { send(req, res, e); } });
  router.post('/seeker/viewings/:viewingId/cancel', auth(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.cancel(claims(res), viewingIdParamsSchema.parse(req.params).viewingId, (req.body as { expectedVersion?: number } | undefined)?.expectedVersion), requestId(req))); } catch (e) { send(req, res, e); } });
  router.get('/provider/viewings', auth(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res), viewingListQuerySchema.parse(req.query)), requestId(req))); } catch (e) { send(req, res, e); } });
  router.post('/provider/viewings/:viewingId/transitions', auth(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.transition(claims(res), viewingIdParamsSchema.parse(req.params).viewingId, viewingTransitionSchema.parse(req.body ?? {})), requestId(req))); } catch (e) { send(req, res, e); } });
  router.get('/admin/viewings', auth(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res), viewingListQuerySchema.parse(req.query)), requestId(req))); } catch (e) { send(req, res, e); } });
  return router;
}
