import { randomBytes } from 'node:crypto';
import type { AccessTokenClaims } from '../auth/crypto.js';
import { viewingCreateSchema, viewingDataSchema, viewingListDataSchema, viewingListQuerySchema, viewingPatchSchema, viewingTransitionSchema, type PublicPropertyRelatedProperty, type ViewingData, type ViewingListQuery, type ViewingStatus } from '@sadat-real-estate/contracts';
export interface ViewingRecord { id: string; propertyId: string; seekerId: string; providerId?: string; property?: PublicPropertyRelatedProperty; status: ViewingStatus; requestedAt: Date; timezone: string; note?: string; version: number; createdAt: Date; updatedAt: Date; }
export interface ViewingRepository { create(row: ViewingRecord): Promise<ViewingRecord>; list(query: ViewingListQuery, scope: { seekerId?: string; providerId?: string }): Promise<{ items: ViewingRecord[]; total: number }>; get(id: string, scope: { seekerId?: string; providerId?: string }): Promise<ViewingRecord | undefined>; update(input: { id: string; expectedVersion: number; status?: ViewingStatus; requestedAt?: Date; timezone?: string; now: Date }): Promise<{ kind: 'written'; row: ViewingRecord } | { kind: 'not_found' | 'version_conflict' | 'conflict' }>; }
export class ViewingServiceError extends Error { constructor(readonly code: 'VIEWING_FORBIDDEN' | 'VIEWING_NOT_FOUND' | 'VIEWING_VERSION_CONFLICT' | 'VIEWING_CONFLICT' | 'VIEWING_INVALID_STATE') { super(code); this.name = 'ViewingServiceError'; } }
function id(): string { return randomBytes(12).toString('hex'); }
function project(row: ViewingRecord): ViewingData { return viewingDataSchema.parse({ id: row.id, propertyId: row.propertyId, seekerId: row.seekerId, ...(row.providerId ? { providerId: row.providerId } : {}), ...(row.property ? { property: row.property } : {}), status: row.status, requestedAt: row.requestedAt.toISOString(), timezone: row.timezone, ...(row.note ? { note: row.note } : {}), version: row.version, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }); }
function scope(claims: AccessTokenClaims): { seekerId?: string; providerId?: string } { return claims.role === 'seeker' ? { seekerId: claims.sub } : claims.role === 'provider' ? { providerId: claims.sub } : {}; }
export function createViewingService(dependencies: { repository: ViewingRepository; now?: () => Date }) { const now = dependencies.now ?? (() => new Date()); const auth = (claims: AccessTokenClaims) => { if (claims.status !== 'verified' || !['seeker', 'provider', 'admin'].includes(claims.role)) throw new ViewingServiceError('VIEWING_FORBIDDEN'); };
  async function create(claims: AccessTokenClaims, input: unknown): Promise<ViewingData> { auth(claims); if (claims.role !== 'seeker') throw new ViewingServiceError('VIEWING_FORBIDDEN'); const parsed = viewingCreateSchema.parse(input); const requestedAt = new Date(parsed.requestedAt); const stamp = now(); if (!Number.isFinite(requestedAt.getTime()) || requestedAt <= stamp || requestedAt.getTime() > stamp.getTime() + 366 * 24 * 60 * 60 * 1000) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const row = await dependencies.repository.create({ id: id(), propertyId: parsed.propertyId, seekerId: claims.sub, status: 'requested', requestedAt, timezone: parsed.timezone, ...(parsed.note ? { note: parsed.note } : {}), version: 0, createdAt: stamp, updatedAt: stamp }); return project(row); }
  async function list(claims: AccessTokenClaims, input: unknown) { auth(claims); const query = viewingListQuerySchema.parse(input); const result = await dependencies.repository.list(query, scope(claims)); return viewingListDataSchema.parse({ items: result.items.map(project), page: query.page, limit: query.limit, total: result.total }); }
  async function get(claims: AccessTokenClaims, viewingId: string) { auth(claims); const row = await dependencies.repository.get(viewingId, scope(claims)); if (!row) throw new ViewingServiceError('VIEWING_NOT_FOUND'); return project(row); }
  async function patch(claims: AccessTokenClaims, viewingId: string, input: unknown) { auth(claims); if (claims.role !== 'seeker') throw new ViewingServiceError('VIEWING_FORBIDDEN'); const parsed = viewingPatchSchema.parse(input); const current = await dependencies.repository.get(viewingId, { seekerId: claims.sub }); if (!current) throw new ViewingServiceError('VIEWING_NOT_FOUND'); if (!['requested', 'rescheduled'].includes(current.status)) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const requestedAt = new Date(parsed.requestedAt); if (requestedAt <= now()) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const result = await dependencies.repository.update({ id: viewingId, expectedVersion: parsed.expectedVersion, status: 'rescheduled', requestedAt, timezone: parsed.timezone, now: now() }); if (result.kind !== 'written') throw new ViewingServiceError(result.kind === 'version_conflict' ? 'VIEWING_VERSION_CONFLICT' : result.kind === 'conflict' ? 'VIEWING_CONFLICT' : 'VIEWING_NOT_FOUND'); return project(result.row); }
  async function transition(claims: AccessTokenClaims, viewingId: string, input: unknown) { auth(claims); if (!['provider', 'admin'].includes(claims.role)) throw new ViewingServiceError('VIEWING_FORBIDDEN'); const parsed = viewingTransitionSchema.parse(input); const current = await dependencies.repository.get(viewingId, scope(claims)); if (!current) throw new ViewingServiceError('VIEWING_NOT_FOUND'); const allowed: Record<ViewingStatus, string[]> = { requested: ['confirm', 'reschedule', 'cancel'], confirmed: ['reschedule', 'cancel', 'complete'], rescheduled: ['confirm', 'reschedule', 'cancel'], cancelled: [], completed: [] }; if (!allowed[current.status].includes(parsed.action)) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const status: Record<string, ViewingStatus> = { confirm: 'confirmed', reschedule: 'rescheduled', cancel: 'cancelled', complete: 'completed' }; const result = await dependencies.repository.update({ id: viewingId, expectedVersion: parsed.expectedVersion, ...(status[parsed.action] ? { status: status[parsed.action] } : {}), ...(parsed.requestedAt ? { requestedAt: new Date(parsed.requestedAt) } : {}), ...(parsed.timezone ? { timezone: parsed.timezone } : {}), now: now() }); if (result.kind !== 'written') throw new ViewingServiceError(result.kind === 'version_conflict' ? 'VIEWING_VERSION_CONFLICT' : result.kind === 'conflict' ? 'VIEWING_CONFLICT' : 'VIEWING_NOT_FOUND'); return project(result.row); }
  async function cancel(claims: AccessTokenClaims, viewingId: string, expectedVersion: unknown) { auth(claims); if (claims.role !== 'seeker') throw new ViewingServiceError('VIEWING_FORBIDDEN'); const version = Number(expectedVersion); if (!Number.isInteger(version) || version < 0) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const current = await dependencies.repository.get(viewingId, { seekerId: claims.sub }); if (!current) throw new ViewingServiceError('VIEWING_NOT_FOUND'); if (['cancelled', 'completed'].includes(current.status)) throw new ViewingServiceError('VIEWING_INVALID_STATE'); const result = await dependencies.repository.update({ id: viewingId, expectedVersion: version, status: 'cancelled', now: now() }); if (result.kind !== 'written') throw new ViewingServiceError(result.kind === 'version_conflict' ? 'VIEWING_VERSION_CONFLICT' : 'VIEWING_NOT_FOUND'); return project(result.row); }
  return { create, list, get, patch, transition, cancel };
}
export function createInMemoryViewingRepository(seed: ViewingRecord[] = []): ViewingRepository { const rows = new Map(seed.map(row => [row.id, row])); const scoped = (row: ViewingRecord, value: { seekerId?: string; providerId?: string }) => (!value.seekerId || row.seekerId === value.seekerId) && (!value.providerId || row.providerId === value.providerId); return { async create(row) { if ([...rows.values()].some(item => item.seekerId === row.seekerId && item.propertyId === row.propertyId && item.requestedAt.getTime() === row.requestedAt.getTime() && !['cancelled', 'completed'].includes(item.status))) throw new ViewingServiceError('VIEWING_CONFLICT'); rows.set(row.id, row); return row; }, async list(query, value) { const items = [...rows.values()].filter(row => scoped(row, value) && (!query.status || row.status === query.status)).sort((a, b) => b.requestedAt.getTime() - a.requestedAt.getTime()); return { items: items.slice((query.page - 1) * query.limit, query.page * query.limit), total: items.length }; }, async get(id, value) { const row = rows.get(id); return row && scoped(row, value) ? row : undefined; }, async update(input) { const row = rows.get(input.id); if (!row) return { kind: 'not_found' }; if (row.version !== input.expectedVersion) return { kind: 'version_conflict' }; if (input.status && input.status !== 'cancelled' && [...rows.values()].some(item => item.id !== row.id && item.propertyId === row.propertyId && item.requestedAt.getTime() === (input.requestedAt ?? row.requestedAt).getTime() && !['cancelled', 'completed'].includes(item.status))) return { kind: 'conflict' }; const next = { ...row, ...(input.status ? { status: input.status } : {}), ...(input.requestedAt ? { requestedAt: input.requestedAt } : {}), ...(input.timezone ? { timezone: input.timezone } : {}), version: row.version + 1, updatedAt: input.now }; rows.set(row.id, next); return { kind: 'written', row: next }; } }; }
