import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const pack=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),execution=path.join(pack,'03_execution');
const read=n=>JSON.parse(fs.readFileSync(path.join(execution,n),'utf8')),write=(n,v)=>fs.writeFileSync(path.join(execution,n),`${JSON.stringify(v,null,2)}\n`);
const task={id:'backend_145',phase:'F7_post_release_assurance',area:'public listing parity',title:'Public Listing Taxonomy Filter — PUB-02',goal:'Add the allowlisted property-type query required by canonical PUB-02 controls.',kind:'implementation',screens:[],sourceRefs:['09_sources/DESIGN_SOURCE_MANIFEST.json'],notes:['Canonical source key: Odl1Epn2u6lIEuIMmABT7o; PUB-02 node: 6017:12095; owned by frontend_099.'],track:'backend',dependsOn:['backend_144'],atomicTaskFile:'04_tracks/backend/F7_post_release_assurance/backend_145.md',allowedRoots:['packages/contracts/src/search/**','apps/api/src/modules/search/**','apps/api/tests/search/**','apps/web/src/features/public/listing-data.ts','agent_pack/**'],acceptance:['Allowlist propertyTypeId in the public listing query.','Filter only published active properties.','Pass focused verification and pack audit.'],verification:['contracts build','API typecheck','focused search tests','affected lint','node agent_pack/scripts/audit_pack.mjs'],sequence:120};
const catalog=read('TASK_CATALOG.json');if(catalog.some(e=>e.id===task.id))throw new Error('backend_145 exists');catalog.splice(catalog.findIndex(e=>e.track==='frontend'),0,task);catalog.forEach((e,i)=>{e.sequence=i+1});write('TASK_CATALOG.json',catalog);
const now=new Date().toISOString(),state=read('TASK_STATE.json');state.updatedAt=now;state.tasks.frontend_099.status='partial';state.tasks.frontend_099.reason='Paused at PUB-02 for the bounded property-type filter contract required by the canonical controls.';state.tasks[task.id]={status:'in_progress',startedAt:now,completedAt:null,reason:null,evidencePath:null};write('TASK_STATE.json',state);
const deps=read('DEPENDENCIES.json');deps.push({taskId:task.id,dependsOn:task.dependsOn});write('DEPENDENCIES.json',deps);
const map=new Map(read('ATOMIC_TASK_MAP.json').map(e=>[e.taskId,e]));map.set(task.id,{taskId:task.id,track:task.track,phase:task.phase,sequence:task.sequence,atomicTaskFile:task.atomicTaskFile});write('ATOMIC_TASK_MAP.json',catalog.map(e=>({...map.get(e.id),sequence:e.sequence})));
const plans=read('STEP_FILE_PLAN.json');plans.push({taskId:task.id,allowedRoots:task.allowedRoots});write('STEP_FILE_PLAN.json',plans);
const manifest=read('MANIFEST.json');manifest.taskCounts={total:catalog.length,backend:catalog.filter(e=>e.track==='backend').length,frontend:catalog.filter(e=>e.track==='frontend').length};manifest.generatedAt=now;write('MANIFEST.json',manifest);
for(const e of catalog){const f=path.join(pack,e.atomicTaskFile),s=fs.readFileSync(f,'utf8'),u=s.replace(/\| Sequence \| \d+ \/ \d+ \|/u,`| Sequence | ${e.sequence} / ${catalog.length} |`);if(u!==s)fs.writeFileSync(f,u)}
console.log(JSON.stringify({taskId:task.id,total:catalog.length,paused:'frontend_099'},null,2));
