import fs from 'node:fs';
const openapiPath = 'apps/api/openapi/openapi.json';
const openapi = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));
const ref = name => ({ '$ref': `#/components/schemas/${name}` });
const success = schema => ({ allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref(schema) } }] });
const id = name => ({ name, in: 'path', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } });
const providerError = { '$ref': '#/components/responses/ProviderError' };
const validation = { '$ref': '#/components/responses/ValidationError' };
openapi.paths['/api/v1/provider/properties/{propertyId}/media'] = { post: { operationId: 'uploadProviderPropertyMedia', summary: 'Upload owned property image or floor plan media', security: [{ bearerAuth: [] }], parameters: [id('propertyId'), { name: 'x-media-kind', in: 'header', required: true, schema: { enum: ['image', 'floor_plan'] } }, { name: 'x-file-name', in: 'header', required: true, schema: { type: 'string', maxLength: 120 } }], requestBody: { required: true, content: { 'image/jpeg': { schema: { type: 'string', format: 'binary' } }, 'image/png': { schema: { type: 'string', format: 'binary' } }, 'application/pdf': { schema: { type: 'string', format: 'binary' } } } }, responses: { '201': { description: 'Uploaded property media', content: { 'application/json': { schema: success('PropertyMediaData') } } }, '400': validation, '401': providerError, '403': providerError, '404': providerError, '409': providerError, '422': providerError, '503': providerError } } };
openapi.paths['/api/v1/provider/properties/{propertyId}/media/order'] = { patch: { operationId: 'reorderProviderPropertyMedia', summary: 'Order owned ready property media and select a cover', security: [{ bearerAuth: [] }], parameters: [id('propertyId')], requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyMediaOrder') } } }, responses: { '200': { description: 'Reordered property media', content: { 'application/json': { schema: success('PropertyMediaListData') } } }, '400': validation, '401': providerError, '403': providerError, '404': providerError, '409': providerError } } };
openapi.paths['/api/v1/provider/properties/{propertyId}/media/{assetId}'] = { delete: { operationId: 'deleteProviderPropertyMedia', summary: 'Delete owned draft property media', security: [{ bearerAuth: [] }], parameters: [id('propertyId'), id('assetId')], responses: { '200': { description: 'Deleted property media', content: { 'application/json': { schema: success('PropertyMediaData') } } }, '401': providerError, '403': providerError, '404': providerError, '409': providerError } } };
Object.assign(openapi.components.schemas, {
  PropertyMediaData: { type: 'object', additionalProperties: false, required: ['id', 'propertyId', 'kind', 'originalFilename', 'detectedMime', 'byteSize', 'sha256', 'sortOrder', 'isCover', 'processingState', 'active', 'version', 'createdAt', 'updatedAt'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, propertyId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, kind: { enum: ['image', 'floor_plan'] }, originalFilename: { type: 'string', minLength: 1, maxLength: 120 }, detectedMime: { enum: ['application/pdf', 'image/jpeg', 'image/png'] }, byteSize: { type: 'integer', minimum: 1, maximum: 10000000 }, sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' }, sortOrder: { type: 'integer', minimum: 0, maximum: 1000 }, isCover: { type: 'boolean' }, processingState: { enum: ['processing', 'ready', 'failed', 'deleted'] }, failureCode: { type: 'string' }, active: { type: 'boolean' }, version: { type: 'integer', minimum: 0 }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } },
  PropertyMediaListData: { type: 'object', additionalProperties: false, required: ['items'], properties: { items: { type: 'array', maxItems: 50, items: ref('PropertyMediaData') } } },
  PropertyMediaOrder: { type: 'object', additionalProperties: false, required: ['version', 'items', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, items: { type: 'array', minItems: 1, maxItems: 50, items: { type: 'object', additionalProperties: false, required: ['mediaId', 'sortOrder'], properties: { mediaId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, sortOrder: { type: 'integer', minimum: 0, maximum: 1000 }, isCover: { type: 'boolean' } } } }, reason: { type: 'string', minLength: 5, maxLength: 500 } } }
});
fs.writeFileSync(openapiPath, `${JSON.stringify(openapi, null, 2)}\n`);
const postmanPath = 'apps/api/postman/Sadat-Real-Estate.postman_collection.json';
const postman = JSON.parse(fs.readFileSync(postmanPath, 'utf8'));
postman.item = postman.item.filter(item => item?.name !== 'Provider Property Media');
postman.item.push({ name: 'Provider Property Media', item: [
  { name: 'Upload Property Media', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'image/jpeg' }, { key: 'x-media-kind', value: 'image' }, { key: 'x-file-name', value: 'synthetic-property.jpg' }], body: { mode: 'file' }, url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/media', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'media'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Requires an isolated verified provider session and a safe JPEG/PNG/floor-plan fixture.' } },
  { name: 'Reorder Property Media', request: { method: 'PATCH', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 1,\n  "items": [{ "mediaId": "000000000000000000000000", "sortOrder": 0, "isCover": true }],\n  "reason": "Order property media"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/media/order', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'media', 'order'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] } } },
  { name: 'Delete Property Media', request: { method: 'DELETE', header: [], url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/media/:assetId', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'media', ':assetId'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }, { key: 'assetId', value: '000000000000000000000000' }] } } }
] });
fs.writeFileSync(postmanPath, `${JSON.stringify(postman, null, 2)}\n`);
const blueprintPath = 'agent_pack/01_product/API_ENDPOINT_BLUEPRINT.json';
const blueprint = JSON.parse(fs.readFileSync(blueprintPath, 'utf8'));
for (const endpoint of blueprint) if (endpoint.module === 'media' && ['POST /api/v1/provider/properties/:propertyId/media', 'PATCH /api/v1/provider/properties/:propertyId/media/order', 'DELETE /api/v1/provider/properties/:propertyId/media/:assetId'].includes(`${endpoint.method} ${endpoint.path}`)) endpoint.status = 'implemented';
fs.writeFileSync(blueprintPath, `${JSON.stringify(blueprint, null, 2)}\n`);
