import fs from 'node:fs';

const openapiPath = 'apps/api/openapi/openapi.json';
const openapi = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));
const ref = name => ({ '$ref': `#/components/schemas/${name}` });
openapi.paths['/api/v1/provider/projects'] = {
  get: { operationId: 'listProviderProjects', summary: 'List projects owned by the authenticated verified provider', security: [{ bearerAuth: [] }], parameters: [{ name: 'status', in: 'query', schema: { '$ref': '#/components/schemas/ProjectStatus' } }, { name: 'search', in: 'query', schema: { type: 'string', minLength: 1, maxLength: 80 } }, { name: 'sort', in: 'query', schema: { enum: ['updatedAt', 'name', 'slug'], default: 'updatedAt' } }, { name: 'direction', in: 'query', schema: { enum: ['asc', 'desc'], default: 'desc' } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }], responses: { '200': { description: 'Owned project list', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectListData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' } } },
  post: { operationId: 'createProviderProject', summary: 'Create an owned project draft', security: [{ bearerAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: ref('ProjectCreate') } } }, responses: { '201': { description: 'Created project', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' }, '409': { '$ref': '#/components/responses/ProviderError' } } }
};
openapi.paths['/api/v1/admin/projects'] = {
  get: { operationId: 'listAdminProjects', summary: 'List projects for authorized administrators', security: [{ bearerAuth: [] }], parameters: [{ name: 'status', in: 'query', schema: { '$ref': '#/components/schemas/ProjectStatus' } }, { name: 'search', in: 'query', schema: { type: 'string', minLength: 1, maxLength: 80 } }, { name: 'sort', in: 'query', schema: { enum: ['updatedAt', 'name', 'slug'], default: 'updatedAt' } }, { name: 'direction', in: 'query', schema: { enum: ['asc', 'desc'], default: 'desc' } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }], responses: { '200': { description: 'Administrative project list', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectListData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' } } }
};
openapi.paths['/api/v1/provider/projects/{projectId}'] = { patch: { operationId: 'updateProviderProject', summary: 'Update an owned project draft with optimistic concurrency', security: [{ bearerAuth: [] }], parameters: [{ name: 'projectId', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }], requestBody: { required: true, content: { 'application/json': { schema: ref('ProjectPatch') } } }, responses: { '200': { description: 'Updated project', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' }, '404': { '$ref': '#/components/responses/ProviderError' }, '409': { '$ref': '#/components/responses/ProviderError' } } } };
openapi.paths['/api/v1/provider/projects/{projectId}/submit'] = { post: { operationId: 'submitProviderProject', summary: 'Submit an owned project for review', security: [{ bearerAuth: [] }], parameters: [{ name: 'projectId', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }], requestBody: { required: true, content: { 'application/json': { schema: ref('ProjectSubmit') } } }, responses: { '200': { description: 'Submitted project', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' }, '404': { '$ref': '#/components/responses/ProviderError' }, '409': { '$ref': '#/components/responses/ProviderError' } } } };
openapi.paths['/api/v1/admin/projects/{projectId}/review'] = { post: { operationId: 'reviewAdminProject', summary: 'Review and publish a project', security: [{ bearerAuth: [] }], parameters: [{ name: 'projectId', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }], requestBody: { required: true, content: { 'application/json': { schema: ref('ProjectReview') } } }, responses: { '200': { description: 'Reviewed project', content: { 'application/json': { schema: { allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref('ProjectData') } }] } } } }, '400': { '$ref': '#/components/responses/ValidationError' }, '401': { '$ref': '#/components/responses/ProviderError' }, '403': { '$ref': '#/components/responses/ProviderError' }, '404': { '$ref': '#/components/responses/ProviderError' }, '409': { '$ref': '#/components/responses/ProviderError' } } } };
Object.assign(openapi.components.schemas, {
  ProjectStatus: { type: 'string', enum: ['draft', 'pending_review', 'needs_changes', 'approved', 'published', 'rejected', 'hidden', 'archived'] },
  ProjectCreate: { type: 'object', additionalProperties: false, required: ['name', 'slug', 'reason'], properties: { name: ref('LocalizedText'), slug: { type: 'string', minLength: 2, maxLength: 120, pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' }, description: ref('LocalizedText'), locationId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, organizationId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, website: { type: 'string', format: 'uri', maxLength: 2048 }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  ProjectPatch: { type: 'object', additionalProperties: false, required: ['version', 'reason'], minProperties: 3, properties: { version: { type: 'integer', minimum: 0 }, name: ref('LocalizedText'), slug: { type: 'string', minLength: 2, maxLength: 120, pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' }, description: { oneOf: [ref('LocalizedText'), { type: 'null' }] }, locationId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, organizationId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, website: { oneOf: [{ type: 'string', format: 'uri', maxLength: 2048 }, { type: 'null' }] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  ProjectSubmit: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  ProjectReview: { type: 'object', additionalProperties: false, required: ['version', 'action', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, action: { enum: ['needs_changes', 'approve', 'reject', 'publish'] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  ProjectData: { type: 'object', additionalProperties: false, required: ['id', 'providerId', 'name', 'slug', 'status', 'version', 'createdAt', 'updatedAt', 'availableActions'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, providerId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, name: ref('LocalizedText'), slug: { type: 'string' }, description: ref('LocalizedText'), locationId: { type: 'string' }, organizationId: { type: 'string' }, website: { type: 'string', format: 'uri' }, status: ref('ProjectStatus'), submittedAt: { type: 'string', format: 'date-time' }, reviewedBy: { type: 'string', pattern: '^[a-f0-9]{24}$' }, reviewedAt: { type: 'string', format: 'date-time' }, reviewReason: { type: 'string', minLength: 5, maxLength: 500 }, publishedAt: { type: 'string', format: 'date-time' }, version: { type: 'integer', minimum: 0 }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' }, availableActions: { type: 'array', items: { enum: ['update', 'submit', 'needs_changes', 'approve', 'reject', 'publish'] }, uniqueItems: true } } },
  ProjectPublicData: { type: 'object', additionalProperties: false, required: ['id', 'slug', 'name', 'developer', 'linkedPublishedProperties'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, slug: { type: 'string' }, name: ref('LocalizedText'), description: ref('LocalizedText'), website: { type: 'string', format: 'uri' }, developer: { oneOf: [{ type: 'null' }, { type: 'object', additionalProperties: false, required: ['id', 'slug', 'name'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, slug: { type: 'string' }, name: ref('LocalizedText') } }] }, linkedPublishedProperties: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['id', 'slug', 'name', 'active', 'status'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, slug: { type: 'string' }, name: ref('LocalizedText'), active: { type: 'boolean' }, status: { const: 'published' } } } } } },
  ProjectListData: { type: 'object', additionalProperties: false, required: ['items'], properties: { items: { type: 'array', items: ref('ProjectData') } } }
});
fs.writeFileSync(openapiPath, `${JSON.stringify(openapi, null, 2)}\n`);

const postmanPath = 'apps/api/postman/Sadat-Real-Estate.postman_collection.json';
const postman = JSON.parse(fs.readFileSync(postmanPath, 'utf8'));
postman.item = postman.item.filter(item => item?.name !== 'Provider Projects');
postman.item = postman.item.filter(item => item?.name !== 'Admin Projects');
postman.item.push({ name: 'Provider Projects', item: [
  { name: 'List Owned Projects', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/provider/projects?page=1&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'projects'], query: [{ key: 'page', value: '1' }, { key: 'limit', value: '20' }] }, description: 'Requires a transient verified provider bearer token. Results are owned-project projections only.' } },
  { name: 'Create Project Draft', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "name": { "ar": "Synthetic project", "en": "Synthetic project" },\n  "slug": "synthetic-project",\n  "reason": "Create synthetic project draft"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/projects', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'projects'] }, description: 'Requires an isolated verified provider session; ownership is derived from the bearer identity.' } },
  { name: 'Update Project Draft', request: { method: 'PATCH', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 0,\n  "name": { "en": "Updated synthetic project" },\n  "reason": "Update synthetic project draft"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/projects/:projectId', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'projects', ':projectId'], variable: [{ key: 'projectId', value: '000000000000000000000000' }] }, description: 'Requires a verified provider bearer token and current optimistic version.' } }
  , { name: 'Submit Project', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 0,\n  "reason": "Submit synthetic project for review"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/projects/:projectId/submit', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'projects', ':projectId', 'submit'], variable: [{ key: 'projectId', value: '000000000000000000000000' }] }, description: 'Requires a verified provider bearer token and current optimistic version.' } },
  { name: 'Review Project', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 1,\n  "action": "approve",\n  "reason": "Approve synthetic project"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/admin/projects/:projectId/review', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'projects', ':projectId', 'review'], variable: [{ key: 'projectId', value: '000000000000000000000000' }] }, description: 'Requires an isolated verified admin session with admin:projects.review.' } }
] });
postman.item.push({ name: 'Admin Projects', item: [
  { name: 'List All Projects', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/admin/projects?page=1&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'projects'], query: [{ key: 'page', value: '1' }, { key: 'limit', value: '20' }] }, description: 'Requires an isolated verified admin session with admin:projects.view. The response is an administrative projection and never accepts a client provider filter.' } }
] });
fs.writeFileSync(postmanPath, `${JSON.stringify(postman, null, 2)}\n`);
