import fs from 'node:fs';

const openapiPath = 'apps/api/openapi/openapi.json';
const openapi = JSON.parse(fs.readFileSync(openapiPath, 'utf8'));
const ref = name => ({ '$ref': `#/components/schemas/${name}` });
const providerError = { '$ref': '#/components/responses/ProviderError' };
const validationError = { '$ref': '#/components/responses/ValidationError' };
const success = schema => ({ allOf: [ref('SuccessEnvelope'), { type: 'object', properties: { data: ref(schema) } }] });
const idParameter = name => ({ name, in: 'path', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } });

openapi.paths['/api/v1/provider/properties'] = {
  get: {
    operationId: 'listProviderProperties', summary: 'List authenticated provider properties', security: [{ bearerAuth: [] }],
    parameters: [
      { name: 'status', in: 'query', schema: { '$ref': '#/components/schemas/PropertyStatus' } },
      { name: 'search', in: 'query', schema: { type: 'string', minLength: 1, maxLength: 80 } },
      { name: 'sort', in: 'query', schema: { type: 'string', enum: ['updatedAt', 'name', 'slug'], default: 'updatedAt' } },
      { name: 'direction', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'], default: 'desc' } },
      { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } },
      { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }
    ],
    responses: { '200': { description: 'Owned property page', content: { 'application/json': { schema: success('PropertyListData') } } }, '400': validationError, '401': providerError, '403': providerError }
  },
  post: {
    operationId: 'createProviderProperty',
    summary: 'Create an owned property draft',
    security: [{ bearerAuth: [] }],
    requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyCreate') } } },
    responses: { '201': { description: 'Created property draft', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '409': providerError }
  }
};
openapi.paths['/api/v1/provider/properties/{propertyId}'] = {
  get: {
    operationId: 'getProviderProperty',
    summary: 'Get an owned property draft',
    security: [{ bearerAuth: [] }],
    parameters: [idParameter('propertyId')],
    responses: { '200': { description: 'Owned property draft', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError }
  }
};
openapi.paths['/api/v1/provider/properties/{propertyId}/steps/{step}'] = {
  patch: {
    operationId: 'saveProviderPropertyStep',
    summary: 'Save a property wizard step with optimistic concurrency',
    security: [{ bearerAuth: [] }],
    parameters: [idParameter('propertyId'), { name: 'step', in: 'path', required: true, schema: { type: 'string', enum: ['basic', 'location', 'details', 'price-payment', 'features-services', 'contact'] } }],
    requestBody: { required: true, content: { 'application/json': { schema: { oneOf: [ref('PropertyCoreStep'), ref('PropertyLocationStep'), ref('PropertyDetailsStep'), ref('PropertyPricingStep'), ref('PropertyFeaturesServicesStep'), ref('PropertyContactStep')] } } } },
    responses: { '200': { description: 'Updated property draft', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError, '409': providerError, '422': providerError }
  }
};
openapi.paths['/api/v1/provider/properties/{propertyId}/submit'] = {
  post: {
    operationId: 'submitProviderProperty',
    summary: 'Validate and submit an owned property for review',
    security: [{ bearerAuth: [] }],
    parameters: [idParameter('propertyId')],
    requestBody: { required: true, content: { 'application/json': { schema: ref('PropertySubmit') } } },
    responses: { '200': { description: 'Submitted property', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError, '409': providerError, '422': providerError }
  }
};
openapi.paths['/api/v1/admin/properties/{propertyId}/review'] = { post: { operationId: 'reviewAdminProperty', summary: 'Review a submitted property', security: [{ bearerAuth: [] }], parameters: [idParameter('propertyId')], requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyReview') } } }, responses: { '200': { description: 'Reviewed property', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError, '409': providerError } } };
openapi.paths['/api/v1/admin/properties'] = { get: { operationId: 'listAdminProperties', summary: 'List properties for authorized administrators', security: [{ bearerAuth: [] }], parameters: [{ name: 'status', in: 'query', schema: ref('PropertyStatus') }, { name: 'providerId', in: 'query', schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, { name: 'locationId', in: 'query', schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, { name: 'projectId', in: 'query', schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, { name: 'active', in: 'query', schema: { type: 'boolean' } }, { name: 'search', in: 'query', schema: { type: 'string', minLength: 1, maxLength: 80 } }, { name: 'sort', in: 'query', schema: { type: 'string', enum: ['updatedAt', 'name', 'slug', 'status'] } }, { name: 'direction', in: 'query', schema: { type: 'string', enum: ['asc', 'desc'] } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100 } }], responses: { '200': { description: 'Administrative property page', content: { 'application/json': { schema: success('PropertyListData') } } }, '400': validationError, '401': providerError, '403': providerError } } };
openapi.paths['/api/v1/admin/properties/possible-duplicates'] = { get: { operationId: 'listPossiblePropertyDuplicates', summary: 'List deterministic possible duplicate signals', security: [{ bearerAuth: [] }], parameters: [{ name: 'propertyId', in: 'query', required: true, schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }], responses: { '200': { description: 'Explainable duplicate candidates', content: { 'application/json': { schema: success('PropertyDuplicateData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError } } };
openapi.paths['/api/v1/admin/properties/{propertyId}/visibility'] = { post: { operationId: 'changeAdminPropertyVisibility', summary: 'Hide, restore, or archive a property', security: [{ bearerAuth: [] }], parameters: [idParameter('propertyId')], requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyVisibility') } } }, responses: { '200': { description: 'Updated property visibility', content: { 'application/json': { schema: success('PropertyData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError, '409': providerError } } };
openapi.paths['/api/v1/provider/properties/{propertyId}/reports'] = { post: { operationId: 'createProviderPropertyReport', summary: 'Report a property with a deterministic reason', security: [{ bearerAuth: [] }], parameters: [idParameter('propertyId')], requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyReportCreate') } } }, responses: { '201': { description: 'Created property report', content: { 'application/json': { schema: success('PropertyReportData') } } }, '400': validationError, '401': providerError, '403': providerError, '409': providerError } } };
openapi.paths['/api/v1/admin/property-reports'] = { get: { operationId: 'listAdminPropertyReports', summary: 'List property reports with privacy-aware reporter data', security: [{ bearerAuth: [] }], parameters: [{ name: 'status', in: 'query', schema: ref('PropertyReportStatus') }, { name: 'propertyId', in: 'query', schema: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }], responses: { '200': { description: 'Property report page', content: { 'application/json': { schema: success('PropertyReportListData') } } }, '400': validationError, '401': providerError, '403': providerError } } };
openapi.paths['/api/v1/admin/property-reports/{reportId}/resolve'] = { post: { operationId: 'resolveAdminPropertyReport', summary: 'Resolve or dismiss a property report', security: [{ bearerAuth: [] }], parameters: [idParameter('reportId')], requestBody: { required: true, content: { 'application/json': { schema: ref('PropertyReportResolve') } } }, responses: { '200': { description: 'Resolved property report', content: { 'application/json': { schema: success('PropertyReportData') } } }, '400': validationError, '401': providerError, '403': providerError, '404': providerError, '409': providerError } } };

Object.assign(openapi.components.schemas, {
  PropertyStatus: { type: 'string', enum: ['draft', 'pending_review', 'needs_changes', 'approved', 'published', 'rejected', 'hidden', 'archived'] },
  PropertyKind: { type: 'string', enum: ['property', 'unit'] },
  PropertyTransactionType: { type: 'string', enum: ['sale', 'rent'] },
  PropertySource: { type: 'object', additionalProperties: false, required: ['providerId', 'sourceType'], properties: { providerId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, sourceType: { type: 'string', enum: ['individual_broker', 'brokerage_office', 'developer_company'] }, organizationId: { type: 'string', pattern: '^[a-f0-9]{24}$' } } },
  PropertyCreate: { type: 'object', additionalProperties: false, required: ['name', 'slug', 'transactionType', 'source', 'reason'], properties: { kind: { '$ref': '#/components/schemas/PropertyKind', default: 'property' }, name: ref('LocalizedText'), slug: { type: 'string', minLength: 2, maxLength: 120, pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' }, transactionType: ref('PropertyTransactionType'), projectId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, parentPropertyId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, source: ref('PropertySource'), reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyCoreStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, kind: { '$ref': '#/components/schemas/PropertyKind' }, name: ref('LocalizedText'), slug: { type: 'string', minLength: 2, maxLength: 120 }, transactionType: ref('PropertyTransactionType'), projectId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, parentPropertyId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyLocationStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, locationId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, coordinates: { oneOf: [{ type: 'object', additionalProperties: false, required: ['latitude', 'longitude'], properties: { latitude: { type: 'number', minimum: -90, maximum: 90 }, longitude: { type: 'number', minimum: -180, maximum: 180 } } }, { type: 'null' }] }, mapUrl: { oneOf: [{ type: 'string', format: 'uri', maxLength: 2048, pattern: '^https://[^\\s]+$' }, { type: 'null' }] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyDetailsStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, description: ref('LocalizedText'), propertyTypeId: { oneOf: [{ type: 'string', pattern: '^[a-f0-9]{24}$' }, { type: 'null' }] }, area: { oneOf: [{ type: 'object', additionalProperties: false, required: ['value', 'unit'], properties: { value: { type: 'number', exclusiveMinimum: 0, maximum: 1000000 }, unit: { const: 'sqm' } } }, { type: 'null' }] }, layout: { type: 'object', additionalProperties: false, properties: { bedrooms: { type: 'integer', minimum: 0, maximum: 100 }, bathrooms: { type: 'integer', minimum: 0, maximum: 100 }, floor: { type: 'integer', minimum: 0, maximum: 1000 }, totalFloors: { type: 'integer', minimum: 1, maximum: 1000 } } }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyMoney: { type: 'object', additionalProperties: false, required: ['amount', 'currency'], properties: { amount: { type: 'number', exclusiveMinimum: 0, maximum: 1000000000000000 }, currency: { type: 'string', pattern: '^[A-Z]{3}$' } } },
  PropertyPaymentPlan: { type: 'object', additionalProperties: false, required: ['name', 'installments', 'frequency', 'installmentAmount'], properties: { name: ref('LocalizedText'), installments: { type: 'integer', minimum: 1, maximum: 120 }, frequency: { enum: ['monthly', 'quarterly', 'annually'] }, downPayment: ref('PropertyMoney'), installmentAmount: ref('PropertyMoney') } },
  PropertyPricingStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, transactionType: ref('PropertyTransactionType'), price: ref('PropertyMoney'), paymentPlans: { type: 'array', maxItems: 20, items: ref('PropertyPaymentPlan') }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyFeaturesServicesStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, featureIds: { type: 'array', maxItems: 50, uniqueItems: true, items: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, serviceIds: { type: 'array', maxItems: 50, uniqueItems: true, items: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyContact: { type: 'object', additionalProperties: false, properties: { contactName: { type: 'string', minLength: 1, maxLength: 160 }, phone: { type: 'string', pattern: '^\\+[1-9]\\d{7,14}$' }, whatsappNumber: { type: 'string', pattern: '^\\+[1-9]\\d{7,14}$' }, email: { type: 'string', format: 'email', maxLength: 254 }, preferredLocale: { type: 'string', enum: ['ar', 'en', 'zh-CN'] } } },
  PropertyContactStep: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, contact: { oneOf: [ref('PropertyContact'), { type: 'null' }] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertySubmit: { type: 'object', additionalProperties: false, required: ['version', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyReview: { type: 'object', additionalProperties: false, required: ['version', 'action', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, action: { type: 'string', enum: ['needs_changes', 'approve', 'reject', 'publish'] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyVisibility: { type: 'object', additionalProperties: false, required: ['version', 'action', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, action: { type: 'string', enum: ['hide', 'restore', 'archive'] }, reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyListQuery: { type: 'object', additionalProperties: false, properties: { status: ref('PropertyStatus'), search: { type: 'string', minLength: 1, maxLength: 80 }, sort: { type: 'string', enum: ['updatedAt', 'name', 'slug'] }, direction: { type: 'string', enum: ['asc', 'desc'] }, page: { type: 'integer', minimum: 1 }, limit: { type: 'integer', minimum: 1, maximum: 100 } } },
  PropertyAdminListQuery: { type: 'object', additionalProperties: false, properties: { status: ref('PropertyStatus'), providerId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, locationId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, projectId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, active: { type: 'boolean' }, search: { type: 'string', minLength: 1, maxLength: 80 }, sort: { type: 'string', enum: ['updatedAt', 'name', 'slug', 'status'] }, direction: { type: 'string', enum: ['asc', 'desc'] }, page: { type: 'integer', minimum: 1 }, limit: { type: 'integer', minimum: 1, maximum: 100 } } },
  PropertyDuplicateData: { type: 'object', additionalProperties: false, required: ['propertyId', 'items', 'total'], properties: { propertyId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, items: { type: 'array', maxItems: 100, items: { type: 'object', additionalProperties: false, required: ['candidateId', 'signals', 'explanation'], properties: { candidateId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, signals: { type: 'array', minItems: 1, maxItems: 3, items: { type: 'string', enum: ['same_slug', 'same_location_transaction', 'same_localized_name'] } }, explanation: { type: 'string', minLength: 5, maxLength: 500 } } } }, total: { type: 'integer', minimum: 0 } } },
  PropertyReportReason: { type: 'string', enum: ['duplicate', 'fraud', 'inaccurate', 'inappropriate', 'other'] },
  PropertyReportStatus: { type: 'string', enum: ['open', 'in_review', 'resolved', 'dismissed'] },
  PropertyReportAction: { type: 'string', enum: ['resolve', 'dismiss'] },
  PropertyReportCreate: { type: 'object', additionalProperties: false, required: ['reason'], properties: { reason: ref('PropertyReportReason'), details: { type: 'string', minLength: 1, maxLength: 2000 } } },
  PropertyReportResolve: { type: 'object', additionalProperties: false, required: ['version', 'action', 'reason'], properties: { version: { type: 'integer', minimum: 0 }, action: ref('PropertyReportAction'), reason: { type: 'string', minLength: 5, maxLength: 500 } } },
  PropertyReportData: { type: 'object', additionalProperties: false, required: ['id', 'propertyId', 'reason', 'status', 'version', 'createdAt', 'updatedAt'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, propertyId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, reporterId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, reason: ref('PropertyReportReason'), details: { type: 'string' }, status: ref('PropertyReportStatus'), resolutionReason: { type: 'string' }, version: { type: 'integer', minimum: 0 }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } },
  PropertyReportListData: { type: 'object', additionalProperties: false, required: ['items', 'page', 'limit', 'total'], properties: { items: { type: 'array', items: ref('PropertyReportData') }, page: { type: 'integer', minimum: 1 }, limit: { type: 'integer', minimum: 1, maximum: 100 }, total: { type: 'integer', minimum: 0 } } },
  PropertyListData: { type: 'object', additionalProperties: false, required: ['items'], properties: { items: { type: 'array', items: ref('PropertyData') } } },
  PropertyValidationData: { type: 'object', additionalProperties: false, required: ['valid', 'issues'], properties: { valid: { type: 'boolean' }, issues: { type: 'array', maxItems: 20, items: { type: 'object', additionalProperties: false, required: ['path', 'code', 'messageKey'], properties: { path: { type: 'string' }, code: { enum: ['required', 'invalid_state'] }, messageKey: { type: 'string' } } } } } },
  PropertyData: { type: 'object', additionalProperties: false, required: ['id', 'kind', 'name', 'slug', 'transactionType', 'source', 'status', 'active', 'version', 'createdAt', 'updatedAt', 'availableActions'], properties: { id: { type: 'string', pattern: '^[a-f0-9]{24}$' }, kind: { '$ref': '#/components/schemas/PropertyKind' }, name: ref('LocalizedText'), slug: { type: 'string' }, transactionType: ref('PropertyTransactionType'), source: ref('PropertySource'), projectId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, parentPropertyId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, locationId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, coordinates: { type: 'object', required: ['latitude', 'longitude'], properties: { latitude: { type: 'number' }, longitude: { type: 'number' } } }, mapUrl: { type: 'string', format: 'uri', maxLength: 2048, pattern: '^https://[^\\s]+$' }, description: ref('LocalizedText'), propertyTypeId: { type: 'string', pattern: '^[a-f0-9]{24}$' }, area: { '$ref': '#/components/schemas/PropertyDetailsStep/properties/area' }, layout: { '$ref': '#/components/schemas/PropertyDetailsStep/properties/layout' }, price: ref('PropertyMoney'), paymentPlans: { type: 'array', maxItems: 20, items: ref('PropertyPaymentPlan') }, featureIds: { type: 'array', maxItems: 50, uniqueItems: true, items: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, serviceIds: { type: 'array', maxItems: 50, uniqueItems: true, items: { type: 'string', pattern: '^[a-f0-9]{24}$' } }, contact: ref('PropertyContact'), submittedAt: { type: 'string', format: 'date-time' }, reviewedBy: { type: 'string', pattern: '^[a-f0-9]{24}$' }, reviewedAt: { type: 'string', format: 'date-time' }, reviewReason: { type: 'string', minLength: 5, maxLength: 500 }, publishedAt: { type: 'string', format: 'date-time' }, status: ref('PropertyStatus'), active: { type: 'boolean' }, version: { type: 'integer', minimum: 0 }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' }, availableActions: { type: 'array', maxItems: 9, items: { type: 'string', enum: ['update', 'submit', 'needs_changes', 'approve', 'reject', 'publish', 'hide', 'restore', 'archive'] } } } }
});
fs.writeFileSync(openapiPath, `${JSON.stringify(openapi, null, 2)}\n`);

const postmanPath = 'apps/api/postman/Sadat-Real-Estate.postman_collection.json';
const postman = JSON.parse(fs.readFileSync(postmanPath, 'utf8'));
postman.item = postman.item.filter(item => item?.name !== 'Provider Properties');
postman.item.push({ name: 'Provider Properties', item: [
  { name: 'List Provider Properties', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/provider/properties?status=draft&sort=updatedAt&direction=desc&page=1&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties'], query: [{ key: 'status', value: 'draft' }, { key: 'sort', value: 'updatedAt' }, { key: 'direction', value: 'desc' }, { key: 'page', value: '1' }, { key: 'limit', value: '20' }] }, description: 'Returns only authenticated provider-owned properties with bounded filters, deterministic ordering, pagination metadata, and state-derived availableActions.' } },
  { name: 'Create Property Draft', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "name": { "ar": "Synthetic apartment", "en": "Synthetic apartment" },\n  "slug": "synthetic-apartment",\n  "transactionType": "sale",\n  "source": { "providerId": "000000000000000000000000", "sourceType": "individual_broker" },\n  "reason": "Create synthetic property draft"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/properties', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties'] }, description: 'Requires an isolated verified provider session. Provider ownership is checked against the bearer subject.' } },
  { name: 'Get Property Draft', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Returns only the authenticated provider-owned property.' } },
  { name: 'Save Property Step', request: { method: 'PATCH', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 0,\n  "name": { "en": "Updated synthetic apartment" },\n  "reason": "Save basic property data"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/steps/:step', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'steps', ':step'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }, { key: 'step', value: 'basic' }] }, description: 'Requires the current optimistic version; set step to basic, location, details, price-payment, features-services, or contact. Location writes also require an existing active location. Contact data contains no provider identity override or secrets.' } }
  , { name: 'Submit Property', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 0,\n  "reason": "Submit property for review"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/submit', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'submit'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Aggregate validation returns structured field errors; only a valid owned draft can enter pending_review.' } },
  { name: 'Review Property', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 1,\n  "action": "approve",\n  "reason": "Approve reviewed property"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/admin/properties/:propertyId/review', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'properties', ':propertyId', 'review'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Requires an authorized verified admin and a mandatory reason.' } },
  { name: 'Change Property Visibility', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 2,\n  "action": "hide",\n  "reason": "Hide property temporarily"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/admin/properties/:propertyId/visibility', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'properties', ':propertyId', 'visibility'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Hide, restore, or archive operations require an authorized verified admin and a mandatory reason.' } }
] });
postman.item = postman.item.filter(item => item?.name !== 'Admin Properties');
postman.item.push({ name: 'Admin Properties', item: [
  { name: 'List Properties', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/admin/properties?status=pending_review&sort=updatedAt&direction=desc&page=1&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'properties'], query: [{ key: 'status', value: 'pending_review' }, { key: 'sort', value: 'updatedAt' }, { key: 'direction', value: 'desc' }, { key: 'page', value: '1' }, { key: 'limit', value: '20' }] }, description: 'Requires admin:properties.view. Filters are bounded and results are paginated with safe state-derived actions.' } },
  { name: 'Find Possible Duplicates', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/admin/properties/possible-duplicates?propertyId=000000000000000000000000&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'properties', 'possible-duplicates'], query: [{ key: 'propertyId', value: '000000000000000000000000' }, { key: 'limit', value: '20' }] }, description: 'Requires admin:properties.review. Returns deterministic signals and human-readable explanations only; no AI matching or unverifiable score.' } },
  { name: 'List Property Reports', request: { method: 'GET', header: [], url: { raw: '{{apiV1BaseUrl}}/admin/property-reports?status=open&page=1&limit=20', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'property-reports'], query: [{ key: 'status', value: 'open' }, { key: 'page', value: '1' }, { key: 'limit', value: '20' }] }, description: 'Requires admin:property-reports.view. Reporter identity is included only for administrators with manage permission.' } },
  { name: 'Resolve Property Report', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "version": 0,\n  "action": "resolve",\n  "reason": "Verified duplicate and handled"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/admin/property-reports/:reportId/resolve', host: ['{{apiV1BaseUrl}}'], path: ['admin', 'property-reports', ':reportId', 'resolve'], variable: [{ key: 'reportId', value: '000000000000000000000000' }] }, description: 'Requires admin:property-reports.manage and the current optimistic version.' } }
] });
postman.item = postman.item.filter(item => item?.name !== 'Property Reports');
postman.item.push({ name: 'Property Reports', item: [
  { name: 'Create Property Report', request: { method: 'POST', header: [{ key: 'Content-Type', value: 'application/json' }], body: { mode: 'raw', raw: '{\n  "reason": "duplicate",\n  "details": "Same property appears twice"\n}', options: { raw: { language: 'json' } } }, url: { raw: '{{apiV1BaseUrl}}/provider/properties/:propertyId/reports', host: ['{{apiV1BaseUrl}}'], path: ['provider', 'properties', ':propertyId', 'reports'], variable: [{ key: 'propertyId', value: '000000000000000000000000' }] }, description: 'Requires a verified seeker, provider, or administrator token. Replays of the same reason are deduplicated.' } }
] });
fs.writeFileSync(postmanPath, `${JSON.stringify(postman, null, 2)}\n`);

const blueprintPath = 'agent_pack/01_product/API_ENDPOINT_BLUEPRINT.json';
const blueprint = JSON.parse(fs.readFileSync(blueprintPath, 'utf8'));
const implemented = new Set(['GET /api/v1/provider/properties', 'GET /api/v1/provider/properties/:propertyId', 'POST /api/v1/provider/properties', 'PATCH /api/v1/provider/properties/:propertyId/steps/:step', 'POST /api/v1/provider/properties/:propertyId/submit', 'GET /api/v1/admin/properties', 'POST /api/v1/admin/properties/:propertyId/review', 'POST /api/v1/admin/properties/:propertyId/visibility', 'GET /api/v1/admin/property-reports', 'POST /api/v1/admin/property-reports/:reportId/resolve']);
implemented.add('GET /api/v1/admin/properties/possible-duplicates');
for (const endpoint of blueprint) if (implemented.has(`${endpoint.method} ${endpoint.path}`)) endpoint.status = 'implemented';
fs.writeFileSync(blueprintPath, `${JSON.stringify(blueprint, null, 2)}\n`);
