import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';

test('adds a type with a required category, automatic order and a responsive editor', async ({ page }, info) => {
  const ar = !info.project.name.endsWith('-en');
  const category = { id: 'a'.repeat(24), kind: 'category', name: { ar: 'سكني', en: 'Residential' }, slug: 'residential', imageUrl: '/assets/canonical/public/sadat-city-entrance.jpg', order: 2, active: true, version: 0, createdAt: '2026-10-10T08:00:00.000Z', updatedAt: '2026-10-10T08:00:00.000Z', availableActions: ['update', 'delete'] };
  const items = [category, { ...category, id: 'b'.repeat(24), slug: 'commercial', name: { ar: 'تجاري', en: 'Commercial' }, order: 8 }];
  let writes = 0;
  let uploads = 0;
  let previewRelease: (() => void) | undefined;
  let delayPreview = false;
  const previewGate = new Promise<void>(resolve => { previewRelease = resolve; });
  const photo = readFileSync('apps/web/public/assets/canonical/public/sadat-city-entrance.jpg');
  const photoUrl = `/api/v1/public/taxonomy-photos/${'e'.repeat(24)}`;
  const envelope = (data: unknown) => ({ data, meta: { requestId: 'taxonomy-qa', page: 1, limit: 100, total: items.length } });
  await page.route('**/api/v1/auth/refresh', route => route.fulfill({ json: envelope({ accessToken: 'taxonomy.admin.qa', tokenType: 'Bearer', expiresInSeconds: 900, user: { id: 'c'.repeat(24), roleType: 'admin', status: 'verified' } }) }));
  await page.route('**/api/v1/admin/property-categories**', async route => {
    expect(route.request().headers().authorization).toBe('Bearer taxonomy.admin.qa');
    const path = new URL(route.request().url()).pathname;
    if (path.includes('/photos/')) { if (delayPreview) await previewGate; return route.fulfill({ contentType: 'image/jpeg', body: photo }); }
    if (path.endsWith('/photos')) {
      uploads++;
      expect(route.request().headers()['content-type']).toBe('image/jpeg');
      return route.fulfill({ status: 201, json: envelope({ id: 'e'.repeat(24), imageUrl: photoUrl }) });
    }
    if (route.request().method() === 'GET') return route.fulfill({ json: envelope({ items }) });
    writes++;
    const body = route.request().postDataJSON();
    expect(body.categoryId).toBe(category.id);
    expect(body.order).toBe(9);
    expect(body.slug).toBeUndefined();
    expect(body.imageUrl).toBe(route.request().method() === 'PATCH' ? category.imageUrl : photoUrl);
    if (writes === 1) return route.fulfill({ status: 400, json: { error: { code: 'TAXONOMY_INVALID', message: 'Internal technical error' }, meta: { requestId: 'taxonomy-fail' } } });
    const item = { ...category, id: 'd'.repeat(24), kind: 'type', name: body.name, slug: 'custom-property-type', imageUrl: body.imageUrl, order: body.order, categoryId: body.categoryId, version: route.request().method() === 'PATCH' ? body.version + 1 : 0 };
    const existing = items.findIndex(item => item.id === 'd'.repeat(24));
    if (existing < 0) items.push(item); else items[existing] = item;
    return route.fulfill({ status: 201, json: envelope(item) });
  });
  await page.goto(`/admin/property-categories?lang=${ar ? 'ar' : 'en'}`);
  await expect(page.getByRole('table')).toBeVisible();
  await page.getByRole('button', { name: ar ? 'إضافة عنصر' : 'Add item', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.locator('#admin-master-data-kind').selectOption('type');
  await dialog.locator(ar ? '#admin-master-data-name-ar' : '#admin-master-data-name-en').fill('Custom property type');
  await dialog.locator('#admin-master-data-reason').fill('Create new property type');
  await dialog.getByRole('button', { name: ar ? 'حفظ' : 'Save', exact: true }).click();
  await expect(dialog.locator('#admin-master-data-category')).toBeFocused();
  expect(writes).toBe(0);
  await dialog.locator('#admin-master-data-category').selectOption(category.id);
  await dialog.locator('input[type=file]').setInputFiles({ name: 'gate.jpg', mimeType: 'image/jpeg', buffer: photo });
  await expect(dialog.locator('img')).toHaveAttribute('src', /^blob:/);
  expect(uploads).toBe(1);
  expect(await dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.screenshot({ path: info.outputPath('taxonomy-type-editor.png') });
  await dialog.getByRole('button', { name: ar ? 'حفظ' : 'Save', exact: true }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  await expect(dialog).not.toContainText('Internal technical error');
  await expect(dialog.locator(ar ? '#admin-master-data-name-ar' : '#admin-master-data-name-en')).toHaveValue('Custom property type');
  await dialog.getByRole('button', { name: ar ? 'حفظ' : 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(uploads).toBe(1);
  await expect(page.getByRole('status')).toHaveText(ar ? 'تمت إضافة العنصر.' : 'Item added.');
  await expect(page.getByTestId(`admin-master-data-item-${'d'.repeat(24)}`)).toContainText('Custom property type');
  await page.getByTestId(`admin-master-data-item-${'d'.repeat(24)}`).getByRole('button', { name: /Edit:|تعديل:/ }).click();
  await expect(dialog.locator('img')).toHaveAttribute('src', /^blob:/);
  await dialog.getByRole('button', { name: ar ? 'إلغاء' : 'Cancel', exact: true }).click();
  delayPreview = true;
  const previewRequest = page.waitForRequest(request => request.url().includes('/property-categories/photos/'));
  await page.getByTestId(`admin-master-data-item-${'d'.repeat(24)}`).getByRole('button', { name: /Edit:|تعديل:/ }).click();
  await previewRequest;
  await dialog.getByRole('button', { name: ar ? 'استخدام صورة بوابة السادات' : 'Use the Sadat gate image' }).click();
  const previewResponse = page.waitForResponse(response => response.url().includes('/property-categories/photos/'));
  previewRelease!();
  await (await previewResponse).finished();
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  await expect(dialog.locator('img')).toHaveAttribute('src', '/assets/canonical/public/sadat-city-entrance.jpg');
  await dialog.locator('#admin-master-data-reason').fill('Restore default gate image');
  await dialog.getByRole('button', { name: ar ? 'حفظ' : 'Save', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.reload();
  await page.getByTestId(`admin-master-data-item-${'d'.repeat(24)}`).getByRole('button', { name: /Edit:|تعديل:/ }).click();
  await expect(dialog.locator('img')).toHaveAttribute('src', category.imageUrl);
  await dialog.getByRole('button', { name: ar ? 'إلغاء' : 'Cancel', exact: true }).click();
  await page.reload();
  await expect(page.getByTestId(`admin-master-data-item-${'d'.repeat(24)}`)).toContainText('Custom property type');
  const downloaded = await page.request.get('/assets/canonical/public/sadat-city-entrance.jpg');
  expect(downloaded.ok()).toBe(true);
  expect(downloaded.headers()['content-type']).toContain('image/jpeg');
});
