import { expect, test } from '@playwright/test';
import { routePublicHomepageApi, routePublicPropertyListApi } from './public-fixtures';

test('homepage budget range supports rental prices, keyboard handles, and both search endpoints', async ({ page }) => {
  const ar = test.info().project.name.endsWith('-ar');
  const locale = ar ? 'ar' : 'en';
  await routePublicHomepageApi(page);
  await routePublicPropertyListApi(page);
  await page.goto(`/?lang=${locale}`);
  const price = page.locator('.homepage-price-range__trigger');
  await price.click();
  const panel = page.locator('.homepage-price-range__panel');
  await expect(panel).toBeVisible();
  const maxSlider = panel.locator('input[type="range"]').nth(1);
  await expect(maxSlider).toHaveAttribute('max', '10000000');
  await page.locator('.public-homepage__search-tabs button').nth(1).click();
  await expect(panel).toHaveCount(0);
  await price.click();
  await expect(maxSlider).toHaveAttribute('max', '100000');
  const minInput = panel.locator('input[type="number"]').nth(0);
  const maxInput = panel.locator('input[type="number"]').nth(1);
  await minInput.fill('5000');
  await maxInput.fill('15000');
  const minSlider = panel.locator('input[type="range"]').nth(0);
  await minSlider.focus();
  await minSlider.press('ArrowRight');
  await expect(minInput).toHaveValue('5500');
  await maxSlider.focus();
  await maxSlider.press('ArrowLeft');
  await expect(maxInput).toHaveValue('14500');
  await expect(price.locator('span')).toHaveAttribute('dir', 'ltr');
  const bounds = await panel.boundingBox();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  await page.screenshot({ path: test.info().outputPath(`rental-price-range-${locale}.png`), fullPage: false });
  await panel.screenshot({ path: test.info().outputPath(`rental-price-panel-${locale}.png`) });
  await maxInput.fill('1000');
  await expect(panel.getByRole('alert')).toBeVisible();
  await expect(page.locator('.public-homepage__search button[type="submit"]')).toBeDisabled();
  await maxInput.fill('14500');
  await maxInput.press('Escape');
  await expect(panel).toHaveCount(0);
  await expect(price).toBeFocused();
  await price.click();
  await expect(minInput).toHaveValue('5500');
  await panel.getByRole('button', { name: ar ? 'تطبيق' : 'Apply', exact: true }).click();
  await page.locator('.public-homepage__search button[type="submit"]').click();
  await expect(page).toHaveURL(/\/properties\?/u);
  const url = new URL(page.url());
  expect(url.searchParams.get('transactionType')).toBe('rent');
  expect(url.searchParams.get('minPrice')).toBe('5500');
  expect(url.searchParams.get('maxPrice')).toBe('14500');
  expect(url.searchParams.get('lang')).toBe(locale);
  await expect(page.locator('html')).toHaveAttribute('dir', ar ? 'rtl' : 'ltr');
});

test('both budget handles can be dragged without changing the other endpoint', async ({ page }) => {
  const locale = test.info().project.name.endsWith('-ar') ? 'ar' : 'en';
  await routePublicHomepageApi(page);
  await page.goto(`/?lang=${locale}`);
  await page.locator('.public-homepage__search-tabs button').nth(1).click();
  await page.locator('.homepage-price-range__trigger').click();
  const panel = page.locator('.homepage-price-range__panel');
  const sliders = panel.locator('input[type="range"]');
  const values = panel.locator('input[type="number"]');
  await sliders.first().scrollIntoViewIfNeeded();
  const bounds = await sliders.first().boundingBox();
  const start = bounds!.x + 12;
  const end = bounds!.x + bounds!.width - 12;
  const y = bounds!.y + bounds!.height / 2;
  await page.mouse.move(start, y);
  await page.mouse.down();
  await page.mouse.move(start + (end - start) * 0.25, y, { steps: 12 });
  await page.mouse.up();
  await expect(values.first()).toHaveValue('25000');
  await expect(values.nth(1)).toHaveValue('');
  await page.mouse.move(end, y);
  await page.mouse.down();
  await page.mouse.move(start + (end - start) * 0.6, y, { steps: 12 });
  await page.mouse.up();
  await expect(values.nth(1)).toHaveValue('60000');
  await expect(values.first()).toHaveValue('25000');
});

test('no price selection stays unfiltered and sale budgets are cleared when switching to rent', async ({ page }) => {
  const locale = test.info().project.name.endsWith('-ar') ? 'ar' : 'en';
  await routePublicHomepageApi(page);
  await routePublicPropertyListApi(page);
  await page.goto(`/?lang=${locale}`);
  const form = page.locator('.public-homepage__search');
  await page.locator('.homepage-price-range__trigger').click();
  await page.locator('.homepage-price-range__panel input[type="number"]').nth(0).fill('1000000');
  await page.locator('.homepage-price-range__panel input[type="number"]').nth(1).fill('3000000');
  await page.locator('.public-homepage__search-tabs button').nth(1).click();
  await form.locator('button[type="submit"]').click();
  await expect(page).toHaveURL(/\/properties\?/u);
  const params = new URL(page.url()).searchParams;
  expect(params.get('transactionType')).toBe('rent');
  expect(params.has('minPrice')).toBe(false);
  expect(params.has('maxPrice')).toBe(false);
});
