import { Router, type Request, type Response } from 'express';
import { accountReportIdParamsSchema, accountReportListQuerySchema, accountReportResolveSchema, propertyReportCreateSchema, propertyReportIdParamsSchema, propertyReportListQuerySchema, propertyReportPropertyParamsSchema, propertyReportResolveSchema, requestIssueResolveSchema, requestIdSchema, requestListQuerySchema } from '@sadat-real-estate/contracts';
import type { AccessTokenClaims, AccessTokenService } from '../auth/crypto.js';
import { ApiContractError, toApiErrorResponse } from '../contracts/error-boundary.js';
import { toSuccessResponse } from '../contracts/response.js';
import { getRequestContext } from '../observability/context.js';
import { createAdminRbacAuthMiddleware } from '../rbac/auth.js';
import { ModerationServiceError, type ModerationContext, type ModerationService } from './service.js';
import { RequestIssueServiceError, type RequestIssueService } from './request-issues.js';

export const MODERATION_ROUTE_DEFINITIONS = [
  { method: 'POST', path: '/api/v1/provider/properties/:propertyId/reports', operationId: 'createProviderPropertyReport' },
  { method: 'GET', path: '/api/v1/admin/property-reports', operationId: 'listAdminPropertyReports' },
  { method: 'POST', path: '/api/v1/admin/property-reports/:reportId/resolve', operationId: 'resolveAdminPropertyReport' },
  { method: 'GET', path: '/api/v1/admin/account-reports', operationId: 'listAdminAccountReports' },
  { method: 'POST', path: '/api/v1/admin/account-reports/:reportId/resolve', operationId: 'resolveAdminAccountReport' },
  { method: 'GET', path: '/api/v1/admin/request-issues', operationId: 'listAdminRequestIssues' },
  { method: 'POST', path: '/api/v1/admin/request-issues/:issueId/resolve', operationId: 'resolveAdminRequestIssue' }
] as const;
export interface ModerationRouterDependencies { service: ModerationService; accessTokens: AccessTokenService; requestIssues: RequestIssueService; }
const errors: Record<string, { statusCode: number; messageKey: string }> = { REPORT_FORBIDDEN: { statusCode: 403, messageKey: 'errors.propertyReports.forbidden' }, REPORT_NOT_FOUND: { statusCode: 404, messageKey: 'errors.propertyReports.notFound' }, REPORT_DUPLICATE: { statusCode: 409, messageKey: 'errors.propertyReports.duplicate' }, REPORT_VERSION_CONFLICT: { statusCode: 409, messageKey: 'errors.propertyReports.versionConflict' }, REPORT_INVALID_STATE: { statusCode: 409, messageKey: 'errors.propertyReports.invalidState' } };
const accountErrors: Record<string, { statusCode: number; messageKey: string }> = { REPORT_FORBIDDEN: { statusCode: 403, messageKey: 'errors.accountReports.forbidden' }, REPORT_NOT_FOUND: { statusCode: 404, messageKey: 'errors.accountReports.notFound' }, REPORT_VERSION_CONFLICT: { statusCode: 409, messageKey: 'errors.accountReports.versionConflict' }, REPORT_INVALID_STATE: { statusCode: 409, messageKey: 'errors.accountReports.invalidState' } };
const requestIssueErrors: Record<string, { statusCode: number; messageKey: string }> = { FORBIDDEN: { statusCode: 403, messageKey: 'errors.requestIssues.forbidden' }, NOT_FOUND: { statusCode: 404, messageKey: 'errors.requestIssues.notFound' }, VERSION_CONFLICT: { statusCode: 409, messageKey: 'errors.requestIssues.versionConflict' }, INVALID_STATE: { statusCode: 409, messageKey: 'errors.requestIssues.invalidState' } };
function context(request: Request): ModerationContext { const current = getRequestContext(); return { requestId: current?.requestId ?? request.get('x-request-id') ?? 'unknown-request', traceId: current?.traceId ?? 'f'.repeat(32) }; }
function claims(response: Response): AccessTokenClaims { return response.locals.reportClaims as AccessTokenClaims; }
function adminId(response: Response): string { return (response.locals.adminRbacClaims as AccessTokenClaims).sub; }
function sendError(request: Request, response: Response, error: unknown): void { const reportError = error instanceof ModerationServiceError ? error : undefined; const definition = reportError ? errors[reportError.code] : undefined; const mapped = toApiErrorResponse(definition ? new ApiContractError(reportError!.code, definition.messageKey, definition.statusCode) : error, context(request).requestId); response.status(mapped.statusCode).json(mapped.body); }
function sendAccountError(request: Request, response: Response, error: unknown): void { const reportError = error instanceof ModerationServiceError ? error : undefined; const definition = reportError ? accountErrors[reportError.code] : undefined; const mapped = toApiErrorResponse(definition ? new ApiContractError(reportError!.code, definition.messageKey, definition.statusCode) : error, context(request).requestId); response.status(mapped.statusCode).json(mapped.body); }
function sendRequestIssueError(request: Request, response: Response, error: unknown): void { const issueError = error instanceof RequestIssueServiceError ? error : undefined; const definition = issueError ? requestIssueErrors[issueError.code] : undefined; const mapped = toApiErrorResponse(definition ? new ApiContractError(issueError!.code, definition.messageKey, definition.statusCode) : error, context(request).requestId); response.status(mapped.statusCode).json(mapped.body); }
function reportAuth(accessTokens: AccessTokenService) { return (request: Request, response: Response, next: () => void): void => { const value = request.get('authorization')?.replace(/^Bearer\s+/i, '').trim(); if (!value) { sendError(request, response, new ApiContractError('AUTHENTICATION_REQUIRED', 'errors.authenticationRequired', 401)); return; } try { const current = accessTokens.verify(value); if (current.status !== 'verified' || !['seeker', 'provider', 'admin'].includes(current.role)) throw new Error('forbidden'); response.locals.reportClaims = current; next(); } catch { sendError(request, response, new ApiContractError('AUTHENTICATION_REQUIRED', 'errors.authenticationRequired', 401)); } }; }
export function createModerationRouter(dependencies: ModerationRouterDependencies): Router {
  const router = Router(); router.use((_request, response, next) => { response.setHeader('Cache-Control', 'no-store'); next(); });
  router.use('/provider/properties/:propertyId/reports', reportAuth(dependencies.accessTokens));
  router.use('/admin/property-reports', createAdminRbacAuthMiddleware(dependencies.accessTokens));
  router.use('/admin/account-reports', createAdminRbacAuthMiddleware(dependencies.accessTokens));
  router.use('/admin/request-issues', createAdminRbacAuthMiddleware(dependencies.accessTokens));
  router.post('/provider/properties/:propertyId/reports', async (request, response) => { try { const { propertyId } = propertyReportPropertyParamsSchema.parse(request.params); const current = context(request); response.status(201).json(toSuccessResponse(await dependencies.service.create(claims(response), propertyId, propertyReportCreateSchema.parse(request.body ?? {}), current), current.requestId)); } catch (error) { sendError(request, response, error); } });
  router.get('/admin/property-reports', async (request, response) => { try { const current = context(request); response.status(200).json(toSuccessResponse(await dependencies.service.list(adminId(response), propertyReportListQuerySchema.parse(request.query)), current.requestId)); } catch (error) { sendError(request, response, error); } });
  router.post('/admin/property-reports/:reportId/resolve', async (request, response) => { try { const { reportId } = propertyReportIdParamsSchema.parse(request.params); const current = context(request); response.status(200).json(toSuccessResponse(await dependencies.service.resolve(adminId(response), reportId, propertyReportResolveSchema.parse(request.body ?? {}), current), current.requestId)); } catch (error) { sendError(request, response, error); } });
  router.get('/admin/account-reports', async (request, response) => { try { const current = context(request); response.status(200).json(toSuccessResponse(await dependencies.service.listAccountReports(adminId(response), accountReportListQuerySchema.parse(request.query)), current.requestId)); } catch (error) { sendAccountError(request, response, error); } });
  router.post('/admin/account-reports/:reportId/resolve', async (request, response) => { try { const { reportId } = accountReportIdParamsSchema.parse(request.params); const current = context(request); response.status(200).json(toSuccessResponse(await dependencies.service.resolveAccountReport(adminId(response), reportId, accountReportResolveSchema.parse(request.body ?? {}), current), current.requestId)); } catch (error) { sendAccountError(request, response, error); } });
  router.get('/admin/request-issues', async (request, response) => { try { const query = requestListQuerySchema.parse(request.query); response.status(200).json(toSuccessResponse(await dependencies.requestIssues.list(response.locals.adminRbacClaims as AccessTokenClaims, query.page, query.limit), context(request).requestId)); } catch (error) { sendRequestIssueError(request, response, error); } });
  router.post('/admin/request-issues/:issueId/resolve', async (request, response) => { try { const issueId = requestIdSchema.parse(request.params.issueId); response.status(200).json(toSuccessResponse(await dependencies.requestIssues.resolve(response.locals.adminRbacClaims as AccessTokenClaims, issueId, requestIssueResolveSchema.parse(request.body ?? {})), context(request).requestId)); } catch (error) { sendRequestIssueError(request, response, error); } });
  return router;
}
