import { accountObjectIdSchema, accountReportActionSchema, accountReportDataSchema, accountReportListDataSchema, accountReportListQuerySchema, accountReportResolveSchema, propertyObjectIdSchema, propertyReportCreateSchema, propertyReportDataSchema, propertyReportListDataSchema, propertyReportListQuerySchema, propertyReportResolveSchema, type AccountReportData, type AccountReportListData, type PropertyReportData, type PropertyReportListData } from '@sadat-real-estate/contracts';
import type { AccessTokenClaims } from '../auth/crypto.js';
import type { AccountReportWriteResult, ModerationRepository, ReportWriteResult, StoredAccountReport, StoredPropertyReport } from './repository.js';

export type ModerationServiceErrorCode = 'REPORT_FORBIDDEN' | 'REPORT_NOT_FOUND' | 'REPORT_DUPLICATE' | 'REPORT_VERSION_CONFLICT' | 'REPORT_INVALID_STATE';
export class ModerationServiceError extends Error { readonly code: ModerationServiceErrorCode; constructor(code: ModerationServiceErrorCode) { super(code); this.name = 'ModerationServiceError'; this.code = code; } }
export interface ModerationAuthorization { authorize(adminId: string, permission: 'admin:property-reports.view' | 'admin:property-reports.manage' | 'admin:account-reports.view' | 'admin:account-reports.manage'): Promise<boolean>; }
export interface ModerationContext { requestId: string; traceId: string; }
export interface ModerationService { create(claims: AccessTokenClaims, propertyId: string, input: unknown, context: ModerationContext): Promise<PropertyReportData>; list(adminId: string, input: unknown): Promise<PropertyReportListData>; resolve(adminId: string, reportId: string, input: unknown, context: ModerationContext): Promise<PropertyReportData>; listAccountReports(adminId: string, input: unknown): Promise<AccountReportListData>; resolveAccountReport(adminId: string, reportId: string, input: unknown, context: ModerationContext): Promise<AccountReportData>; }
function data(report: StoredPropertyReport, includeReporter: boolean): PropertyReportData { return propertyReportDataSchema.parse({ id: report.id, propertyId: report.propertyId, ...(includeReporter && report.reporterId ? { reporterId: report.reporterId } : {}), reason: report.reason, ...(report.details ? { details: report.details } : {}), status: report.status, ...(report.resolutionReason ? { resolutionReason: report.resolutionReason } : {}), version: report.version, createdAt: report.createdAt.toISOString(), updatedAt: report.updatedAt.toISOString() }); }
function accountData(report: StoredAccountReport, includeReporter: boolean): AccountReportData { return accountReportDataSchema.parse({ id: report.id, accountId: report.accountId, ...(report.accountRoleType ? { accountRoleType: report.accountRoleType } : {}), ...(includeReporter && report.reporterId ? { reporterId: report.reporterId } : {}), reason: report.reason, ...(report.details ? { details: report.details } : {}), status: report.status, ...(report.resolutionReason ? { resolutionReason: report.resolutionReason } : {}), relatedReports: report.relatedReports, version: report.version, createdAt: report.createdAt.toISOString(), updatedAt: report.updatedAt.toISOString() }); }
function write(result: ReportWriteResult): StoredPropertyReport { if (result.kind === 'duplicate') throw new ModerationServiceError('REPORT_DUPLICATE'); if (result.kind === 'not_found') throw new ModerationServiceError('REPORT_NOT_FOUND'); if (result.kind === 'version_conflict') throw new ModerationServiceError('REPORT_VERSION_CONFLICT'); if (result.kind === 'invalid_state') throw new ModerationServiceError('REPORT_INVALID_STATE'); return result.report; }
function writeAccount(result: AccountReportWriteResult): StoredAccountReport { if (result.kind === 'not_found') throw new ModerationServiceError('REPORT_NOT_FOUND'); if (result.kind === 'version_conflict') throw new ModerationServiceError('REPORT_VERSION_CONFLICT'); if (result.kind === 'invalid_state') throw new ModerationServiceError('REPORT_INVALID_STATE'); return result.report; }
function actorType(claims: AccessTokenClaims): 'seeker' | 'provider' | 'admin' { if (claims.role === 'provider') return 'provider'; if (claims.role === 'admin') return 'admin'; return 'seeker'; }

export function createModerationService(dependencies: { repository: ModerationRepository; authorization?: ModerationAuthorization; now?: () => Date }): ModerationService {
  const now = dependencies.now ?? (() => new Date());
  async function permission(adminId: string, value: 'admin:property-reports.view' | 'admin:property-reports.manage' | 'admin:account-reports.view' | 'admin:account-reports.manage'): Promise<void> { if (!dependencies.authorization || !await dependencies.authorization.authorize(adminId, value)) throw new ModerationServiceError('REPORT_FORBIDDEN'); }
  return {
    async create(claims, propertyId, unparsedInput, context) { if (claims.status !== 'verified' || !['seeker', 'provider', 'admin'].includes(claims.role)) throw new ModerationServiceError('REPORT_FORBIDDEN'); propertyObjectIdSchema.parse(propertyId); const input = propertyReportCreateSchema.parse(unparsedInput); return data(write(await dependencies.repository.create({ propertyId, reporterId: claims.sub, report: input, actorType: actorType(claims), requestId: context.requestId, traceId: context.traceId, now: now() })), false); },
    async list(adminId, unparsedInput) { await permission(adminId, 'admin:property-reports.view'); const query = propertyReportListQuerySchema.parse(unparsedInput); const result = await dependencies.repository.list(query); const includeReporter = Boolean(dependencies.authorization && await dependencies.authorization.authorize(adminId, 'admin:property-reports.manage')); return propertyReportListDataSchema.parse({ items: result.items.map(report => data(report, includeReporter)), page: query.page, limit: query.limit, total: result.total }); },
    async resolve(adminId, reportId, unparsedInput, context) { await permission(adminId, 'admin:property-reports.manage'); propertyReportObjectId(reportId); const input = propertyReportResolveSchema.parse(unparsedInput); return data(write(await dependencies.repository.resolve({ reportId, expectedVersion: input.version, action: input.action, adminId, reason: input.reason, requestId: context.requestId, traceId: context.traceId, now: now() })), true); },
    async listAccountReports(adminId, unparsedInput) { await permission(adminId, 'admin:account-reports.view'); const query = accountReportListQuerySchema.parse(unparsedInput); const result = await dependencies.repository.listAccountReports(query); const includeReporter = Boolean(dependencies.authorization && await dependencies.authorization.authorize(adminId, 'admin:account-reports.manage')); return accountReportListDataSchema.parse({ items: result.items.map(report => accountData(report, includeReporter)), page: query.page, limit: query.limit, total: result.total }); },
    async resolveAccountReport(adminId, reportId, unparsedInput, context) { await permission(adminId, 'admin:account-reports.manage'); accountObjectIdSchema.parse(reportId); const input = accountReportResolveSchema.parse(unparsedInput); return accountData(writeAccount(await dependencies.repository.resolveAccountReport({ reportId, expectedVersion: input.version, action: accountReportActionSchema.parse(input.action), adminId, reason: input.reason, requestId: context.requestId, traceId: context.traceId, now: now() })), true); }
  };
}
function propertyReportObjectId(value: string): void { propertyObjectIdSchema.parse(value); }
