import { Types, type Connection } from 'mongoose';
import { organizationSlugSchema, publicOrganizationCardSchema, publicOrganizationDirectoryQuerySchema, publicOrganizationListDataSchema, publicOrganizationProfileSchema, type PublicOrganizationDirectoryQuery, type PublicOrganizationListData, type PublicOrganizationProfile } from '@sadat-real-estate/contracts';

export interface PublicOrganizationProjectSource { id: string; slug: string; name: unknown; imageUrl?: string; description?: unknown; website?: string; locationName?: unknown; statusLabel?: unknown; projectType?: unknown; unitCount?: number; areaLabel?: unknown; priceLabel?: unknown; deliveryLabel?: unknown; status: string }
export interface PublicOrganizationPropertySource { id: string; slug: string; kind: string; name: unknown; imageUrl?: string; transactionType: string; projectId?: string; status: string; active: boolean }
export interface PublicOrganizationSource { id: string; providerId: string; kind: string; slug: string; name: unknown; imageUrl?: string; logoUrl?: string; locations?: unknown[]; description?: unknown; activeAreas?: unknown[]; projectTypes?: unknown[]; propertyTypes?: unknown[]; paymentPlans?: unknown[]; totalUnits?: number; availableUnits?: number; soldUnits?: number; reservedUnits?: number; activeAreaCount?: number; lastUpdated?: string; contactPhone?: string; whatsappUrl?: string; contactAddress?: string; status: string; providerStatus: string; projects: PublicOrganizationProjectSource[]; properties: PublicOrganizationPropertySource[] }
export interface PublicOrganizationRepository { list(query: PublicOrganizationDirectoryQuery): Promise<{ items: PublicOrganizationSource[]; total: number }>; findBySlug(slug: string): Promise<PublicOrganizationSource | null> }

function project(source: PublicOrganizationProjectSource) { return { id: source.id, slug: source.slug, name: source.name, ...(source.imageUrl ? { imageUrl: source.imageUrl } : {}), ...(source.description !== undefined ? { description: source.description } : {}), ...(source.website ? { website: source.website } : {}), ...(source.locationName !== undefined ? { locationName: source.locationName } : {}), ...(source.statusLabel !== undefined ? { statusLabel: source.statusLabel } : {}), ...(source.projectType !== undefined ? { projectType: source.projectType } : {}), ...(source.unitCount !== undefined ? { unitCount: source.unitCount } : {}), ...(source.areaLabel !== undefined ? { areaLabel: source.areaLabel } : {}), ...(source.priceLabel !== undefined ? { priceLabel: source.priceLabel } : {}), ...(source.deliveryLabel !== undefined ? { deliveryLabel: source.deliveryLabel } : {}) }; }
function property(source: PublicOrganizationPropertySource) { return { id: source.id, slug: source.slug, kind: source.kind, name: source.name, ...(source.imageUrl ? { imageUrl: source.imageUrl } : {}), transactionType: source.transactionType, ...(source.projectId ? { projectId: source.projectId } : {}) }; }
function publicProfile(source: PublicOrganizationSource): PublicOrganizationProfile | null {
  if (source.status !== 'approved' || source.providerStatus !== 'approved') return null;
  const projects = source.projects.filter(value => value.status === 'published').map(project).sort((a,b) => a.slug.localeCompare(b.slug, 'en') || a.id.localeCompare(b.id, 'en'));
  const properties = source.properties.filter(value => value.status === 'published' && value.active).map(property).sort((a,b) => a.slug.localeCompare(b.slug, 'en') || a.id.localeCompare(b.id, 'en'));
  const parsed = publicOrganizationProfileSchema.safeParse({ id: source.id, kind: source.kind, slug: source.slug, name: source.name, ...(source.imageUrl ? { imageUrl: source.imageUrl } : {}), ...(source.logoUrl ? { logoUrl: source.logoUrl } : {}), ...(Array.isArray(source.locations) ? { locations: source.locations } : {}), ...(source.description !== undefined ? { description: source.description } : {}), ...(Array.isArray(source.activeAreas) ? { activeAreas: source.activeAreas } : {}), ...(Array.isArray(source.projectTypes) ? { projectTypes: source.projectTypes } : {}), ...(Array.isArray(source.propertyTypes) ? { propertyTypes: source.propertyTypes } : {}), ...(Array.isArray(source.paymentPlans) ? { paymentPlans: source.paymentPlans } : {}), ...(source.contactPhone ? { contactPhone: source.contactPhone } : {}), ...(source.whatsappUrl ? { whatsappUrl: source.whatsappUrl } : {}), ...(source.contactAddress ? { contactAddress: source.contactAddress } : {}), verified: true, projectCount: projects.length, propertyCount: properties.length, projects, properties, stats:{publishedProjects:projects.length,availableProperties:properties.length,saleProperties:properties.filter((value)=>value.transactionType==='sale').length,rentalProperties:properties.filter((value)=>value.transactionType==='rent').length, ...(source.totalUnits !== undefined ? { totalUnits: source.totalUnits } : {}), ...(source.availableUnits !== undefined ? { availableUnits: source.availableUnits } : {}), ...(source.soldUnits !== undefined ? { soldUnits: source.soldUnits } : {}), ...(source.reservedUnits !== undefined ? { reservedUnits: source.reservedUnits } : {}), ...(source.activeAreaCount !== undefined ? { activeAreas: source.activeAreaCount } : {}), ...(source.lastUpdated ? { lastUpdated: source.lastUpdated } : {})} });
  return parsed.success ? parsed.data : null;
}

export function createPublicOrganizationService(dependencies: { repository: PublicOrganizationRepository }) {
  return {
    async list(unparsedQuery: unknown): Promise<PublicOrganizationListData> {
      const query = publicOrganizationDirectoryQuerySchema.parse(unparsedQuery);
      const result = await dependencies.repository.list(query);
      const items = result.items.flatMap(source => { const profile = publicProfile(source); return profile ? [publicOrganizationCardSchema.parse({ id: profile.id, kind: profile.kind, slug: profile.slug, name: profile.name, ...(profile.imageUrl ? { imageUrl: profile.imageUrl } : {}), ...(profile.logoUrl ? { logoUrl: profile.logoUrl } : {}), ...(profile.locations ? { locations: profile.locations } : {}), ...(profile.description !== undefined ? { description: profile.description } : {}), verified: profile.verified, projectCount: profile.projectCount, propertyCount: profile.propertyCount })] : []; });
      const ordered = [...items].sort((left, right) => { const leftKey = query.sort === 'name' ? (left.name.en ?? left.name.ar ?? left.name['zh-CN'] ?? '') : left.slug; const rightKey = query.sort === 'name' ? (right.name.en ?? right.name.ar ?? right.name['zh-CN'] ?? '') : right.slug; const comparison = leftKey.localeCompare(rightKey, 'en') || left.slug.localeCompare(right.slug, 'en') || left.id.localeCompare(right.id, 'en'); return query.direction === 'asc' ? comparison : -comparison; });
      return publicOrganizationListDataSchema.parse({ items: ordered, page: query.page, limit: query.limit, total: result.total });
    },
    async get(unparsedSlug: unknown): Promise<PublicOrganizationProfile | null> {
      const slug = organizationSlugSchema.parse(unparsedSlug);
      const source = await dependencies.repository.findBySlug(slug);
      return source ? publicProfile(source) : null;
    }
  };
}

type Row = Record<string, unknown>;
function id(value: unknown): string | undefined { if (typeof value === 'string') return value; if (value && typeof value === 'object' && typeof (value as { toHexString?: () => string }).toHexString === 'function') return (value as { toHexString: () => string }).toHexString(); return undefined; }
function organization(row: Row, projects: PublicOrganizationProjectSource[], properties: PublicOrganizationPropertySource[], providerStatus: string): PublicOrganizationSource | null { const rowId = id(row._id); const providerId = id(row.providerId); if (!rowId || !providerId || typeof row.kind !== 'string' || typeof row.slug !== 'string' || row.name === undefined || typeof row.status !== 'string') return null; return { id: rowId, providerId, kind: row.kind, slug: row.slug, name: row.name, ...(typeof row.imageUrl === 'string' ? { imageUrl: row.imageUrl } : {}), ...(typeof row.logoUrl === 'string' ? { logoUrl: row.logoUrl } : {}), ...(Array.isArray(row.locations) ? { locations: row.locations } : {}), ...(row.description !== undefined ? { description: row.description } : {}), ...(Array.isArray(row.activeAreas) ? { activeAreas: row.activeAreas } : {}), ...(Array.isArray(row.projectTypes) ? { projectTypes: row.projectTypes } : {}), ...(Array.isArray(row.propertyTypes) ? { propertyTypes: row.propertyTypes } : {}), ...(Array.isArray(row.paymentPlans) ? { paymentPlans: row.paymentPlans } : {}), ...(typeof row.totalUnits === 'number' ? { totalUnits: row.totalUnits } : {}), ...(typeof row.availableUnits === 'number' ? { availableUnits: row.availableUnits } : {}), ...(typeof row.soldUnits === 'number' ? { soldUnits: row.soldUnits } : {}), ...(typeof row.reservedUnits === 'number' ? { reservedUnits: row.reservedUnits } : {}), ...(typeof row.activeAreaCount === 'number' ? { activeAreaCount: row.activeAreaCount } : {}), ...(typeof row.lastUpdated === 'string' ? { lastUpdated: row.lastUpdated } : {}), ...(typeof row.contactPhone === 'string' ? { contactPhone: row.contactPhone } : {}), ...(typeof row.whatsappUrl === 'string' ? { whatsappUrl: row.whatsappUrl } : {}), ...(typeof row.contactAddress === 'string' ? { contactAddress: row.contactAddress } : {}), status: row.status, providerStatus, projects, properties }; }
function mapProject(row: Row): PublicOrganizationProjectSource | null { const rowId = id(row._id); return rowId && typeof row.slug === 'string' && row.name !== undefined && typeof row.status === 'string' ? { id: rowId, slug: row.slug, name: row.name, ...(typeof row.imageUrl === 'string' ? { imageUrl: row.imageUrl } : {}), ...(row.description !== undefined ? { description: row.description } : {}), ...(typeof row.website === 'string' ? { website: row.website } : {}), ...(row.locationName !== undefined ? { locationName: row.locationName } : {}), ...(row.statusLabel !== undefined ? { statusLabel: row.statusLabel } : {}), ...(row.projectType !== undefined ? { projectType: row.projectType } : {}), ...(typeof row.unitCount === 'number' ? { unitCount: row.unitCount } : {}), ...(row.areaLabel !== undefined ? { areaLabel: row.areaLabel } : {}), ...(row.priceLabel !== undefined ? { priceLabel: row.priceLabel } : {}), ...(row.deliveryLabel !== undefined ? { deliveryLabel: row.deliveryLabel } : {}), status: row.status } : null; }
function mapProperty(row: Row): PublicOrganizationPropertySource | null { const rowId = id(row._id); const projectId = id(row.projectId); return rowId && typeof row.slug === 'string' && typeof row.kind === 'string' && row.name !== undefined && typeof row.transactionType === 'string' && typeof row.status === 'string' && typeof row.active === 'boolean' ? { id: rowId, slug: row.slug, kind: row.kind, name: row.name, ...(typeof row.imageUrl === 'string' ? { imageUrl: row.imageUrl } : {}), transactionType: row.transactionType, ...(projectId ? { projectId } : {}), status: row.status, active: row.active } : null; }

export function createMongoosePublicOrganizationRepository(connection: Connection): PublicOrganizationRepository {
  const organizations = connection.collection('organizations'); const profiles = connection.collection('provider_profiles'); const projects = connection.collection('projects'); const properties = connection.collection('properties');
  async function hydrate(row: Row): Promise<PublicOrganizationSource | null> { const providerId = id(row.providerId); if (!providerId) return null; const provider = await profiles.findOne({ _id: new Types.ObjectId(providerId), status: 'approved' }, { projection: { _id: 1, status: 1 } }); if (!provider || typeof provider.status !== 'string') return null; const organizationId = id(row._id); if (!organizationId) return null; const [projectRows, propertyRows] = await Promise.all([projects.find({ organizationId: new Types.ObjectId(organizationId) }, { projection: { _id: 1, slug: 1, name: 1, imageUrl: 1, description: 1, website: 1, locationName: 1, statusLabel: 1, projectType: 1, unitCount: 1, areaLabel: 1, priceLabel: 1, deliveryLabel: 1, status: 1 } }).sort({ slug: 1, _id: 1 }).limit(1000).toArray(), properties.find({ organizationId: new Types.ObjectId(organizationId) }, { projection: { _id: 1, slug: 1, kind: 1, name: 1, imageUrl: 1, transactionType: 1, projectId: 1, status: 1, active: 1 } }).sort({ slug: 1, _id: 1 }).limit(1000).toArray()]); return organization(row, projectRows.flatMap(value => { const mapped = mapProject(value as Row); return mapped ? [mapped] : []; }), propertyRows.flatMap(value => { const mapped = mapProperty(value as Row); return mapped ? [mapped] : []; }), provider.status); }
  return { async list(query) { const filter: Row = { status: 'approved' }; if (query.kind) filter.kind = query.kind; if (query.search) filter.$text = { $search: query.search }; const direction: 1 | -1 = query.direction === 'asc' ? 1 : -1; const sort: Record<string, 1 | -1> = query.sort === 'name' ? { 'name.en': direction, slug: 1, _id: 1 } : { slug: direction, _id: 1 }; const [rows, total] = await Promise.all([organizations.find(filter).sort(sort).skip((query.page - 1) * query.limit).limit(query.limit).toArray(), organizations.countDocuments(filter)]); const items = (await Promise.all(rows.map(row => hydrate(row as Row)))).flatMap(value => value ? [value] : []); return { items, total: items.length < total ? total : items.length }; }, async findBySlug(slug) { const row = await organizations.findOne({ slug, status: 'approved' }); return row ? hydrate(row as Row) : null; } };
}
