import assert from 'node:assert/strict';import test from 'node:test';
import type{AccessTokenClaims,AccessTokenService}from'../../src/modules/auth/crypto.js';import type{FeatureData,FeatureService}from'../../src/modules/taxonomy/features.js';import{FeatureError}from'../../src/modules/taxonomy/features.js';import{createApiServer,startApiServer,stopApiServer}from'../../src/server.js';
const admin='0123456789abcdef01234567',viewer='1123456789abcdef01234567',featureId='2123456789abcdef01234567';
const tokens:AccessTokenService={issue(){return'unused'},verify(token){if(token==='bad')throw Error();return{iss:'sadat-real-estate-api',aud:'sadat-real-estate',sub:token==='viewer'?viewer:admin,sid:'3123456789abcdef01234567',role:token==='seeker'?'seeker':'admin',status:'verified',iat:1,exp:2,jti:'x'}as AccessTokenClaims}};
const item=():FeatureData=>({id:featureId,kind:'feature',groupKey:'building_amenities',name:{ar:'مصعد',en:'Elevator'},slug:'elevator',order:1,active:true,version:0,createdAt:'2026-08-14T08:00:00.000Z',updatedAt:'2026-08-14T08:00:00.000Z',availableActions:['update','delete']});
const service:FeatureService={async list(id,q){if(id===viewer)throw new FeatureError('FEATURE_FORBIDDEN');return{items:q.active===false?[]:[item()],total:q.active===false?0:1}},async create(_id,input){return{...item(),kind:input.kind,groupKey:input.groupKey,slug:input.slug}},async update(_id,target,input){if(target!==featureId)throw new FeatureError('FEATURE_NOT_FOUND');return{...item(),active:input.active??true,version:1}},async delete(_id,target,input){if(input.reason==='Referenced feature')throw new FeatureError('FEATURE_IN_USE');return{id:target,deleted:true}}};
async function run(fn:(url:string)=>Promise<void>){const server=createApiServer({database:{isReady:async()=>true},features:{service,accessTokens:tokens}});const address=await startApiServer(server,{host:'127.0.0.1',port:0});try{await fn(`http://127.0.0.1:${address.port}`)}finally{await stopApiServer(server)}}
const req=(url:string,method:string,path:string,token:string,body?:unknown)=>fetch(url+path,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
test('feature routes enforce authentication, admin role, permission, and strict input',async()=>run(async url=>{assert.equal((await fetch(url+'/api/v1/admin/features')).status,401);assert.equal((await req(url,'GET','/api/v1/admin/features','seeker')).status,403);assert.equal((await req(url,'GET','/api/v1/admin/features','viewer')).status,403);assert.equal((await req(url,'GET','/api/v1/admin/features?limit=101','admin')).status,400);assert.equal((await req(url,'POST','/api/v1/admin/features','admin',{kind:'feature',groupKey:'bad key',name:{en:'X'},slug:'Bad',reason:'Invalid feature',extra:true})).status,400)}));
test('feature routes support ordered CRUD and guard referenced deletion',async()=>run(async url=>{const listed=await req(url,'GET','/api/v1/admin/features?kind=feature&active=true','admin');assert.equal(listed.status,200);assert.equal((await listed.json()as{data:{items:unknown[]}}).data.items.length,1);assert.equal((await req(url,'POST','/api/v1/admin/features','admin',{kind:'feature',groupKey:'building_amenities',name:{en:'Elevator'},slug:'elevator',order:1,reason:'Create feature'})).status,201);assert.equal((await req(url,'PATCH',`/api/v1/admin/features/${featureId}`,'admin',{version:0,active:false,reason:'Deactivate feature'})).status,200);assert.equal((await req(url,'DELETE',`/api/v1/admin/features/${featureId}`,'admin',{version:0,reason:'Referenced feature'})).status,409)}));
