import assert from 'node:assert/strict';import test from 'node:test';
import {taxonomyCreateSchema,taxonomyListQuerySchema,taxonomyPatchSchema} from '@sadat-real-estate/contracts';
import {createTaxonomyService,TaxonomyError,type StoredTaxonomy,type TaxonomyStore} from '../../src/modules/taxonomy/module.js';
const admin='0123456789abcdef01234567',viewer='1123456789abcdef01234567',category='2123456789abcdef01234567',typeId='3123456789abcdef01234567',at=new Date('2026-08-14T08:00:00Z');
const base=(o:Partial<StoredTaxonomy>={}):StoredTaxonomy=>({id:category,kind:'category',name:{en:'Residential'},slug:'residential',order:0,active:true,version:0,createdAt:at,updatedAt:at,...o});
function fixture(inUse=false){const m=new Map([[category,base()]]);const store:TaxonomyStore={async list(){return{items:[...m.values()],total:m.size}},async find(id){return m.get(id)??null},async categoryExists(id){return m.get(id)?.kind==='category'},async create(v){if([...m.values()].some(x=>x.slug===v.slug))return{kind:'slug_conflict'};const item=base({...v,id:typeId});m.set(typeId,item);return{kind:'written',item}},async update(id,v,c){const x=m.get(id);if(!x)return{kind:'not_found'};if(x.version!==v)return{kind:'version_conflict'};const item={...x,...c,version:v+1};m.set(id,item);return{kind:'written',item}},async delete(id,v){const x=m.get(id);if(!x)return{kind:'not_found'};if(inUse)return{kind:'in_use'};if(x.version!==v)return{kind:'version_conflict'};m.delete(id);return{kind:'deleted'}}};return createTaxonomyService({store,authorization:{async authorize(id,p){return id===admin||(id===viewer&&p.endsWith('.view'))}},now:()=>at});}
test('validates strict localized hierarchy, slugs, optimistic mutations, and bounded lists',()=>{assert.equal(taxonomyCreateSchema.safeParse({kind:'type',name:{en:'Apartment'},slug:'apartment',reason:'Missing category'}).success,false);assert.equal(taxonomyCreateSchema.safeParse({kind:'category',name:{en:'Residential'},slug:'Bad Slug',reason:'Invalid slug'}).success,false);assert.equal(taxonomyPatchSchema.safeParse({version:0,reason:'No change'}).success,false);assert.equal(taxonomyListQuerySchema.safeParse({limit:'101'}).success,false);assert.equal(taxonomyCreateSchema.safeParse({kind:'category',name:{en:'X'},slug:'xx',reason:'Unknown field',ownerId:admin}).success,false);});
test('enforces view/manage permissions and category-to-type relationship',async()=>{const s=fixture();assert.deepEqual((await s.list({userId:viewer},{sort:'order',direction:'asc',page:1,limit:20})).data.items[0]?.availableActions,[]);await assert.rejects(s.create({userId:viewer},{kind:'category',name:{en:'Denied'},slug:'denied',order:0,active:true,reason:'Viewer denied'},{requestId:'1',traceId:'a'.repeat(32)}),/TAXONOMY_FORBIDDEN/);const x=await s.create({userId:admin},{kind:'type',categoryId:category,name:{en:'Apartment'},slug:'apartment',order:1,active:true,reason:'Create property type'},{requestId:'2',traceId:'b'.repeat(32)});assert.equal(x.categoryId,category);await assert.rejects(s.create({userId:admin},{kind:'type',categoryId:'4123456789abcdef01234567',name:{en:'Unknown'},slug:'unknown',order:0,active:true,reason:'Unknown category'},{requestId:'3',traceId:'c'.repeat(32)}),/TAXONOMY_CATEGORY_NOT_FOUND/);});
test('handles duplicate, ordering, activation, concurrency, replay, and referenced deletion',async()=>{const s=fixture();await assert.rejects(s.create({userId:admin},{kind:'category',name:{en:'Duplicate'},slug:'residential',order:0,active:true,reason:'Duplicate category'},{requestId:'4',traceId:'d'.repeat(32)}),/TAXONOMY_SLUG_EXISTS/);const x=await s.update({userId:admin},category,{version:0,order:2,active:false,reason:'Reorder category'},{requestId:'5',traceId:'e'.repeat(32)});assert.equal(x.active,false);await assert.rejects(s.update({userId:admin},category,{version:0,order:3,reason:'Stale update'},{requestId:'6',traceId:'f'.repeat(32)}),/TAXONOMY_VERSION_CONFLICT/);await assert.rejects(fixture(true).delete({userId:admin},category,{version:0,reason:'Referenced deletion'},{requestId:'7',traceId:'1'.repeat(32)}),(e)=>e instanceof TaxonomyError&&e.code==='TAXONOMY_IN_USE');});
