import { useEffect, useState } from 'react';
import type { AdminUserData, AdminUserListData, RbacPermission, RbacRoleData, SupportedLocale } from '@sadat-real-estate/contracts';
import { Button } from '../design_system/index.ts';
import type { AdminRbacSource } from './data.ts';

const resources: Record<string, [string, string]> = {
  'account-reports': ['بلاغات الحسابات', 'Account reports'], ads: ['الإعلانات', 'Advertising'], audit: ['سجل التدقيق', 'Audit log'], banners: ['البانرات', 'Banners'], commissions: ['العمولات', 'Commissions'], community: ['المجتمع', 'Community'], content: ['محتوى الموقع', 'Website content'], documents: ['المستندات', 'Documents'], features: ['المميزات والخدمات', 'Amenities'], locations: ['المواقع', 'Locations'], overview: ['لوحة التحكم', 'Dashboard'], payments: ['المدفوعات', 'Payments'], projects: ['المشاريع', 'Projects'], properties: ['العقارات', 'Properties'], 'property-reports': ['بلاغات العقارات', 'Property reports'], providers: ['عارضو العقارات', 'Providers'], 'request-issues': ['مشكلات الطلبات', 'Request issues'], requests: ['طلبات العملاء', 'Customer requests'], roles: ['المناصب والصلاحيات', 'Roles'], settings: ['الإعدادات', 'Settings'], staff: ['موظفو الإدارة', 'Administrator staff'], taxonomy: ['أنواع العقارات', 'Property types'], users: ['الحسابات', 'Accounts'], viewings: ['المعاينات', 'Viewings']
};
const actions: Record<string, [string, string]> = { view: ['عرض', 'View'], manage: ['إدارة وتعديل', 'Manage'], review: ['مراجعة واعتماد', 'Review'], publish: ['نشر', 'Publish'], price: ['تسعير', 'Price'], schedule: ['جدولة', 'Schedule'], moderate: ['مراجعة المحتوى', 'Moderate'], assign: ['تعيين مسؤول', 'Assign'], notes: ['إضافة ملاحظات', 'Add notes'] };

export function PermissionChooser({ locale, catalog, value, mode, disabled, change, applyPreset }: { readonly locale: SupportedLocale; readonly catalog: readonly RbacPermission[]; readonly value: readonly RbacPermission[]; readonly mode: 'custom' | 'view_only'; readonly disabled: boolean; readonly change: (permissions: RbacPermission[]) => void; readonly applyPreset: (name: string, permissions: RbacPermission[], mode: 'custom' | 'view_only') => void }) {
  const ar = locale === 'ar'; const index = ar ? 0 : 1;
  const allowed = catalog.filter(permission => mode !== 'view_only' || permission.endsWith('.view'));
  const presets = [
    { name: ar ? 'مدير المنصة — كل الصلاحيات' : 'Platform manager — all permissions', mode: 'custom' as const, permissions: [...catalog] },
    { name: ar ? 'مسؤول العقارات والعارضين' : 'Property and provider reviewer', mode: 'custom' as const, permissions: catalog.filter(item => /^admin:(overview|properties|providers|projects|documents|features|locations|taxonomy)\./.test(item)) },
    { name: ar ? 'مسؤول العملاء والمعاينات' : 'Customer and viewing coordinator', mode: 'custom' as const, permissions: catalog.filter(item => /^admin:(overview|requests|viewings|users)\./.test(item)) },
    { name: ar ? 'مسؤول المحتوى والإعلانات' : 'Content and advertising manager', mode: 'custom' as const, permissions: catalog.filter(item => /^admin:(overview|content|banners|ads|community)\./.test(item)) },
    { name: ar ? 'عرض فقط' : 'View only', mode: 'view_only' as const, permissions: catalog.filter(item => item.endsWith('.view')) }
  ];
  return <section className="admin-rbac__role-tools">
    <label className="admin-rbac__field">{ar ? 'منصب جاهز (اختياري)' : 'Role preset (optional)'}<select value="" disabled={disabled} onChange={event => { if (event.currentTarget.value === '') return; const preset = presets[Number(event.currentTarget.value)]; if (preset) applyPreset(preset.name, [...preset.permissions], preset.mode); }}><option value="">{ar ? 'اختر منصبًا أو حدد الصلاحيات بنفسك' : 'Choose a preset or customize permissions'}</option>{presets.map((preset, position) => <option key={preset.name} value={position}>{preset.name}</option>)}</select></label>
    <p className="admin-rbac__muted">{ar ? 'المنصب مجموعة صلاحيات تُربط بموظف. الاختيار الجاهز يعبّئ الصلاحيات ويمكنك تعديلها قبل الحفظ. مدير المنصة هنا يحصل على الصلاحيات الحالية؛ المسؤول الأعلى يمتلك وصولًا كاملًا دائمًا.' : 'A role groups permissions assigned to an employee. Presets fill the selection and remain editable before saving. Platform manager selects the current catalog; Super Admin always has full access.'}</p>
    <div className="admin-rbac__actions"><Button type="button" size="sm" variant="secondary" disabled={disabled} onClick={() => change([...allowed])}>{ar ? 'تحديد الكل' : 'Select all'}</Button><Button type="button" size="sm" variant="secondary" disabled={disabled} onClick={() => change([])}>{ar ? 'إلغاء تحديد الكل' : 'Clear selection'}</Button><span role="status">{ar ? 'الصلاحيات المحددة' : 'Selected permissions'}: {value.length} / {catalog.length}</span></div>
    <fieldset className="admin-rbac__permissions"><legend>{ar ? 'الصلاحيات' : 'Permissions'}</legend>{catalog.map(permission => {
      const [resource, action] = permission.slice(6).split('.');
      return <label key={permission}><input type="checkbox" checked={value.includes(permission)} disabled={disabled || !allowed.includes(permission)} onChange={() => change(value.includes(permission) ? value.filter(item => item !== permission) : [...value, permission])} /><span>{resources[resource ?? '']?.[index] ?? resource} — {actions[action ?? '']?.[index] ?? action}<small dir="ltr">{permission}</small></span></label>;
    })}</fieldset>
  </section>;
}

export function StaffRoles({ locale, source, value, change, disabled, required = false }: { readonly locale: SupportedLocale; readonly source: AdminRbacSource; readonly value: readonly string[]; readonly change: (ids: string[]) => void; readonly disabled: boolean; readonly required?: boolean }) {
  const ar = locale === 'ar'; const [roles, setRoles] = useState<RbacRoleData[]>([]); const [error, setError] = useState(false); const [canAssign, setCanAssign] = useState(false);
  useEffect(() => { const controller = new AbortController(); void source.loadRoles(controller.signal).then(data => { if (!controller.signal.aborted) { setRoles(data.items); setCanAssign(data.effectivePermissions.includes('admin:roles.manage')); } }).catch(() => { if (!controller.signal.aborted) setError(true); }); return () => controller.abort(); }, [source]);
  return <fieldset className="admin-rbac__permissions"><legend>{ar ? `منصب الموظف${required ? ' (مطلوب)' : ''}` : `Employee roles${required ? ' (required)' : ''}`}</legend>{roles.filter(role => role.active || value.includes(role.id)).map(role => <label key={role.id}><input type="checkbox" checked={value.includes(role.id)} disabled={disabled || !canAssign || !role.active} onChange={() => change(value.includes(role.id) ? value.filter(id => id !== role.id) : [...value, role.id])} /><span>{role.name}<small>{role.description ?? (role.accessMode === 'view_only' ? (ar ? 'عرض بدون تعديل' : 'Read only') : (ar ? `${role.permissions.length} صلاحية` : `${role.permissions.length} permissions`))}</small></span></label>)}{error || (roles.length > 0 && !canAssign) ? <p role="status">{ar ? 'تحديد المنصب يحتاج صلاحية إدارة المناصب. يمكنك مراجعتها مع المسؤول الأعلى.' : 'Role assignment requires role management permission. Contact the Super Admin.'}</p> : null}{!error && roles.length === 0 ? <p>{ar ? 'لا توجد مناصب متاحة بعد. أنشئ منصبًا من الأدوار والصلاحيات.' : 'No roles available yet. Create a role first.'}</p> : null}</fieldset>;
}

export function RoleStaff({ locale, source, role, canAssign }: { readonly locale: SupportedLocale; readonly source: AdminRbacSource; readonly role: RbacRoleData; readonly canAssign: boolean }) {
  const ar = locale === 'ar'; const [search, setSearch] = useState(''); const [query, setQuery] = useState({ search: '', page: 1 }); const [data, setData] = useState<AdminUserListData>(); const [selected, setSelected] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState('');
  useEffect(() => { if (!canAssign) return; const controller = new AbortController(); setSelected(''); setData(undefined); void source.loadUsers({ page: query.page, limit: 20, status: 'active', accessLevel: 'standard_admin', ...(query.search ? { search: query.search } : {}) }, controller.signal).then(next => { if (!controller.signal.aborted) setData(next); }).catch(() => { if (!controller.signal.aborted) setFeedback(ar ? 'تعذر تحميل الموظفين. راجع صلاحية عرض موظفي الإدارة ثم أعد البحث.' : 'Could not load employees. Check staff view permission and search again.'); }); return () => controller.abort(); }, [source, query, canAssign, ar]);
  const employee: AdminUserData | undefined = data?.items.find(item => item.id === selected);
  return <section className="admin-rbac__form-panel"><h2>{ar ? 'مين هيشتغل بالمنصب ده؟' : 'Who will use this role?'}</h2><p className="admin-rbac__muted">{ar ? 'اختر موظفًا موجودًا بالاسم والإيميل، أو أضف موظفًا جديدًا بكلمة مرور واربطه بهذا المنصب. كلمة المرور لا تُعرض بعد الحفظ. احفظ تعديل المنصب أولًا؛ الإسناد يطبّق صلاحياته المحفوظة.' : 'Choose an existing employee by name and email, or create an employee with a password and this role. Saved passwords are never displayed. Save role changes before assigning employees.'}</p>{canAssign ? <a className="admin-rbac__secondary-link" href={`/admin/admin-users/new?roleId=${role.id}&lang=${locale}`}>{ar ? 'إضافة موظف بهذا المنصب' : 'Add employee with this role'}</a> : null}
    {canAssign ? <form onSubmit={event => { event.preventDefault(); if (!employee || busy || reason.trim().length < 3) return; setBusy(true); setFeedback(''); void source.updateUser(employee.id, { expectedVersion: employee.version, reason: reason.trim(), roleIds: [...new Set([...(employee.roleIds ?? []), role.id])] }).then(next => { setData(current => current ? { ...current, items: current.items.map(item => item.id === next.id ? next : item) } : current); setFeedback(ar ? 'تم ربط الموظف بالمنصب. يبدأ دخوله القادم بالصلاحيات الجديدة.' : 'Employee assigned. New permissions apply at the next sign-in.'); setReason(''); }).catch(() => setFeedback(ar ? 'تعذر ربط الموظف. بياناتك محفوظة؛ أعد البحث لتحديث إصدار الحساب وراجع الصلاحيات.' : 'Assignment failed. Your input is preserved; search again for the latest account version and check permissions.')).finally(() => setBusy(false)); }}>
      <label className="admin-rbac__field">{ar ? 'بحث باسم الموظف أو الإيميل' : 'Search employee name or email'}<input value={search} maxLength={160} disabled={busy} onChange={event => setSearch(event.currentTarget.value)} /></label><Button type="button" variant="secondary" disabled={busy} onClick={() => { setFeedback(''); setQuery({ search: search.trim(), page: 1 }); }}>{ar ? 'بحث' : 'Search'}</Button>
      <label className="admin-rbac__field">{ar ? 'الموظف' : 'Employee'}<select required value={selected} disabled={busy || !data} onChange={event => setSelected(event.currentTarget.value)}><option value="">{ar ? 'اختر موظفًا' : 'Choose an employee'}</option>{data?.items.map(item => <option key={item.id} value={item.id}>{item.displayName} — {item.email}</option>)}</select></label>{data?.items.length === 0 ? <p>{ar ? 'لا توجد نتائج؛ أضف الموظف أو غيّر البحث.' : 'No results. Add an employee or change the search.'}</p> : null}
      {data && data.total > data.limit ? <div className="admin-rbac__pagination"><Button type="button" variant="secondary" disabled={busy || query.page === 1} onClick={() => setQuery(current => ({ ...current, page: current.page - 1 }))}>{ar ? 'السابق' : 'Previous'}</Button><span>{query.page} / {Math.ceil(data.total / data.limit)}</span><Button type="button" variant="secondary" disabled={busy || query.page * data.limit >= data.total} onClick={() => setQuery(current => ({ ...current, page: current.page + 1 }))}>{ar ? 'التالي' : 'Next'}</Button></div> : null}
      <label className="admin-rbac__field">{ar ? 'سبب إسناد المنصب' : 'Assignment reason'}<textarea value={reason} required minLength={3} maxLength={500} disabled={busy} onChange={event => setReason(event.currentTarget.value)} /></label><Button type="submit" loading={busy} disabled={!employee || !role.active || reason.trim().length < 3 || (employee.roleIds ?? []).includes(role.id)}>{ar ? 'ربط الموظف بالمنصب' : 'Assign employee to role'}</Button>{employee?.roleIds?.includes(role.id) ? <p>{ar ? 'الموظف مرتبط بهذا المنصب بالفعل.' : 'Employee already has this role.'}</p> : null}
    </form> : <p className="admin-rbac__muted">{ar ? 'ربط الموظفين يحتاج صلاحيات إدارة الموظفين والمناصب.' : 'Assignment requires staff and role management permissions.'}</p>}{feedback ? <p className="admin-rbac__feedback" role="status">{feedback}</p> : null}</section>;
}

export function RoleAccountGuide({ locale, roleId, canCreate = true }: { readonly locale: SupportedLocale; readonly roleId?: string | undefined; readonly canCreate?: boolean }) {
  const ar = locale === 'ar';
  return <aside className="admin-rbac__form-panel admin-rbac__account-guide" aria-label={ar ? 'إزاي الموظف يدخل ويستخدم المنصب؟' : 'How does an employee sign in and use a role?'}>
    <h2>{ar ? 'إزاي الموظف يدخل ويستخدم المنصب؟' : 'How does an employee sign in and use a role?'}</h2>
    <p>{ar ? 'المنصب مجموعة صلاحيات، مش حساب دخول. حساب الموظف بتنشئه من «المستخدمون الإداريون»؛ إضافة شخص في فريق العمل لا تنشئ له حساب إدارة.' : 'A role is a set of permissions, not a login account. Create the employee under Administrator users; adding a person to the public team does not create an administrator account.'}</p>
    <ol>
      <li>{ar ? 'احفظ المنصب والصلاحيات المطلوبة أولًا.' : 'Save the role and its required permissions first.'}</li>
      <li>{ar ? 'لو الموظف جديد: أضف اسمه وإيميله وكلمة مرور، واختر «مسؤول قياسي» والمنصب المناسب. لو عنده حساب إدارة بالفعل: افتح المنصب واربطه من «مين هيشتغل بالمنصب ده؟» أو عدّل حسابه.' : 'For a new employee, enter their name, email and password, then choose Standard Admin and the role. For an existing administrator, assign them from “Who will use this role?” on the role page or edit their account.'}</li>
      <li>{ar ? 'أبلغ الموظف بالإيميل وكلمة المرور اللي اخترتها ورابط تسجيل الدخول. كلمة المرور لا تظهر بعد الحفظ، وإنشاء الحساب لا يرسل دعوة دخول تلقائية.' : 'Give the employee their email, the password you chose and the login link. The password is not displayed after saving, and creating the account does not send an automatic login invitation.'}</li>
      <li>{ar ? 'يدخل من صفحة تسجيل الدخول العادية بالإيميل وكلمة المرور. لو التحقق بخطوتين مفعّل، يكمل كود التحقق المرسل لإيميله، ثم يفتح لوحة الإدارة ويستخدم الصلاحيات المسندة له.' : 'They use the normal login page with email and password. If two-factor verification is enabled, they complete the code sent to their email, then open administration with their assigned permissions.'}</li>
    </ol>
    <div className="admin-rbac__actions">
      {canCreate ? <a className="ui-button ui-button--primary" href={`/admin/admin-users/new?${roleId ? `roleId=${roleId}&` : ''}lang=${locale}`}>{ar ? 'إنشاء حساب موظف' : 'Create employee account'}</a> : null}
      <a className="admin-rbac__secondary-link" href={`/admin/admin-users?lang=${locale}`}>{ar ? 'حسابات موظفي الإدارة' : 'Administrator accounts'}</a>
      <a className="admin-rbac__secondary-link" href={`/auth/login?lang=${locale}`} target="_blank" rel="noopener noreferrer">{ar ? 'رابط دخول الموظف' : 'Employee login link'}</a>
    </div>
    {!canCreate ? <p>{ar ? 'إنشاء الحساب وربطه بالمنصب يحتاج صلاحيات إدارة الموظفين والمناصب ومنصبًا نشطًا؛ راجع المسؤول الأعلى.' : 'Creating an account with a role requires staff and role management permissions and an active role; contact the Super Admin.'}</p> : null}
  </aside>;
}

export function StaffLoginHandoff({ locale, email }: { locale: SupportedLocale; email: string }) {
  const ar = locale === 'ar';
  return <div className="admin-rbac__account-guide" role="status"><p>{ar ? `تم إنشاء الحساب بالإيميل ${email}. أبلغ الموظف بالإيميل وكلمة المرور اللي اخترتها؛ كلمة المرور لا تظهر بعد الحفظ ولا تُرسل دعوة دخول تلقائية.` : `Account created for ${email}. Give the employee their email and the password you chose; saved passwords are not displayed and no login invitation is sent automatically.`}</p><a href={`/auth/login?lang=${locale}`} target="_blank" rel="noopener noreferrer">{ar ? 'رابط دخول الموظف' : 'Employee login link'}</a></div>;
}
