import { Schema, Types, type Connection, type Model } from 'mongoose';
import type { AccessTokenService } from '../auth/crypto.js';
import type { AuditWriter } from '../audit/writer.js';
import type { RbacService } from '../rbac/service.js';
import { createTaxonomyService, type StoredTaxonomy, type TaxonomyStore } from './module.js';
import type { TaxonomyRouterDependencies } from './router.js';

interface Rec {kind:'category'|'type';categoryId?:Types.ObjectId;name:{ar?:string;en?:string};slug:string;order:number;active:boolean;createdBy:Types.ObjectId;updatedBy:Types.ObjectId;createdAt:Date;updatedAt:Date;version:number}
const names=new Schema({ar:{type:String,trim:true},en:{type:String,trim:true}},{_id:false,strict:'throw'});
const schema=new Schema<Rec>({kind:{type:String,enum:['category','type'],required:true,immutable:true},categoryId:{type:Schema.Types.ObjectId,ref:'PropertyTaxonomy'},name:{type:names,required:true},slug:{type:String,required:true,lowercase:true,match:/^[a-z0-9]+(?:-[a-z0-9]+)*$/},order:{type:Number,min:0,max:1_000_000,default:0},active:{type:Boolean,default:true},createdBy:{type:Schema.Types.ObjectId,required:true,immutable:true},updatedBy:{type:Schema.Types.ObjectId,required:true}},{collection:'property_taxonomy',strict:'throw',timestamps:true,versionKey:'version',optimisticConcurrency:true});
schema.pre('validate',function(){if(this.kind==='type'&&!this.categoryId)this.invalidate('categoryId','Type category required');if(this.kind==='category'&&this.categoryId)this.invalidate('categoryId','Category cannot have parent');});
schema.index({slug:1},{unique:true,name:'property_taxonomy_slug_unique'});schema.index({kind:1,categoryId:1,active:1,order:1,slug:1},{name:'property_taxonomy_hierarchy_order'});schema.index({'name.ar':'text','name.en':'text'},{name:'property_taxonomy_name_search',default_language:'none'});
const map=(x:Rec&{_id:Types.ObjectId}):StoredTaxonomy=>({id:x._id.toHexString(),kind:x.kind,...(x.categoryId?{categoryId:x.categoryId.toHexString()}:{}),name:x.name,slug:x.slug,order:x.order,active:x.active,version:x.version,createdAt:x.createdAt,updatedAt:x.updatedAt});
export function createTaxonomyRuntime(connection:Connection,accessTokens:AccessTokenService,audit:AuditWriter,authorization:RbacService):TaxonomyRouterDependencies{const model=(connection.models.PropertyTaxonomy as Model<Rec>|undefined)??connection.model<Rec>('PropertyTaxonomy',schema);const store:TaxonomyStore={
  async list(q){const f:Record<string,unknown>={};if(q.kind)f.kind=q.kind;if(q.categoryId)f.categoryId=new Types.ObjectId(q.categoryId);if(q.active!==undefined)f.active=q.active;if(q.search)f.$text={$search:q.search};const d:1|-1=q.direction==='asc'?1:-1;const sort:Record<string,1|-1>=q.sort==='order'?{order:d,slug:1}:{[q.sort]:d,slug:1};const[rows,total]=await Promise.all([model.find(f).sort(sort).skip((q.page-1)*q.limit).limit(q.limit).lean(),model.countDocuments(f)]);return{items:rows.map(x=>map(x as Rec&{_id:Types.ObjectId})),total};},
  async find(id){const x=await model.findById(id).lean();return x?map(x as Rec&{_id:Types.ObjectId}):null;},async categoryExists(id){return Boolean(await model.exists({_id:id,kind:'category'}));},
  async create(v,m){try{const doc=new model({...v,...(v.categoryId?{categoryId:new Types.ObjectId(v.categoryId)}:{}),createdBy:new Types.ObjectId(m.actorId),updatedBy:new Types.ObjectId(m.actorId),createdAt:m.at,updatedAt:m.at});await doc.save();const item=map(doc.toObject() as Rec&{_id:Types.ObjectId});await audit.record({actorType:'admin',actorId:m.actorId,targetType:'property_taxonomy',targetId:item.id,action:'taxonomy.create',reason:m.reason,before:null,after:item,requestId:m.requestId,traceId:m.traceId,occurredAt:m.at});return{kind:'written',item};}catch(e){if(typeof e==='object'&&e!==null&&'code'in e&&e.code===11000)return{kind:'slug_conflict'};throw e;}},
  async update(id,version,changes,_before,m){try{const set:Record<string,unknown>={...changes,updatedBy:new Types.ObjectId(m.actorId),updatedAt:m.at};if(changes.categoryId)set.categoryId=new Types.ObjectId(changes.categoryId);const x=await model.findOneAndUpdate({_id:id,version},{$set:set,$inc:{version:1}},{new:true,runValidators:true,lean:true});if(!x)return await model.exists({_id:id})?{kind:'version_conflict'}:{kind:'not_found'};const item=map(x as Rec&{_id:Types.ObjectId});await audit.record({actorType:'admin',actorId:m.actorId,targetType:'property_taxonomy',targetId:id,action:'taxonomy.update',reason:m.reason,before:_before,after:item,requestId:m.requestId,traceId:m.traceId,occurredAt:m.at});return{kind:'written',item};}catch(e){if(typeof e==='object'&&e!==null&&'code'in e&&e.code===11000)return{kind:'slug_conflict'};throw e;}},
  async delete(id,version,before,m){const oid=new Types.ObjectId(id);const refs=before.kind==='category'?await model.countDocuments({categoryId:oid}):await connection.collection('properties').countDocuments({$or:[{propertyTypeId:oid},{propertyCategoryId:oid}]});if(refs)return{kind:'in_use'};const x=await model.findOneAndDelete({_id:id,version});if(!x)return await model.exists({_id:id})?{kind:'version_conflict'}:{kind:'not_found'};await audit.record({actorType:'admin',actorId:m.actorId,targetType:'property_taxonomy',targetId:id,action:'taxonomy.delete',reason:m.reason,before,after:null,requestId:m.requestId,traceId:m.traceId,occurredAt:m.at});return{kind:'deleted'};}
};return{accessTokens,service:createTaxonomyService({store,authorization})};}
