import assert from 'node:assert/strict';
import test from 'node:test';
import type { AccessTokenClaims } from '../../src/modules/auth/crypto.js';
import { createInMemoryViewingRepository, createViewingService, type ViewingRecord } from '../../src/modules/viewings/service.js';
const seeker = { iss: 'sadat-real-estate-api', aud: 'sadat-real-estate', sub: '0123456789abcdef01234567', sid: '1123456789abcdef01234567', role: 'seeker', status: 'verified', iat: 1, exp: 9999999999, jti: 'test' } as AccessTokenClaims;
const provider = { ...seeker, sub: '2123456789abcdef01234567', role: 'provider' } as AccessTokenClaims;
const property = '3123456789abcdef01234567'; const viewingId = '4123456789abcdef01234567'; const stamp = new Date('2026-08-14T10:00:00.000Z');
test('creates future request-and-confirm viewings and prevents duplicate competing times', async () => { const repo = createInMemoryViewingRepository(); const service = createViewingService({ repository: repo, now: () => stamp }); const created = await service.create(seeker, { propertyId: property, requestedAt: '2026-08-15T10:00:00.000Z', timezone: 'Africa/Cairo' }); assert.equal(created.status, 'requested'); assert.equal(created.version, 0); await assert.rejects(() => service.create(seeker, { propertyId: property, requestedAt: '2026-08-15T10:00:00.000Z', timezone: 'Africa/Cairo' }), /VIEWING_CONFLICT/); await assert.rejects(() => service.create(seeker, { propertyId: property, requestedAt: '2026-08-13T10:00:00.000Z', timezone: 'Africa/Cairo' }), /VIEWING_INVALID_STATE/); });
test('enforces seeker ownership, optimistic reschedule/cancel, and provider scope', async () => { const seed: ViewingRecord = { id: viewingId, propertyId: property, seekerId: seeker.sub, providerId: provider.sub, status: 'requested', requestedAt: new Date('2026-08-15T10:00:00.000Z'), timezone: 'UTC', version: 0, createdAt: stamp, updatedAt: stamp }; const service = createViewingService({ repository: createInMemoryViewingRepository([seed]), now: () => stamp }); const rescheduled = await service.patch(seeker, viewingId, { requestedAt: '2026-08-16T10:00:00.000Z', timezone: 'UTC', expectedVersion: 0 }); assert.equal(rescheduled.status, 'rescheduled'); await assert.rejects(() => service.cancel({ ...seeker, sub: '5123456789abcdef01234567' } as AccessTokenClaims, viewingId, 1), /VIEWING_NOT_FOUND/); const confirmed = await service.transition(provider, viewingId, { action: 'confirm', expectedVersion: 1 }); assert.equal(confirmed.status, 'confirmed'); const cancelled = await service.cancel(seeker, viewingId, 2); assert.equal(cancelled.status, 'cancelled'); });
