import { Router, type Request, type Response } from 'express';
import { requestIdParamsSchema, requestListQuerySchema, requestNoteSchema, requestTransitionRequestSchema } from '@sadat-real-estate/contracts';
import type { AccessTokenClaims, AccessTokenService } from '../auth/crypto.js';
import { ApiContractError, toApiErrorResponse } from '../contracts/error-boundary.js';
import { toSuccessResponse } from '../contracts/response.js';
import { getRequestContext } from '../observability/context.js';
import { RequestServiceError } from './service.js';
import type { createRequestService } from './service.js';

export const REQUEST_ROUTE_DEFINITIONS = [
  { method: 'POST', path: '/api/v1/seeker/contact-requests', operationId: 'createSeekerContactRequest' }, { method: 'POST', path: '/api/v1/seeker/search-requests', operationId: 'createSeekerSearchRequest' }, { method: 'GET', path: '/api/v1/seeker/requests', operationId: 'listSeekerRequests' }, { method: 'GET', path: '/api/v1/seeker/requests/:requestId', operationId: 'getSeekerRequest' },
  { method: 'POST', path: '/api/v1/provider/customer-requests', operationId: 'createProviderCustomerRequest' }, { method: 'GET', path: '/api/v1/provider/customer-requests', operationId: 'listProviderCustomerRequests' }, { method: 'GET', path: '/api/v1/provider/customer-requests/:requestId', operationId: 'getProviderCustomerRequest' }, { method: 'POST', path: '/api/v1/provider/customer-requests/:requestId/transitions', operationId: 'transitionProviderCustomerRequest' },
  { method: 'GET', path: '/api/v1/admin/requests', operationId: 'listAdminRequests' }, { method: 'GET', path: '/api/v1/admin/requests/overdue', operationId: 'listOverdueAdminRequests' }, { method: 'GET', path: '/api/v1/admin/requests/:requestId', operationId: 'getAdminRequest' }, { method: 'POST', path: '/api/v1/admin/requests/:requestId/assign', operationId: 'assignAdminRequest' }, { method: 'POST', path: '/api/v1/admin/requests/:requestId/notes', operationId: 'addAdminRequestNote' }, { method: 'POST', path: '/api/v1/admin/requests/:requestId/transitions', operationId: 'transitionAdminRequest' }
] as const;
export interface RequestRouterDependencies { service: ReturnType<typeof createRequestService>; accessTokens: AccessTokenService; }
function context(request: Request): string { return getRequestContext()?.requestId ?? request.get('x-request-id') ?? 'unknown-request'; }
function claims(response: Response, role: 'seeker' | 'provider' | 'admin'): AccessTokenClaims { return response.locals[`${role}Claims`] as AccessTokenClaims; }
function bearer(accessTokens: AccessTokenService, role: AccessTokenClaims['role']) { return (request: Request, response: Response, next: () => void): void => { const token = request.get('authorization')?.replace(/^Bearer\s+/i, '').trim(); if (!token) { const body = toApiErrorResponse(new ApiContractError('AUTHENTICATION_REQUIRED', 'errors.authenticationRequired', 401), context(request)); response.status(401).json(body.body); return; } try { const current = accessTokens.verify(token); if (current.role !== role || current.status !== 'verified') throw new Error('forbidden'); response.locals[`${role}Claims`] = current; next(); } catch { const body = toApiErrorResponse(new ApiContractError('FORBIDDEN', 'errors.forbidden', 403), context(request)); response.status(403).json(body.body); } }; }
function send(request: Request, response: Response, error: unknown): void { const mapped: Record<string, { status: number; key: string }> = { REQUEST_FORBIDDEN: { status: 403, key: 'errors.forbidden' }, REQUEST_NOT_FOUND: { status: 404, key: 'errors.requests.notFound' }, REQUEST_VERSION_CONFLICT: { status: 409, key: 'errors.requests.versionConflict' }, REQUEST_INVALID_STATE: { status: 409, key: 'errors.requests.invalidState' }, REQUEST_DUPLICATE: { status: 409, key: 'errors.requests.duplicate' }, REQUEST_RATE_LIMITED: { status: 429, key: 'errors.rateLimited' } }; const serviceError = error instanceof RequestServiceError ? error : undefined; const current = serviceError ? mapped[serviceError.code] : undefined; const body = toApiErrorResponse(current && serviceError ? new ApiContractError(serviceError.code, current.key, current.status) : error, context(request)); response.status(body.statusCode).json(body.body); }
export function createRequestRouter(dependencies: RequestRouterDependencies): Router { const router = Router(); router.use((_request, response, next) => { response.setHeader('Cache-Control', 'no-store'); next(); });
  router.post('/seeker/contact-requests', bearer(dependencies.accessTokens, 'seeker'), async (req, res) => { try { const data = await dependencies.service.createContact(claims(res, 'seeker'), req.body ?? {}); res.status(201).json(toSuccessResponse(data, context(req))); } catch (e) { send(req, res, e); } });
  router.post('/seeker/search-requests', bearer(dependencies.accessTokens, 'seeker'), async (req, res) => { try { const data = await dependencies.service.create(claims(res, 'seeker'), { type: 'property_search', payload: req.body ?? {} }); res.status(201).json(toSuccessResponse(data, context(req))); } catch (e) { send(req, res, e); } });
  router.get('/seeker/requests', bearer(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res, 'seeker'), requestListQuerySchema.parse(req.query)), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/seeker/requests/:requestId', bearer(dependencies.accessTokens, 'seeker'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.get(claims(res, 'seeker'), requestIdParamsSchema.parse(req.params).requestId), context(req))); } catch (e) { send(req, res, e); } });
  router.post('/provider/customer-requests', bearer(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(201).json(toSuccessResponse(await dependencies.service.create(claims(res, 'provider'), { type: 'provider_customer', payload: req.body ?? {} }), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/provider/customer-requests', bearer(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res, 'provider'), requestListQuerySchema.parse(req.query)), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/provider/customer-requests/:requestId', bearer(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.get(claims(res, 'provider'), requestIdParamsSchema.parse(req.params).requestId), context(req))); } catch (e) { send(req, res, e); } });
  router.post('/provider/customer-requests/:requestId/transitions', bearer(dependencies.accessTokens, 'provider'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.transition(claims(res, 'provider'), requestIdParamsSchema.parse(req.params).requestId, requestTransitionRequestSchema.parse(req.body ?? {})), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/admin/requests', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.list(claims(res, 'admin'), requestListQuerySchema.parse(req.query)), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/admin/requests/overdue', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.overdue(claims(res, 'admin'), requestListQuerySchema.parse(req.query)), context(req))); } catch (e) { send(req, res, e); } });
  router.get('/admin/requests/:requestId', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.get(claims(res, 'admin'), requestIdParamsSchema.parse(req.params).requestId), context(req))); } catch (e) { send(req, res, e); } });
  router.post('/admin/requests/:requestId/assign', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.assign(claims(res, 'admin'), requestIdParamsSchema.parse(req.params).requestId, req.body ?? {}), context(req))); } catch (e) { send(req, res, e); } });
  router.post('/admin/requests/:requestId/notes', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.addNote(claims(res, 'admin'), requestIdParamsSchema.parse(req.params).requestId, requestNoteSchema.parse(req.body ?? {})), context(req))); } catch (e) { send(req, res, e); } });
  router.post('/admin/requests/:requestId/transitions', bearer(dependencies.accessTokens, 'admin'), async (req, res) => { try { res.status(200).json(toSuccessResponse(await dependencies.service.transition(claims(res, 'admin'), requestIdParamsSchema.parse(req.params).requestId, requestTransitionRequestSchema.parse(req.body ?? {})), context(req))); } catch (e) { send(req, res, e); } });
  return router;
}
