import { randomBytes } from 'node:crypto';
import type { AccessTokenClaims } from '../auth/crypto.js';
import { overdueRequestListDataSchema, requestAssignmentSchema, requestCreateSchema, requestDataSchema, requestListDataSchema, requestListQuerySchema, requestNoteSchema, requestTransitionRequestSchema, type RequestCreate, type RequestData, type RequestListData, type RequestListQuery, type RequestStatus, type RequestTransition } from '@sadat-real-estate/contracts';

export interface RequestRecord { id: string; type: RequestCreate['type']; source: 'seeker' | 'provider' | 'admin' | 'public'; creatorId?: string; seekerId?: string; providerId?: string; propertyId?: string; projectId?: string; status: RequestStatus; payload: Record<string, unknown>; assignedTo?: string; internalNotes?: Array<{ id: string; body: string; authorId: string; createdAt: Date }>; dueAt?: Date; appointmentAt?: Date; appointmentTimezone?: string; version: number; createdAt: Date; updatedAt: Date; }
export type RequestWriteResult = { kind: 'written'; request: RequestRecord } | { kind: 'not_found' } | { kind: 'version_conflict' } | { kind: 'invalid_state' } | { kind: 'duplicate' };
export interface RequestRepository { create(request: RequestRecord): Promise<RequestWriteResult>; list(query: RequestListQuery, scope?: { seekerId?: string; providerId?: string }): Promise<{ items: RequestRecord[]; total: number }>; get(id: string, scope?: { seekerId?: string; providerId?: string }): Promise<RequestRecord | undefined>; transition(input: { id: string; expectedVersion: number; status: RequestStatus; reason?: string; actorId: string; now: Date; }): Promise<RequestWriteResult>; assign(input: { id: string; expectedVersion: number; assigneeId: string; now: Date }): Promise<RequestWriteResult>; addNote(input: { id: string; expectedVersion: number; note: { id: string; body: string; authorId: string; createdAt: Date }; now: Date }): Promise<RequestWriteResult>; }

export type RequestServiceErrorCode = 'REQUEST_FORBIDDEN' | 'REQUEST_NOT_FOUND' | 'REQUEST_VERSION_CONFLICT' | 'REQUEST_INVALID_STATE' | 'REQUEST_DUPLICATE' | 'REQUEST_RATE_LIMITED';
export class RequestServiceError extends Error { constructor(readonly code: RequestServiceErrorCode) { super(code); this.name = 'RequestServiceError'; } }

function id(): string { return randomBytes(12).toString('hex'); }
function active(claims: AccessTokenClaims): boolean { return claims.status === 'verified' && ['seeker', 'provider', 'admin'].includes(claims.role); }
function available(status: RequestStatus, role: AccessTokenClaims['role']): RequestTransition[] { const map: Record<RequestStatus, RequestTransition[]> = { new: role === 'admin' || role === 'provider' ? ['start_review', 'contact', 'cancel'] : ['cancel'], under_review: ['contact', 'needs_information', 'cancel'], contacted: ['schedule', 'start_progress', 'resolve', 'cancel'], scheduled: ['start_progress', 'cancel'], needs_information: ['start_review', 'cancel'], in_progress: ['resolve', 'cancel'], resolved: role === 'admin' ? ['reopen', 'close'] : [], cancelled: role === 'admin' ? ['reopen', 'close'] : [], closed: role === 'admin' ? ['reopen'] : [] }; return map[status] ?? []; }
function project(request: RequestRecord, role: AccessTokenClaims['role']): RequestData { return requestDataSchema.parse({ id: request.id, type: request.type, source: request.source, ...(role === 'admin' ? { creatorId: request.creatorId, seekerId: request.seekerId, providerId: request.providerId, assignedTo: request.assignedTo, dueAt: request.dueAt?.toISOString() } : { ...(request.seekerId ? { seekerId: request.seekerId } : {}), ...(request.providerId ? { providerId: request.providerId } : {}) }), ...(request.propertyId ? { propertyId: request.propertyId } : {}), ...(request.projectId ? { projectId: request.projectId } : {}), status: request.status, payload: request.payload, ...(request.appointmentAt ? { appointmentAt: request.appointmentAt.toISOString(), appointmentTimezone: request.appointmentTimezone } : {}), version: request.version, availableActions: available(request.status, role), createdAt: request.createdAt.toISOString(), updatedAt: request.updatedAt.toISOString() }); }
function scopeFor(claims: AccessTokenClaims): { seekerId?: string; providerId?: string } | undefined { return claims.role === 'seeker' ? { seekerId: claims.sub } : claims.role === 'provider' ? { providerId: claims.sub } : undefined; }

export function createRequestService(dependencies: { repository: RequestRepository; now?: () => Date }) {
  const now = dependencies.now ?? (() => new Date());
  const contactAttempts = new Map<string, { startedAt: number; count: number }>();
  async function authorize(claims: AccessTokenClaims): Promise<void> { if (!active(claims)) throw new RequestServiceError('REQUEST_FORBIDDEN'); }
  async function create(claims: AccessTokenClaims, input: unknown): Promise<RequestData> { await authorize(claims); const parsed = requestCreateSchema.parse(input); if (parsed.type === 'provider_customer' && claims.role !== 'provider') throw new RequestServiceError('REQUEST_FORBIDDEN'); if (parsed.type !== 'provider_customer' && claims.role !== 'seeker') throw new RequestServiceError('REQUEST_FORBIDDEN'); const stamp = now(); const payload = parsed.payload as Record<string, unknown>; const request: RequestRecord = { id: id(), type: parsed.type, source: claims.role, creatorId: claims.sub, ...(claims.role === 'seeker' ? { seekerId: claims.sub } : { providerId: claims.sub }), ...(typeof payload.propertyId === 'string' ? { propertyId: payload.propertyId } : {}), ...(typeof payload.projectId === 'string' ? { projectId: payload.projectId } : {}), status: 'new', payload, dueAt: new Date(stamp.getTime() + 48 * 60 * 60 * 1000), version: 0, createdAt: stamp, updatedAt: stamp }; const result = await dependencies.repository.create(request); if (result.kind !== 'written') throw new RequestServiceError(result.kind === 'duplicate' ? 'REQUEST_DUPLICATE' : 'REQUEST_INVALID_STATE'); return project(result.request, claims.role); }
  async function list(claims: AccessTokenClaims, unparsed: unknown): Promise<RequestListData> { await authorize(claims); const query = requestListQuerySchema.parse(unparsed); const result = await dependencies.repository.list(query, scopeFor(claims)); return requestListDataSchema.parse({ items: result.items.map(item => project(item, claims.role)), page: query.page, limit: query.limit, total: result.total }); }
  async function overdue(claims: AccessTokenClaims, unparsed: unknown) { await authorize(claims); if (claims.role !== 'admin') throw new RequestServiceError('REQUEST_FORBIDDEN'); const query = requestListQuerySchema.parse(unparsed); const result = await dependencies.repository.list(query); const cutoff = now().getTime(); const items = result.items.filter(item => item.dueAt && item.dueAt.getTime() < cutoff && !['resolved', 'cancelled', 'closed'].includes(item.status)).map(item => ({ request: project(item, claims.role), overdueBySeconds: Math.floor((cutoff - (item.dueAt as Date).getTime()) / 1000) })); return overdueRequestListDataSchema.parse({ items, page: query.page, limit: query.limit, total: items.length }); }
  async function get(claims: AccessTokenClaims, requestId: string): Promise<RequestData> { await authorize(claims); const row = await dependencies.repository.get(requestId, scopeFor(claims)); if (!row) throw new RequestServiceError('REQUEST_NOT_FOUND'); return project(row, claims.role); }
  async function transition(claims: AccessTokenClaims, requestId: string, unparsed: unknown): Promise<RequestData> { await authorize(claims); const input = requestTransitionRequestSchema.parse(unparsed); const target: Record<RequestTransition, RequestStatus> = { start_review: 'under_review', contact: 'contacted', schedule: 'scheduled', needs_information: 'needs_information', start_progress: 'in_progress', resolve: 'resolved', cancel: 'cancelled', close: 'closed', reopen: 'under_review' }; const row = await dependencies.repository.get(requestId, scopeFor(claims)); if (!row) throw new RequestServiceError('REQUEST_NOT_FOUND'); if (!available(row.status, claims.role).includes(input.transition)) throw new RequestServiceError('REQUEST_INVALID_STATE'); const result = await dependencies.repository.transition({ id: row.id, expectedVersion: input.expectedVersion, status: target[input.transition], ...(input.reason ? { reason: input.reason } : {}), actorId: claims.sub, now: now() }); if (result.kind !== 'written') throw new RequestServiceError(result.kind === 'version_conflict' ? 'REQUEST_VERSION_CONFLICT' : result.kind === 'not_found' ? 'REQUEST_NOT_FOUND' : 'REQUEST_INVALID_STATE'); return project(result.request, claims.role); }
  async function assign(claims: AccessTokenClaims, requestId: string, unparsed: unknown): Promise<RequestData> { await authorize(claims); if (claims.role !== 'admin') throw new RequestServiceError('REQUEST_FORBIDDEN'); const input = requestAssignmentSchema.parse(unparsed); const row = await dependencies.repository.get(requestId); if (!row) throw new RequestServiceError('REQUEST_NOT_FOUND'); const result = await dependencies.repository.assign({ id: requestId, expectedVersion: input.expectedVersion, assigneeId: input.assigneeId, now: now() }); if (result.kind !== 'written') throw new RequestServiceError(result.kind === 'version_conflict' ? 'REQUEST_VERSION_CONFLICT' : 'REQUEST_NOT_FOUND'); return project(result.request, claims.role); }
  async function addNote(claims: AccessTokenClaims, requestId: string, unparsed: unknown): Promise<RequestData> { await authorize(claims); if (claims.role !== 'admin') throw new RequestServiceError('REQUEST_FORBIDDEN'); const input = requestNoteSchema.parse(unparsed); const row = await dependencies.repository.get(requestId); if (!row) throw new RequestServiceError('REQUEST_NOT_FOUND'); const result = await dependencies.repository.addNote({ id: requestId, expectedVersion: input.expectedVersion, note: { id: id(), body: input.body, authorId: claims.sub, createdAt: now() }, now: now() }); if (result.kind !== 'written') throw new RequestServiceError(result.kind === 'version_conflict' ? 'REQUEST_VERSION_CONFLICT' : 'REQUEST_NOT_FOUND'); return project(result.request, claims.role); }
  async function createContact(claims: AccessTokenClaims, input: unknown): Promise<{ status: RequestStatus }> { if (claims.role !== 'seeker') throw new RequestServiceError('REQUEST_FORBIDDEN'); const stamp = now().getTime(); const attempt = contactAttempts.get(claims.sub); if (attempt && stamp - attempt.startedAt < 60_000 && attempt.count >= 5) throw new RequestServiceError('REQUEST_RATE_LIMITED'); await create(claims, { type: 'contact', payload: input }); if (!attempt || stamp - attempt.startedAt >= 60_000) contactAttempts.set(claims.sub, { startedAt: stamp, count: 1 }); else contactAttempts.set(claims.sub, { startedAt: attempt.startedAt, count: attempt.count + 1 }); return { status: 'new' }; }
  return { create, createContact, list, overdue, get, transition, assign, addNote };
}

export function createInMemoryRequestRepository(seed: RequestRecord[] = []): RequestRepository {
  const rows = new Map(seed.map(row => [row.id, row]));
  const scoped = (row: RequestRecord, scope?: { seekerId?: string; providerId?: string }) => (!scope?.seekerId || row.seekerId === scope.seekerId) && (!scope?.providerId || row.providerId === scope.providerId);
  return {
    async create(request) { if ([...rows.values()].some(row => row.creatorId === request.creatorId && row.type === request.type && row.status === 'new' && JSON.stringify(row.payload) === JSON.stringify(request.payload))) return { kind: 'duplicate' }; rows.set(request.id, request); return { kind: 'written', request }; },
    async list(query, scope) { const values = [...rows.values()].filter(row => scoped(row, scope) && (!query.status || row.status === query.status) && (!query.type || row.type === query.type) && (!query.source || row.source === query.source)).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime() || b.id.localeCompare(a.id)); return { items: values.slice((query.page - 1) * query.limit, query.page * query.limit), total: values.length }; },
    async get(requestId, scope) { const row = rows.get(requestId); return row && scoped(row, scope) ? row : undefined; },
    async transition(input) { const row = rows.get(input.id); if (!row) return { kind: 'not_found' }; if (row.version !== input.expectedVersion) return { kind: 'version_conflict' }; if (row.status === input.status) return { kind: 'invalid_state' }; const updated = { ...row, status: input.status, version: row.version + 1, updatedAt: input.now }; rows.set(row.id, updated); return { kind: 'written', request: updated }; },
    async assign(input) { const row = rows.get(input.id); if (!row) return { kind: 'not_found' }; if (row.version !== input.expectedVersion) return { kind: 'version_conflict' }; const updated = { ...row, assignedTo: input.assigneeId, version: row.version + 1, updatedAt: input.now }; rows.set(row.id, updated); return { kind: 'written', request: updated }; },
    async addNote(input) { const row = rows.get(input.id); if (!row) return { kind: 'not_found' }; if (row.version !== input.expectedVersion) return { kind: 'version_conflict' }; const updated = { ...row, internalNotes: [...(row.internalNotes ?? []), input.note], version: row.version + 1, updatedAt: input.now }; rows.set(row.id, updated); return { kind: 'written', request: updated }; }
  };
}
