#!/usr/bin/env bash
set -Eeuo pipefail
umask 027

if [[ ${EUID} -ne 0 ]]; then
  echo 'Run this provisioning script as root.' >&2
  exit 1
fi

REPOSITORY_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
export DEBIAN_FRONTEND=noninteractive

if [[ ! -r /etc/os-release ]]; then
  echo 'Cannot identify the Ubuntu release from /etc/os-release.' >&2
  exit 1
fi
# shellcheck disable=SC1091
source /etc/os-release
case "${VERSION_ID:-}" in
  24.04) MONGO_REPO_CODENAME=noble ;;
  22.04) MONGO_REPO_CODENAME=jammy ;;
  *)
    echo "Unsupported Ubuntu release ${VERSION_ID:-unknown}. Use Ubuntu 24.04 LTS (recommended) or 22.04 LTS; MongoDB must not be installed from an LTS repository on a non-LTS kernel." >&2
    exit 1
    ;;
esac

# A previous interrupted run can leave a MongoDB source with a stale key. Remove
# only that repository before the first apt update; the key and source are rebuilt
# below with readable permissions.
rm -f /etc/apt/sources.list.d/mongodb-org-8.0.list
apt-get update
apt-get install -y ca-certificates curl gnupg nginx certbot python3-certbot-nginx \
  clamav clamav-daemon clamav-freshclam rsync jq ufw logrotate sudo

install -d -m 0755 /etc/apt/keyrings
MONGO_KEY_TMP=$(mktemp /tmp/elsadat-mongodb-key.XXXXXX.gpg)
curl --fail --silent --show-error --location \
  https://www.mongodb.org/static/pgp/server-8.0.asc \
  | gpg --batch --dearmor --yes --output "$MONGO_KEY_TMP"
# Apt invokes gpgv as `_apt`; an existing key generated by an interrupted run
# may be mode 0600 or plain ASCII and is then reported as NO_PUBKEY/unsupported.
# Validate the rebuilt key before exposing it to apt and make the ownership and
# mode explicit so a rerun is deterministic.
if ! gpg --batch --no-default-keyring --keyring "$MONGO_KEY_TMP" --list-keys >/dev/null 2>&1; then
  echo 'MongoDB signing key validation failed.' >&2
  rm -f "$MONGO_KEY_TMP"
  exit 1
fi
install -o root -g root -m 0644 "$MONGO_KEY_TMP" /etc/apt/keyrings/mongodb-server-8.0.gpg
rm -f "$MONGO_KEY_TMP"
echo "deb [arch=amd64,arm64 signed-by=/etc/apt/keyrings/mongodb-server-8.0.gpg] https://repo.mongodb.org/apt/ubuntu ${MONGO_REPO_CODENAME}/mongodb-org/8.0 multiverse" \
  > /etc/apt/sources.list.d/mongodb-org-8.0.list

if ! command -v node >/dev/null 2>&1 \
  || [[ $(node -p 'Number(process.versions.node.split(".")[0])') -lt 24 ]] \
  || [[ $(node -p 'Number(process.versions.node.split(".")[0])') -ge 25 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_24.x -o /tmp/elsadat-nodesource.sh
  bash /tmp/elsadat-nodesource.sh
  rm -f /tmp/elsadat-nodesource.sh
  apt-get install -y nodejs
fi

if ! command -v node >/dev/null 2>&1 \
  || [[ $(node -p 'Number(process.versions.node.split(".")[0])') -ne 24 ]]; then
  echo 'Node.js 24 is required by this release.' >&2
  exit 1
fi

apt-get update
apt-get install -y mongodb-org mongodb-database-tools

if ! id -u elsadat >/dev/null 2>&1; then
  useradd --system --create-home --home-dir /var/lib/elsadat --shell /bin/bash elsadat
fi
usermod --shell /bin/bash elsadat

install -d -o elsadat -g elsadat -m 0750 \
  /opt/elsadatrealestate \
  /opt/elsadatrealestate/releases \
  /opt/elsadatrealestate/staging \
  /var/lib/elsadatrealestate/private \
  /var/backups/elsadatrealestate \
  /var/log/elsadatrealestate
install -d -o root -g elsadat -m 0750 /etc/elsadatrealestate
install -d -o www-data -g www-data -m 0755 /var/www/letsencrypt
printf '%s\n' \
  'elsadat ALL=(root) NOPASSWD: /usr/bin/systemctl restart elsadat-api.service elsadat-web.service' \
  > /etc/sudoers.d/elsadat-deploy
chmod 0440 /etc/sudoers.d/elsadat-deploy
visudo -cf /etc/sudoers.d/elsadat-deploy

install -m 0644 "$REPOSITORY_ROOT/deploy/systemd/"*.service /etc/systemd/system/
install -m 0644 "$REPOSITORY_ROOT/deploy/systemd/"*.timer /etc/systemd/system/
install -d -m 0755 /etc/systemd/system/clamav-daemon.socket.d
install -m 0644 "$REPOSITORY_ROOT/deploy/clamav/elsadat-clamav.socket.conf" \
  /etc/systemd/system/clamav-daemon.socket.d/elsadat.conf
install -m 0644 "$REPOSITORY_ROOT/deploy/nginx/elsadatrealestate-http.conf" /etc/nginx/sites-available/elsadatrealestate.conf
ln -sfn /etc/nginx/sites-available/elsadatrealestate.conf /etc/nginx/sites-enabled/elsadatrealestate.conf
rm -f /etc/nginx/sites-enabled/default

sed -i -E 's/^(TCPSocket|TCPAddr|StreamMaxLength|MaxFileSize|MaxScanSize|ReadTimeout)[[:space:]]/# Native runtime replaced: /' /etc/clamav/clamd.conf
grep -Ev '^[[:space:]]*(#|$)' "$REPOSITORY_ROOT/deploy/clamav/elsadat-clamd.conf" >> /etc/clamav/clamd.conf

systemctl daemon-reload
systemctl enable mongod clamav-daemon clamav-freshclam nginx
systemctl restart clamav-daemon.socket clamav-daemon clamav-freshclam
nginx -t
systemctl restart nginx

ufw allow OpenSSH
ufw allow 'Nginx Full'

echo 'NATIVE_UBUNTU_PACKAGES_READY'
echo 'Next: install .env.production as root:elsadat mode 0640 at /etc/elsadatrealestate/production.env, then run configure-mongodb.sh.'
