import { randomBytes } from 'node:crypto';
import type { AccessTokenClaims } from '../auth/crypto.js';
import { communityCommentCreateSchema, communityCommentSchema, communityPostCreateSchema, communityPostPatchSchema, communityPostSchema, type CommunityComment, type CommunityPost } from '@sadat-real-estate/contracts';
const id = () => randomBytes(12).toString('hex'); const active = (claims: AccessTokenClaims) => claims.status === 'verified' && ['seeker', 'provider', 'admin'].includes(claims.role);
export function createCommunityService(seed: CommunityPost[] = []) { const posts = new Map(seed.map(post => [post.id, post])); const comments = new Map<string, CommunityComment>(); const now = () => new Date().toISOString(); return {
  async create(claims: AccessTokenClaims, input: unknown) { if (!active(claims)) throw new Error('FORBIDDEN'); const parsed = communityPostCreateSchema.parse(input); const stamp = now(); const post = communityPostSchema.parse({ id: id(), authorId: claims.sub, ...parsed, status: 'draft', createdAt: stamp, updatedAt: stamp }); posts.set(post.id, post); return post; },
  async listOwned(claims: AccessTokenClaims) { if (!active(claims)) throw new Error('FORBIDDEN'); return [...posts.values()].filter(post => post.authorId === claims.sub); },
  async update(claims: AccessTokenClaims, postId: string, input: unknown) { const post = posts.get(postId); if (!post || post.authorId !== claims.sub) throw new Error('NOT_FOUND'); const updated = communityPostSchema.parse({ ...post, ...communityPostPatchSchema.parse(input), updatedAt: now() }); posts.set(post.id, updated); return updated; },
  async remove(claims: AccessTokenClaims, postId: string) { const post = posts.get(postId); if (!post || post.authorId !== claims.sub) throw new Error('NOT_FOUND'); const updated = { ...post, status: 'removed' as const, updatedAt: now() }; posts.set(post.id, updated); return updated; },
  async publish(claims: AccessTokenClaims, postId: string) { if (claims.role !== 'admin') throw new Error('FORBIDDEN'); const post = posts.get(postId); if (!post) throw new Error('NOT_FOUND'); const updated = { ...post, status: 'published' as const, updatedAt: now() }; posts.set(post.id, updated); return updated; },
  async createComment(claims: AccessTokenClaims, input: unknown) { if (!active(claims)) throw new Error('FORBIDDEN'); const parsed = communityCommentCreateSchema.parse(input); const post = posts.get(parsed.postId); if (!post || post.status !== 'published') throw new Error('INVALID_STATE'); const depth = parsed.parentId ? (comments.get(parsed.parentId)?.depth ?? 0) + 1 : 0; if (depth > 2) throw new Error('INVALID_STATE'); const comment = communityCommentSchema.parse({ id: id(), ...parsed, authorId: claims.sub, depth, status: 'visible', createdAt: now() }); comments.set(comment.id, comment); return comment; },
  async listComments(postId: string) { return [...comments.values()].filter(comment => comment.postId === postId && comment.status === 'visible').sort((a, b) => a.createdAt.localeCompare(b.createdAt)); },
  async removeComment(claims: AccessTokenClaims, commentId: string) { const comment = comments.get(commentId); if (!comment || (comment.authorId !== claims.sub && claims.role !== 'admin')) throw new Error('NOT_FOUND'); const updated = { ...comment, status: 'removed' as const }; comments.set(comment.id, updated); return updated; },
  async publicList() { return [...posts.values()].filter(post => post.status === 'published').sort((a, b) => b.createdAt.localeCompare(a.createdAt)); },
  async publicFeed() { return (await this.publicList()).map(post => ({ post, comments: [...comments.values()].filter(comment => comment.postId === post.id && comment.status === 'visible') })); }
}; }
