import { randomBytes } from 'node:crypto';
import type { AccessTokenClaims } from '../auth/crypto.js';
import { articleCategoryCreateSchema, articleCategoryPatchSchema, articleCategorySchema, articleCreateSchema, articleListQuerySchema, articlePatchSchema, articlePublicSchema, articleSchema, type Article, type ArticleCategory, type ArticlePublic } from '@sadat-real-estate/contracts';
const id = () => randomBytes(12).toString('hex'); const localeValue = (text: Partial<Record<string, string>>, locale: string) => text[locale] ?? text.ar ?? text.en ?? text['zh-CN'] ?? '';
export function createArticleService(seed: { categories?: ArticleCategory[]; articles?: Article[] } = {}) {
  const categories = new Map((seed.categories ?? []).map(item => [item.id, item])); const articles = new Map((seed.articles ?? []).map(item => [item.id, item]));
  const admin = (claims: AccessTokenClaims) => { if (claims.role !== 'admin' || claims.status !== 'verified') throw new Error('FORBIDDEN'); };
  return {
    async createCategory(claims: AccessTokenClaims, input: unknown) { admin(claims); const parsed = articleCategoryCreateSchema.parse(input); if ([...categories.values()].some(item => item.slug === parsed.slug)) throw new Error('DUPLICATE'); const item = articleCategorySchema.parse({ id: id(), ...parsed }); categories.set(item.id, item); return item; },
    async updateCategory(claims: AccessTokenClaims, categoryId: string, input: unknown) { admin(claims); const current = categories.get(categoryId); if (!current) throw new Error('NOT_FOUND'); const item = articleCategorySchema.parse({ ...current, ...articleCategoryPatchSchema.parse(input) }); categories.set(item.id, item); return item; },
    async listCategories(claims: AccessTokenClaims) { admin(claims); return [...categories.values()].sort((a, b) => a.displayOrder - b.displayOrder || a.id.localeCompare(b.id)); },
    async createArticle(claims: AccessTokenClaims, input: unknown): Promise<Article> { admin(claims); const parsed = articleCreateSchema.parse(input); if (!categories.has(parsed.categoryId)) throw new Error('NOT_FOUND'); const item = articleSchema.parse({ id: id(), ...parsed, status: 'draft', updatedAt: new Date().toISOString() }); articles.set(item.id, item); return item; },
    async updateArticle(claims: AccessTokenClaims, articleId: string, input: unknown) { admin(claims); const current = articles.get(articleId); if (!current) throw new Error('NOT_FOUND'); const item = articleSchema.parse({ ...current, ...articlePatchSchema.parse(input), updatedAt: new Date().toISOString() }); articles.set(item.id, item); return item; },
    async transitionArticle(claims: AccessTokenClaims, articleId: string, status: Article['status']) { admin(claims); const current = articles.get(articleId); if (!current) throw new Error('NOT_FOUND'); const allowed: Record<Article['status'], Article['status'][]> = { draft: ['pending_review'], pending_review: ['published', 'draft'], published: ['archived'], archived: ['draft'] }; if (!allowed[current.status].includes(status)) throw new Error('INVALID_STATE'); const item = articleSchema.parse({ ...current, status, ...(status === 'published' ? { publishedAt: new Date().toISOString() } : {}), updatedAt: new Date().toISOString() }); articles.set(item.id, item); return item; },
    async listPublic(input: unknown): Promise<ArticlePublic[]> { const query = articleListQuerySchema.parse(input); return [...articles.values()].filter(item => item.status === 'published' && (!query.categoryId || item.categoryId === query.categoryId)).sort((a, b) => (b.publishedAt ?? '').localeCompare(a.publishedAt ?? '') || a.id.localeCompare(b.id)).slice((query.page - 1) * query.limit, query.page * query.limit).map(item => articlePublicSchema.parse({ id: item.id, categoryId: item.categoryId, slug: item.slug, title: { [query.locale]: localeValue(item.title, query.locale) }, body: { [query.locale]: localeValue(item.body, query.locale) }, ...(item.seoTitle ? { seoTitle: { [query.locale]: localeValue(item.seoTitle, query.locale) } } : {}), ...(item.seoDescription ? { seoDescription: { [query.locale]: localeValue(item.seoDescription, query.locale) } } : {}), ...(item.coverAssetId ? { coverAssetId: item.coverAssetId } : {}), publishedAt: item.publishedAt })); },
    async getPublicBySlug(slug: string, locale: 'ar' | 'en' | 'zh-CN' = 'ar') { const item = [...articles.values()].find(row => row.slug === slug && row.status === 'published'); if (!item) throw new Error('NOT_FOUND'); return articlePublicSchema.parse({ id: item.id, categoryId: item.categoryId, slug: item.slug, title: { [locale]: localeValue(item.title, locale) }, body: { [locale]: localeValue(item.body, locale) }, ...(item.seoTitle ? { seoTitle: { [locale]: localeValue(item.seoTitle, locale) } } : {}), ...(item.seoDescription ? { seoDescription: { [locale]: localeValue(item.seoDescription, locale) } } : {}), ...(item.coverAssetId ? { coverAssetId: item.coverAssetId } : {}), publishedAt: item.publishedAt }); }
  };
}
