import { AdPlacementGuide } from '../admin_ads/placement-guide.tsx';
import { z } from 'zod';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { featuredOptionsSuccessEnvelopeSchema, type AdBanner, type AdAdminRequest, type FeaturedOptions, type LocalizedText, type SupportedLocale, type PublicHomepageBanner } from '@sadat-real-estate/contracts';
import { ApiClient, ApiClientError } from '../contracts/index.ts';
import { AdminNavigation } from '../admin/index.ts';
import { Button } from '../design_system/index.ts';
import type { RouteSession } from '../routing/index.ts';
import { createAdminHomeSource, type AdminHomeSource, type AdminHomeAuthorizationSource } from '../admin_home/data.ts';
import { FeaturedCard, featuredText } from '../public/featured-card.tsx';
import { egyptInstant, egyptLocalDateTime } from '../public/egypt-time.ts';
import '../admin_home/styles.css';
import './styles.css';

const dateLabel = (value: string, locale: SupportedLocale) => new Intl.DateTimeFormat(locale, { timeZone: 'Africa/Cairo', dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));
const placementKey = 'homepage.featured';
const cleanText = (value: LocalizedText): LocalizedText | undefined => { const entries = Object.entries(value).filter(([, text]) => text?.trim()).map(([locale, text]) => [locale, text?.trim()]); return entries.length ? Object.fromEntries(entries) : undefined; };
const failure = (error: unknown, ar: boolean) => error instanceof ApiClientError && error.status === 409 ? ar ? 'تغير السجل أثناء التعديل. مدخلاتك محفوظة؛ أغلق النموذج وأعد تحميل السجل قبل المحاولة.' : 'The record changed. Your inputs are kept; reload the saved record before retrying.' : ar ? 'تعذر الحفظ. مدخلاتك والصورة المختارة محفوظة؛ راجع البيانات وحاول مرة أخرى.' : 'Could not save. Your inputs and selected image are kept; check and retry.';
function TextFields({ label, value, set, multiline = false }: { label: string; value: LocalizedText; set: (value: LocalizedText) => void; multiline?: boolean }) {
  return <fieldset className="admin-featured__texts"><legend>{label}</legend>{(['ar', 'en'] as const).map(lang => <label key={lang}>{lang === 'ar' ? 'العربية' : 'English'}{multiline ? <textarea dir={lang === 'ar' ? 'rtl' : 'ltr'} value={value[lang] ?? ''} maxLength={2000} onChange={event => set({ ...value, [lang]: event.target.value })} /> : <input dir={lang === 'ar' ? 'rtl' : 'ltr'} value={value[lang] ?? ''} maxLength={500} onChange={event => set({ ...value, [lang]: event.target.value })} />}</label>)}</fieldset>;
}

export function FeaturedEditor({ item, campaign, options, loadOptions, source, locale, onSaved, onClose }: { item?: AdBanner | undefined; campaign?: AdAdminRequest['request'] | undefined; options: FeaturedOptions; loadOptions: (id?: string) => Promise<FeaturedOptions>; source: AdminHomeSource; locale: SupportedLocale; onSaved: () => void; onClose: () => void }) {
  const ar = locale === 'ar';
  const [saved, setSaved] = useState(item);
  const [provider, setProvider] = useState(item?.featured?.advertiserProviderId ?? campaign?.providerId ?? '');
  const [destinations, setDestinations] = useState<FeaturedOptions['destinations']>([]);
  const [destination, setDestination] = useState(item?.featured?.destination ? `${item.featured.destination.kind}:${item.featured.destination.id}` : '');
  const [title, setTitle] = useState<LocalizedText>(item?.title ?? {}), [body, setBody] = useState<LocalizedText>(item?.body ?? {}), [highlight, setHighlight] = useState<LocalizedText>(item?.featured?.highlight ?? {}), [installment, setInstallment] = useState<LocalizedText>(item?.featured?.installment ?? {}), [ctaLabel, setCtaLabel] = useState<LocalizedText>(item?.featured?.ctaLabel ?? {});
  const [start, setStart] = useState(egyptLocalDateTime(new Date(item?.startAt ?? campaign?.intervalStart ?? Date.now()))), [end, setEnd] = useState(egyptLocalDateTime(new Date(item?.endAt ?? campaign?.intervalEnd ?? Date.now() + 86400000 * 30)));
  const [seconds, setSeconds] = useState(item?.displaySeconds ?? 6);
  const [imageIds, setImageIds] = useState<string[]>(item?.mediaIds ?? (item?.mediaId ? [item.mediaId] : []));
  const [image, setImage] = useState<string>(), [file, setFile] = useState<File>(), [filePreview, setFilePreview] = useState<string>();
  const [busy, setBusy] = useState(false), [error, setError] = useState<string>(), [feedback, setFeedback] = useState<string>(), [previewSize, setPreviewSize] = useState<'desktop' | 'mobile'>('desktop');
  useEffect(() => { let current = true; if (!provider) { setDestinations([]); return; } void loadOptions(provider).then(value => { if (current) setDestinations(value.destinations); }).catch(() => { if (current) { setDestinations([]); setError(ar ? 'الحساب غير متاح للإعلان. اختر حسابًا معتمدًا ومسموحًا له بالظهور.' : 'Choose an approved advertiser eligible for public display.'); } }); return () => { current = false; }; }, [provider, loadOptions, ar]);
  useEffect(() => { if (!file) { setFilePreview(undefined); return; } const url = URL.createObjectURL(file); setFilePreview(url); return () => URL.revokeObjectURL(url); }, [file]);
  useEffect(() => { let current = true; const urls: string[] = []; if (item) void source.previewBanner(item.id).then(async value => { if (value.media) { const url = await source.loadMediaPreview(value.media.url); if (url.startsWith('blob:')) urls.push(url); if (current) setImage(url); } }).catch(() => { if (current) setError(ar ? 'تعذر تحميل صورة المعاينة.' : 'Could not load the preview image.'); }); return () => { current = false; urls.forEach(url => URL.revokeObjectURL(url)); }; }, [item, source, ar]);
  const advertiser = options.advertisers.find(value => value.id === provider);
  const selected = destinations.find(value => `${value.kind}:${value.id}` === destination);
  const preview: PublicHomepageBanner = { key: 'featured_preview', presentation: 'featured', title: cleanText(title), body: cleanText(body), highlight: cleanText(highlight), installment: cleanText(installment), ctaLabel: cleanText(ctaLabel), imageUrl: filePreview ?? image, targetUrl: selected?.href, advertiserName: advertiser?.name, advertiserImageUrl: advertiser?.imageUrl, advertiserVerified: advertiser?.verified ?? false, order: saved?.sortOrder ?? 0 };
  async function save(publish: boolean, event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(undefined); setFeedback(undefined);
    const parsedTitle = cleanText(title), startAt = egyptInstant(start), endAt = egyptInstant(end);
    if (!advertiser || !selected || !parsedTitle || !startAt || !endAt || endAt <= startAt || publish && endAt.getTime() <= Date.now() || seconds < 3 || seconds > 60 || publish && !file && !imageIds.length) { setError(ar ? 'اختر المعلن والصفحة والصورة، وأدخل عنوانًا ومواعيد صحيحة. مدة الكارت من 3 إلى 60 ثانية.' : 'Choose an advertiser, page and image, and enter a title and valid dates. Slide duration is 3–60 seconds.'); return; }
    const fields = { placementKey, title: parsedTitle, body: cleanText(body), featured: { advertiserProviderId: provider, destination: { kind: selected.kind, id: selected.id }, highlight: cleanText(highlight), installment: cleanText(installment), ctaLabel: cleanText(ctaLabel), ...(saved?.featured?.eyebrow ? { eyebrow: saved.featured.eyebrow } : {}) }, startAt: startAt.toISOString(), endAt: endAt.toISOString(), displaySeconds: seconds };
    setBusy(true);
    try {
      let record = saved ? await source.updateBanner(saved.id, { ...fields, body: fields.body ?? null, status: 'draft', expectedVersion: saved.version, reason: 'Save featured homepage card' }) : await source.createBanner({ ...fields, ...(campaign ? { adRequestId: campaign.id } : {}) });
      setSaved(record);
      let selectedIds = imageIds;
      if (file) { const media = await source.uploadBannerImage(record.id, file); selectedIds = [media.id]; setImageIds(selectedIds); setFile(undefined); try { const url = await source.loadMediaPreview(media.url); setImage(url); } catch { setImage(undefined); /* Saving does not depend on preview delivery. */ } }
      record = await source.updateBanner(record.id, { mediaIds: selectedIds, expectedVersion: record.version, reason: 'Save featured card image' }); setSaved(record);
      if (publish) { record = await source.updateBanner(record.id, { status: new Date(record.startAt).getTime() > Date.now() ? 'scheduled' : 'active', expectedVersion: record.version, reason: 'Publish saved featured homepage card' }); setSaved(record); }
      setFeedback(ar ? publish ? 'تم حفظ كل التعديلات والصورة ونشر الإعلان حسب موعده.' : 'تم حفظ المسودة.' : publish ? 'All changes and the image were saved; the ad is published for its schedule.' : 'Draft saved.'); onSaved();
    } catch (cause) { setError(failure(cause, ar)); } finally { setBusy(false); }
  }
  return <section className="admin-home__editor" aria-label={ar ? 'تعديل الإعلان المميز' : 'Featured ad editor'}><div className="admin-home__editor-heading"><h2>{ar ? 'محتوى الكارت المميز' : 'Featured card content'}</h2><Button variant="secondary" disabled={busy} onClick={onClose}>{ar ? 'إغلاق' : 'Close'}</Button></div>
    <AdPlacementGuide placementKey={placementKey} locale={locale} /><form onSubmit={event => void save(false, event)}><fieldset disabled={busy || !options.canManage} className="admin-featured__fields"><label>{ar ? 'المعلن من حسابات المنصة' : 'Advertiser account'}<select value={provider} required disabled={!!campaign} onChange={event => { setProvider(event.target.value); setDestination(''); }}><option value="">{ar ? 'اختر الحساب' : 'Choose an account'}</option>{options.advertisers.map(value => <option key={value.id} value={value.id}>{featuredText(value.name, locale)}</option>)}</select></label><p>{ar ? 'الاسم والصورة من حساب المعلن. المكتب غير المشترك غير متاح للاختيار؛ الاشتراك لا يكشف بيانات العملاء.' : 'Name and image come from the account. Hidden offices cannot be selected; subscriptions never reveal customer data.'}</p>
      <label>{ar ? 'وجهة الزر — صفحة منشورة للمعلن' : 'Button destination — advertiser’s published page'}<select required value={destination} onChange={event => setDestination(event.target.value)}><option value="">{ar ? 'اختر الصفحة' : 'Choose a page'}</option>{destinations.map(value => <option key={`${value.kind}:${value.id}`} value={`${value.kind}:${value.id}`}>{featuredText(value.name, locale)}</option>)}</select></label>
      <label>{ar ? 'صورة الإعلان' : 'Ad image'}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => setFile(event.target.files?.[0])} /></label>
      <TextFields label={ar ? 'العنوان' : 'Title'} value={title} set={setTitle} /><TextFields label={ar ? 'الوصف' : 'Description'} value={body} set={setBody} multiline /><TextFields label={ar ? 'السطر الأصفر البارز' : 'Highlighted line'} value={highlight} set={setHighlight} /><TextFields label={ar ? 'نص التقسيط' : 'Payment plan text'} value={installment} set={setInstallment} /><TextFields label={ar ? 'نص الزر' : 'Button label'} value={ctaLabel} set={setCtaLabel} />
      <div className="admin-home__form-grid"><label>{ar ? 'بداية العرض — توقيت مصر' : 'Starts — Egypt time'}<input type="datetime-local" required disabled={!!campaign} value={start} onChange={event => setStart(event.target.value)} /></label><label>{ar ? 'نهاية العرض — توقيت مصر' : 'Ends — Egypt time'}<input type="datetime-local" required disabled={!!campaign} value={end} onChange={event => setEnd(event.target.value)} /></label><label>{ar ? 'مدة ظهور الكارت بالثواني' : 'Seconds per slide'}<input type="number" min="3" max="60" value={seconds} onChange={event => setSeconds(Number(event.target.value))} required /></label></div>
      {campaign ? <p>{ar ? 'هذا الإعلان مرتبط بطلب العميل. النشر يتطلب اعتماد الدفع والجدولة.' : 'This ad belongs to a customer request. Approved payment and scheduling are required to publish.'}</p> : null}
      <div className="admin-home__inline-actions"><Button type="submit" disabled={busy}>{ar ? 'حفظ مسودة' : 'Save draft'}</Button><Button type="submit" disabled={busy} formAction="" onClick={event => { event.preventDefault(); const form = event.currentTarget.form; if (form?.reportValidity()) void save(true, { preventDefault() {} } as FormEvent<HTMLFormElement>); }}>{ar ? 'حفظ ونشر' : 'Save and publish'}</Button></div>
    </fieldset></form>{error ? <p role="alert">{error}</p> : null}{feedback ? <p role="status">{feedback}</p> : null}
    <div className="admin-home__inline-actions"><h3>{ar ? 'معاينة مباشرة' : 'Live preview'}</h3><Button variant="secondary" onClick={() => setPreviewSize('desktop')}>{ar ? 'كمبيوتر' : 'Desktop'}</Button><Button variant="secondary" onClick={() => setPreviewSize('mobile')}>{ar ? 'موبايل' : 'Mobile'}</Button></div><div className="admin-featured__preview public-homepage__section--banners" data-size={previewSize}><div className="public-homepage__banner-card"><FeaturedCard banner={preview} locale={locale} preview /></div></div>
  </section>;
}

export function AdminFeatured({ locale, session, authClient, apiOrigin, url }: { locale: SupportedLocale; session: RouteSession; authClient?: AdminHomeAuthorizationSource | undefined; apiOrigin?: string | undefined; url?: string | undefined }) {
  const ar = locale === 'ar';
  const source = useMemo(() => createAdminHomeSource({ authorization: authClient, apiOrigin }), [authClient, apiOrigin]);
  const client = useMemo(() => new ApiClient(apiOrigin ? { baseUrl: apiOrigin } : {}), [apiOrigin]);
  const access = useMemo(() => ({ headers: { authorization: authClient?.getAuthorizationHeader() ?? '' } }), [authClient]);
  const loadOptions = useMemo(() => async (id?: string) => (await client.request('/admin/banners/featured-options', { responseSchema: featuredOptionsSuccessEnvelopeSchema, ...(id ? { query: { providerId: id } } : {}), ...access })).data.data, [client, access]);
  const [items, setItems] = useState<AdBanner[]>([]), [options, setOptions] = useState<FeaturedOptions>({ advertisers: [], destinations: [], canManage: false }), [editing, setEditing] = useState<AdBanner | 'new'>(), [error, setError] = useState<string>(), [busy, setBusy] = useState(false), [attempt, setAttempt] = useState(0), [campaign, setCampaign] = useState<AdAdminRequest['request']>(), [page, setPage] = useState(1), [total, setTotal] = useState(0);
  const requestId = new URL(url ?? 'http://localhost/admin/ads/featured', 'http://localhost').searchParams.get('requestId');
  useEffect(() => { if (session.status !== 'authenticated' || session.role !== 'admin') { setError(ar ? 'يلزم تسجيل دخول إداري.' : 'An administrator session is required.'); return; } const controller = new AbortController(); setBusy(true); void Promise.all([source.loadBanners({ placementKey, page, limit: 100 }, controller.signal), loadOptions(), requestId ? source.loadAdRequest(requestId, controller.signal) : Promise.resolve(undefined)]).then(([list, choices, request]) => { if (controller.signal.aborted) return; setItems(list.items); setTotal(list.total); setOptions(choices); setCampaign(request?.request); if (request && request.request.placementKey === placementKey) setEditing(list.items.find(item => item.adRequestId === request.request.id) ?? 'new'); setError(undefined); }).catch(cause => { if (!controller.signal.aborted) setError(failure(cause, ar)); }).finally(() => { if (!controller.signal.aborted) setBusy(false); }); return () => controller.abort(); }, [session.status, session.status === 'authenticated' ? session.role : undefined, source, loadOptions, requestId, attempt, page, ar]);
  const refresh = () => setAttempt(value => value + 1);
  async function setup() { setBusy(true); try { const config = await source.loadBannerConfig(); await source.updateBannerConfig({ enabled: true, expectedVersion: config.version, reason: 'Enable featured homepage advertisement placement' }); refresh(); } catch (cause) { setError(failure(cause, ar)); } finally { setBusy(false); } }
  async function stop(item: AdBanner) { setBusy(true); try { await source.updateBanner(item.id, { status: 'draft', expectedVersion: item.version, reason: 'Stop featured homepage card' }); refresh(); } catch (cause) { setError(failure(cause, ar)); } finally { setBusy(false); } }
  async function move(index: number, offset: number) { const next = [...items], other = index + offset; if (!next[index] || !next[other]) return; [next[index], next[other]] = [next[other]!, next[index]!]; setBusy(true); try { await source.reorderBanners({ placementKey, items: next.map((item, position) => ({ bannerId: item.id, sortOrder: items[position]!.sortOrder, expectedVersion: item.version })), reason: 'Reorder featured homepage cards' }); refresh(); } catch (cause) { setError(failure(cause, ar)); } finally { setBusy(false); } }
  async function importOld() { setBusy(true); try { await client.request('/admin/banners/featured-import', { method: 'POST', json: {}, responseSchema: z.object({ data: z.object({ imported: z.boolean() }) }).passthrough(), ...access }); refresh(); } catch (cause) { setError(failure(cause, ar)); } finally { setBusy(false); } }
  return <section className="admin-home" dir={ar ? 'rtl' : 'ltr'}><AdminNavigation locale={locale} activePath="/admin/ads/featured" /><div className="admin-home__content"><header className="admin-home__heading"><div><h1>{ar ? 'إعلانات الرئيسية المميزة' : 'Featured homepage ads'}</h1><p>{ar ? 'كروت بصور ونصوص كاملة تتبادل العرض أسفل أعلى الرئيسية.' : 'Complete image and text cards rotating below the homepage hero.'}</p></div><Button disabled={busy || !options.canManage} onClick={() => setEditing('new')}>{ar ? 'إضافة إعلان مميز' : 'Add featured ad'}</Button></header><nav className="admin-home__tabs"><a href={`/admin/ads/requests?lang=${locale}`}>{ar ? 'طلبات الإعلانات' : 'Ad requests'}</a><a href={`/admin/banners?lang=${locale}`}>{ar ? 'بانرات أعلى الصفحة' : 'Homepage hero banners'}</a></nav><div className="admin-home__inline-actions"><Button variant="secondary" disabled={busy || !options.canManage} onClick={() => void setup()}>{ar ? 'تشغيل عرض الإعلانات وتجهيز القسم' : 'Enable display and set up placement'}</Button><Button variant="secondary" disabled={busy || !options.canManage} onClick={() => void importOld()}>{ar ? 'نقل الكروت القديمة للمراجعة' : 'Import legacy cards for review'}</Button></div>{error ? <p role="alert">{error}<Button variant="secondary" onClick={refresh}>{ar ? 'إعادة المحاولة' : 'Retry'}</Button></p> : null}{busy ? <p role="status">{ar ? 'جارٍ التنفيذ…' : 'Working…'}</p> : null}{editing ? <FeaturedEditor key={editing === 'new' ? 'new' : editing.id} {...(editing === 'new' ? { campaign } : { item: editing })} options={options} loadOptions={loadOptions} source={source} locale={locale} onSaved={refresh} onClose={() => setEditing(undefined)} /> : null}
    <section className="admin-home__panel"><h2>{ar ? 'الإعلانات ومواعيدها' : 'Ads and schedules'}</h2>{items.length === 0 ? <p>{ar ? 'لا توجد كروت محفوظة. أضف إعلانًا أو انقل السجلات القديمة للمراجعة.' : 'No saved cards. Add an ad or import legacy records for review.'}</p> : null}<div className="admin-home__table-wrap"><table className="admin-home__table"><thead><tr>{(ar ? ['الإعلان', 'الحالة', 'البداية', 'النهاية', 'الإجراءات'] : ['Ad', 'Status', 'Starts', 'Ends', 'Actions']).map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item, index) => <FeaturedRow key={item.id} item={item} index={index} count={items.length} locale={locale} source={source} disabled={busy || !options.canManage} onEdit={() => setEditing(item)} onStop={() => void stop(item)} onMove={offset => void move(index, offset)} />)}</tbody></table></div><div className="admin-home__inline-actions"><Button disabled={page <= 1 || busy} onClick={() => setPage(value => value - 1)}>{ar ? 'السابق' : 'Previous'}</Button><span>{page} / {Math.max(1, Math.ceil(total / 100))}</span><Button disabled={page * 100 >= total || busy} onClick={() => setPage(value => value + 1)}>{ar ? 'التالي' : 'Next'}</Button></div></section></div></section>;
}
function FeaturedRow({ item, index, count, locale, source, disabled, onEdit, onStop, onMove }: { item: AdBanner; index: number; count: number; locale: SupportedLocale; source: AdminHomeSource; disabled: boolean; onEdit: () => void; onStop: () => void; onMove: (offset: number) => void }) {
  const [image, setImage] = useState<string>();
  useEffect(() => { let current = true, objectUrl: string | undefined; void source.previewBanner(item.id).then(async preview => { if (!preview.media) return; const url = await source.loadMediaPreview(preview.media.url); if (url.startsWith('blob:')) objectUrl = url; if (current) setImage(url); }).catch(() => {}); return () => { current = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [source, item.id, item.version]);
  const ar = locale === 'ar', states = ar ? { draft: 'مسودة', scheduled: 'مجدول', active: 'منشور', paused: 'موقوف', ended: 'انتهى', archived: 'مؤرشف' } : { draft: 'Draft', scheduled: 'Scheduled', active: 'Published', paused: 'Stopped', ended: 'Ended', archived: 'Archived' };
  return <tr><td>{image ? <img className="admin-featured__thumbnail" src={image} alt="" /> : null}<strong>{featuredText(item.title, locale)}</strong>{!item.featured?.advertiserProviderId ? <small>{ar ? 'غير مرتبط — عارض مبهم حتى تختار الحساب' : 'Unlinked — anonymous until an account is selected'}</small> : null}</td><td>{new Date(item.endAt).getTime() <= Date.now() && ['active', 'scheduled'].includes(item.status) ? states.ended : states[item.status]}</td><td>{dateLabel(item.startAt, locale)}</td><td>{dateLabel(item.endAt, locale)}</td><td><div className="admin-home__row-actions"><Button disabled={disabled} onClick={onEdit}>{ar ? 'تعديل' : 'Edit'}</Button><Button variant="secondary" onClick={onEdit}>{ar ? 'معاينة' : 'Preview'}</Button>{['active', 'scheduled'].includes(item.status) ? <Button variant="secondary" disabled={disabled} onClick={onStop}>{ar ? 'إيقاف' : 'Stop'}</Button> : null}<Button variant="secondary" disabled={disabled || index === 0} onClick={() => onMove(-1)}>↑</Button><Button variant="secondary" disabled={disabled || index === count - 1} onClick={() => onMove(1)}>↓</Button></div></td></tr>;
}
