export const DESIGN_TOKENS = Object.freeze({
  color: Object.freeze({
    brandPrimary: '#0F4A3B',
    brandSecondary: '#17233D',
    brandAccent: '#D1A044',
    pageBackground: '#FAF8F2',
    surface: '#FFFFFF',
    surfaceSoft: '#F3E8D0',
    text: '#17233D',
    textStrong: '#17233D',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    brand: '#0F4A3B',
    brandInteractive: '#17233D',
    brandSoft: '#F3E8D0',
    accentText: '#D1A044',
    border: '#E8E1D2',
    borderStrong: '#D6C8A8',
    info: '#38BDF8',
    success: '#22C55E',
    warning: '#F59E0B',
    error: '#EF4444',
    borderInfo: '#38BDF8',
    borderCritical: '#EF4444',
    onBrand: '#FFFFFF',
    focus: '#D1A044'
  }),
  typography: Object.freeze({
    fontFamily: Object.freeze({
      sans: 'Cairo, "Noto Sans SC", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'
    }),
    fontSize: Object.freeze({
      caption: '0.75rem',
      small: '0.875rem',
      body: '1rem',
      bodyLarge: '1.125rem',
      sectionTitle: '1.25rem',
      headingTwo: '1.875rem',
      headingOne: '2.25rem',
      display: '3rem',
      displayMin: '2.25rem',
      displayPreferred: '5vw',
      displayMax: '3rem'
    }),
    lineHeight: Object.freeze({ body: '1.7', heading: '1.3', display: '1.2' }),
    weight: Object.freeze({ regular: '400', medium: '500', semibold: '600', bold: '700', extrabold: '800', strong: '700' }),
    tracking: Object.freeze({ label: '0' })
  }),
  spacing: Object.freeze({
    none: '0',
    xs: '0.25rem',
    sm: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    '2xl': '2rem',
    '2.5xl': '2.5rem',
    '3xl': '3rem',
    '4xl': '4rem'
  }),
  radius: Object.freeze({ sm: '0.5rem', md: '0.75rem', lg: '1rem', xl: '1.5rem', full: '9999px' }),
  shadow: Object.freeze({
    sm: '0 1px 2px 0 rgb(23 35 61 / 0.05)',
    card: '0 1px 3px 0 rgb(23 35 61 / 0.1), 0 1px 2px -1px rgb(23 35 61 / 0.1)',
    dropdown: '0 10px 15px -3px rgb(23 35 61 / 0.1), 0 4px 6px -4px rgb(23 35 61 / 0.1)',
    modal: '0 25px 50px -12px rgb(23 35 61 / 0.25)',
    sticky: '0 20px 25px -5px rgb(23 35 61 / 0.1), 0 8px 10px -6px rgb(23 35 61 / 0.1)',
    header: '0 1px 2px 0 rgb(23 35 61 / 0.05)',
    state: '0 1px 3px 0 rgb(23 35 61 / 0.1), 0 1px 2px -1px rgb(23 35 61 / 0.1)'
  }),
  component: Object.freeze({
    buttonHeightXs: '1.75rem',
    buttonHeightSm: '2rem',
    buttonHeightMd: '2.5rem',
    buttonHeightLg: '3rem',
    inputHeight: '2.5rem',
    headerHeightMin: '3.5rem',
    headerHeightMax: '4rem',
    sidebarWidth: '15rem',
    modalMaxWidthMin: '30rem',
    modalMaxWidthMax: '37.5rem'
  }),
  asset: Object.freeze({ logoMaxInlineSize: '4rem', logoMaxBlockSize: '3.5rem' })
} as const);

export const DESIGN_TOKEN_CSS_VARIABLES = Object.freeze({
  brandPrimary: '--color-brand-primary',
  brandSecondary: '--color-brand-secondary',
  brandAccent: '--color-brand-accent',
  pageBackground: '--color-page-background',
  surface: '--color-surface',
  surfaceSoft: '--color-surface-soft',
  text: '--color-text',
  textStrong: '--color-text-strong',
  textSecondary: '--color-text-secondary',
  textMuted: '--color-text-muted',
  brand: '--color-brand',
  brandInteractive: '--color-brand-interactive',
  brandSoft: '--color-brand-soft',
  accentText: '--color-accent-text',
  border: '--color-border',
  borderStrong: '--color-border-strong',
  info: '--color-status-info',
  success: '--color-status-success',
  warning: '--color-status-warning',
  error: '--color-status-error',
  borderInfo: '--color-border-info',
  borderCritical: '--color-border-critical',
  onBrand: '--color-on-brand',
  focus: '--color-focus',
  fontFamilySans: '--font-family-sans',
  fontSizeCaption: '--font-size-caption',
  fontSizeSmall: '--font-size-small',
  fontSizeBody: '--font-size-body',
  fontSizeBodyLarge: '--font-size-body-large',
  fontSizeSectionTitle: '--font-size-section-title',
  fontSizeHeadingTwo: '--font-size-heading-two',
  fontSizeHeadingOne: '--font-size-heading-one',
  fontSizeDisplay: '--font-size-display',
  fontSizeDisplayMin: '--font-size-display-min',
  fontSizeDisplayPreferred: '--font-size-display-preferred',
  fontSizeDisplayMax: '--font-size-display-max',
  lineHeightBody: '--line-height-body',
  lineHeightHeading: '--line-height-heading',
  lineHeightDisplay: '--line-height-display',
  weightRegular: '--font-weight-regular',
  weightMedium: '--font-weight-medium',
  weightSemibold: '--font-weight-semibold',
  weightBold: '--font-weight-bold',
  weightExtrabold: '--font-weight-extrabold',
  weightStrong: '--font-weight-strong',
  trackingLabel: '--letter-spacing-label',
  spaceNone: '--space-none',
  spaceXs: '--space-xs',
  spaceSm: '--space-sm',
  spaceMd: '--space-md',
  spaceLg: '--space-lg',
  spaceXl: '--space-xl',
  space2xl: '--space-2xl',
  space2_5xl: '--space-2-5xl',
  space3xl: '--space-3xl',
  space4xl: '--space-4xl',
  radiusSm: '--radius-sm',
  radiusMd: '--radius-md',
  radiusLg: '--radius-lg',
  radiusXl: '--radius-xl',
  radiusFull: '--radius-full',
  shadowSm: '--shadow-sm',
  shadowCard: '--shadow-card',
  shadowDropdown: '--shadow-dropdown',
  shadowModal: '--shadow-modal',
  shadowSticky: '--shadow-sticky',
  shadowHeader: '--shadow-header',
  shadowState: '--shadow-state',
  buttonHeightXs: '--button-height-xs',
  buttonHeightSm: '--button-height-sm',
  buttonHeightMd: '--button-height-md',
  buttonHeightLg: '--button-height-lg',
  inputHeight: '--input-height',
  headerHeightMin: '--header-height-min',
  headerHeightMax: '--header-height-max',
  sidebarWidth: '--sidebar-width',
  modalMaxWidthMin: '--modal-max-width-min',
  modalMaxWidthMax: '--modal-max-width-max',
  assetLogoMaxInlineSize: '--asset-logo-max-inline-size',
  assetLogoMaxBlockSize: '--asset-logo-max-block-size'
} as const);

export type DesignTokens = typeof DESIGN_TOKENS;
